### ISSUE TITLE
LEARN_DIF Code List error?

### ISSUE THREAD

**Issue by craig-petch** [jiscdev/analytics-udd#101]
Just to flag a discrepancy between the Values in the UDD definition for LEARN_DIF and the HESA values. The HESA values have  leading zeros and are 2 character strings, this format is also followed in the SRS.  As we are using the values in the UDD definitions to validate against we need the two definitions to be the same. I guess this also then needs reflecting in LRW validation too?

Craig

**Comment by wilmTap** [comment]
I think some of the thinking behind some of these value spaces was to accommodate a synthesis of HESA with FEILR vocabularies over time. That doesn't preclude using the literal HESA values in this case, though.

If people are agreed that we should harmonise, I propose we add it v1.3, because we could update existing values programmatically.

**Comment by wilmTap** [comment]
Check against HESA data futures; it might be a v2.0

**Comment by wilmTap** [comment]
OK, having delved into a bit more: the codes in student.DISABILITY1 and student.DISABILITY2 have collapsed a number of HESA categories. For example: HESA category 6 "Mental health difficulties" has been combined with HESA category 55 "A mental health condition, such as depression, schizophrenia or anxiety disorder" into UDD category 55 "A mental health condition such as depression schizophrenia or anxiety disorder". This means that there will be a discrepancy even if we do adopt HESA's leading zeroes.

The data dictionary proposed for HESA data futures suggests that the HESA disability codes won't change; they're just TBC.

We can do either one of two things:

1. Carry on with the codes as they are
2. Adopt the HESA codes verbatim, and map them to FEILR in some way

2 makes ETL easier in the future for HE, but could lead to issues when FEILR codes are mapped to them. It will be also a be breaking change with 1.2.x

**Comment by robwynj** [comment]
Hi Wilbert,

Sounds like HESA’s codes have also been updated for 16-17 then? If so we’ll need to review and possibly update any corresponding/ common field changes etc with HESA – suggested for v2 of the UDD maybe?

Rob
--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by arc12** [comment]
I note this issue now refers to both LEARN_DIF and DISABILITY.

I am of the view that many of the code lists we currently have are excessively detailed. While this detail may be justified for whole-sector data collections and policy-oriented analysis, I am quite unconvinced that the scale of data at a single institution is sufficiently large. Also, for a high-dimensional machine learning scenario, even a sample size which would be statistically useful for a report on a minority section of the population is likely to be noise. For example, knowing a student is blind is highly unlikely to be predictive of any outcome of interest, but there may be a statistically-significant difference in distribution of blind students between faculties. The issue here is that there are so many other attributes of students which are indicative of outcomes; success (or whatever) is not defined by disability.

One of the problems with detail, which the comments on this issue highlight, is that detail is likely to change. Mapping detail to detail as change happens is a nightmare. Similarly, mapping multiple (HESA, FEILR, +....) into a union code list which accommodates the detail in each leads us to a monster!

I suggest the resolution is to use more broad categories, with the standard rules for coalescence from the detail provided. This has already been done in parts of the UDD but we should probably go further. I think we should persue an approach where we don't worry about the effect on UDD of data futures or annual changes, and expect these changes to simply mean a fairly painless change to a "case" statement in some ETL.

**Comment by wilmTap** [comment]
Doh.

I just managed to mix up student.LEARN_DIF and student.DISABILITY1/2. Yes, we can introduce leading zeroes to the single digit values- now in a v1.3 patch.

As to @arc12's suggestion: the current UDD student.DISABILITY1 code list is already much reduced from the HESA 2015/2016 list, but could always be reduced further. What do other people think?

@robwynj: yes, it is different for 2016/17. [From HESA:](https://www.hesa.ac.uk/collection/c16051/revisionhistory/)

> Instance.LEARNDIF. This field has been removed for 2016/17, and superseded by Student.LLDDHEALTHPROB. The coverage of the new field is no different, although it is now collected on the Student entity.

**Comment by wilmTap** [comment]
Agreed to introduce the leading zeroes for LEARNDIF. Leave the rest.

**Comment by wilmTap** [comment]
Turns out that HESA's 2016-2017 LLDDHEALTHPROB _is_ different from 2015-16, and therefore what's in the UDD. I propose to keep the UDD LEARN_DIF as is for now in v1.2.7, and therefore still derived from HESA 2015/16 LEARNDIF.

I'm open about what we do with v1.3: we could just add the leading zeroes, or we could adopt [HESA's 2016-2017 LLDDHEALTHPROB,](https://www.hesa.ac.uk/collection/c16051/a/LLDDHEALTHPROB) which is bigger, but will be what's present in the HEps...
