### ISSUE TITLE
course duration would be a useful addition

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#109]

**Comment by wilmTap** [comment]
To be discussed

**Comment by alanepaull** [comment]
This issue has very little detail, so I'm thinking that we need to have a look at some data (preferably real) to get a handle on it.  @arc12: would you be able to flesh this one out a little, in respect of the data requirement, and examples?  Then I can have a bash at potential solutions.

**Comment by arc12** [comment]
"very little detail". You are too polite Alan!

We got this data as duration in years for UC Suffolk (SITS site). I believe Quercus holds the same.

The value is potentially useful as a discriminant in predictive modelling (although there are other attributes which are not independent from it, such as course aim and mode of study, it is a relatively clean and simple case). It is also helpful in making sense of the data in exploration activities and quality checking. As such, and to match what I expect to be common parlance among those in academia, I imagine that years is the right unit. "its a 2 year course".

I suspect this is purely a course membership attribute.

**Comment by arc12** [comment]
Propose this should be an integer number of months.
In notes, permit data which is "rounded" to 12*years if the actual number of months is not stored.

**Comment by alanepaull** [comment]
"It's a 2 year course" suggests that course_duration is a property of course, rather than of student_course_membership.  This is not HESA's SPLENGTH (Expected Length of Study), but is roughly the difference between the start and end of the course, in months.  Nothing in the HESA return seems suitable.  ILR doesn't have duration either, but does have start and end dates.

My hesitation in attaching it to course is that, if we have a "single" course with many durations, we'll have to reflect this with more course records, and maybe systems hold a course record with multiple durations?  For example, 1 year FT, 2 years PT, up to 5 years variable.  This suggests the XCRI-style 'presentations' structure, which sounds counter-productive to me.  However, a property containing multiple durations on one course record in UDD is horrible, as it won't be easy to analyse.

On the other hand, duration per se pertains to the course, rather than the student, so it's perhaps a bit forced to put it in as a property of student_course_membership.  The student doesn't influence course duration, though they may choose to take a 1FT or 2PT version.  duration seems more pertinent to a course as an offering.  As we don't deal with the offering aspect, I've added a course_duration property to student_course_membership to see if it will fly.
