### ISSUE TITLE
Dealing with required properties that allow NULL

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#110]
In the past, we decided to balance the need to be able to rely on the presence of at least some properties with the need to allow for different types of unknown/no value and the need to be consistent across the UDD by specifying NULL as an allowed value on all properties with codes, including ones that are required (cf issues #13 and #64).

It turns out that that simply doesn't work with the API. So we need to find a different solution.

One proposal is to make the required properties that allow NULL (listed below) optional. That's certainly possible, but it seems to me that some of those properties look kind of important, and they generally ought to be known to an institution. They're not values such as grades that can't be known yet at particular stages of the lifecycle.

The alternative is to drop the NULL value, and force institutions to pick from the other codes. This might break with @arc12's preference for consistency, and there'd also have to be a decision about what the default value should be. I think the existing 'unknown' would work, because the genuine absence of these values at source do seem to indicate a data quality problem, and not an expected state of affairs.

What do people prefer?

student.ETHNICITY
student.SEXID
student.LEARNDIF
student.DISABILITY1
student.DISABILITY2
student.TERMTIME_ACCOM
student.PARENTS_ED
student.SOCIO_EC
student.OVERSEAS

student_on_course_instance.MODE

student_course_membership.ENTRY_QUALS

**Comment by arc12** [comment]
I'd like to disect this a bit, with a view to clarifying "that simply doesn't work with the API".
(although I'm not just referring to the LRW API, and I think the UDD spec should accommodate a range of representations. A particular representation might be applicable for sending and receiving data to the LRW but this is a binding issue IMO)

I think NULL itself is a problematic term; its a bit of a hack for situations where we need to store a value which means "there is no value". So: I think the specification could reasonably talk about "missing data". and avoid reference to NULL, as it is a technology-specific concept.

Missing data in CSV seems straight-forward: two adjacent commas or a comma at a line end. This representation seems trouble-free in the tools I use (programmatic and desktop).

Missing data in JSON seems to be done in 2 common ways:
- if using an associative array, don't provide an entry
- provide explicit "key_name": null

The latter is probably more convenient, and the bandwidth overhead marginal for non-sparse data.

Using special codes (or indeed empty strings) for missing data is clumsy because we end up with several different representations (at the least we end up with difference for numerics and strings, maybe dates, at worst, difference for each attribute).

So:
- can we confirm that the issue is primarily a representational one, rather than a conceptual one about missing data.
- can we be clear precisely what the API problem is

Cheers, Adam

**Comment by wilmTap** [comment]
- I think it lurches into conceptual territory: what is the meaning of 'required' when NULL (in any for) is an allowed value
- From @ht2:

> I've tested the API as it stands, and no - it will NOT allows NULL to be passed in as the field is marked as a "required" field. To be honest, I think we just need to take off the idea of the field being "required" at all, set it to have a sensible default of NULL and allow NULL values to be sent in.

**Comment by robwynj** [comment]
I would prefer IMHO to keep this simple - and have a code/ value representing "No Source Data Available" (or something similar, or better worded!!), which highlights to the institution that they have a cleansing/ data collection issue aka NULL after any resultant analysis/ data load or update. 

At least it can be highlighted to them too, and differentiate from any other valid (HESA-type) codes for that field, in any data cleansing reports which we can then send back to them (for required fields) in a BAU (daily/ live update) scenario for example.

Some of these fields should simply not be optional - otherwise those which are, could or should allow nulls!

Rob

**Comment by arc12** [comment]
I wonder whether we should go back to the question of optional vs mandatory, to clarify requirements.

I understand there to be, for a data instance:
1. mandatory primary key fields, maybe composite
2. mandatory foreign key fields
3. other fields whose absence would make the data meaningless or would make processing the data very difficult or make dashboard presentation useless (e.g. no course titles). We make these mandatory. These have no support for an idea like "no source data available"; it the data isn't available the instance is just plain bad!
4. fields where we would normally expect there to be data but which, in a realistic SRS there might be a few instances without the data. These should be optional. For data quality assessment we want to highlight these because a large number of instances with missing data probably means some more work on the ETL is needed.
5. fields where we think that the data is quite useful/important from a LA point of view. We'd want to treat these similarly to #4 but it may well depend on the actual institutional use of LA, and its a different discussion about cost/benefits of acquiring the data vs what is probably a technical DBA discussion for #4.
6. fields where normal process means that data will not be known (e.g. end of module mark/grade). These should be mandatory. Data quality assessment can't be done simply by highlighting what is missing but may need more nuanced approaches which take account of the values in multiple fields.

1, 2, and 3 should be validation requirements. Hard, mean, un-bending!

4, 5 and 6 should not (although we might still imagine datatype conformity for data which is present). We should avoid making #4 mandatory with an "other" category because that will simply mean the ETL codes in a fall-back to "other" to pass validation, and we're still non-the-wiser. Instead, we should accommodate some data quality reporting as part of the on-boarding process (and possibly also as an ongoing monitoring). We might want to defer reporting-back on #6 until some initial data-exploration from a data science perspective has been undertaken, i.e. to not expect to generate an automatic/routine QA report.

If the problems we currently face have some basis in fields being treated as categories 1-3 above when they should be treated as 4-6, then lets resolve that first. Otherwise, we risk finding a solution to the wrong problem.

**Comment by wilmTap** [comment]
Make the referenced list optional. Get rid of the NULL values.

**Comment by wilmTap** [comment]
I've had a look at all required properties in v1.2.6, and came up with the lists below. "Necessary and required" will remain required in v1.2.7. the others will become optional with different degrees of health warning: "Desirable for presentation, but optional" will warn that several downstream apps may not work if omitted, and "Desirable for analysis, but optional" that analytics models will not function as well if omitted.

**Necessary and required**

- assessment_instance.MOD_INSTANCE_ID
- assessment_instance.ASSESS_INSTANCE_ID
- course.COURSE_ID
- course_instance.COURSE_ID
- course_instance.COURSE_INSTANCE_ID
- institution.TENANT_ID
- module.MOD_ID
- module_instance.MOD_INSTANCE_ID
- module_instance.MOD_ID
- module_VLE_map.VLE_MOD_ID
- module_VLE_map.MOD_INSTANCE_ID
- student.STUDENT_ID
- student_course_membership.STUDENT_ID
- student_course_membership.STUDENT_COURSE_MEMBERSHIP_ID
- student_course_membership.STUDENT_COURSE_MEMBERSHIP_SEQ
- student_course_membership.COURSE_ID
- student_on_assessment_instance.STUDENT_ID
- student_on_assessment_instance.STUDENT_COURSE_MEMBERSHIP_ID
- student_on_assessment_instance.STUDENT_COURSE_MEMBERSHIP_SEQ
- student_on_assessment_instance.MOD_INSTANCE_ID
- student_on_assessment_instance.ASSESS_INSTANCE_ID
- student_on_assessment_instance.ASSESS_SEQ_ID
- student_on_a_module_instance.STUDENT_ID
- student_on_a_module_instance.STUDENT_COURSE_MEMBERSHIP_ID
- student_on_a_module_instance.STUDENT_COURSE_MEMBERSHIP_SEQ
- student_on_a_module_instance.COURSE_INSTANCE_ID
- student_on_a_module_instance.MOD_INSTANCE_ID
- student_on_course_instance.STUDENT_ID
- student_on_course_instance.STUDENT_COURSE_MEMBERSHIP_ID
- student_on_course_instance.STUDENT_COURSE_MEMBERSHIP_SEQ
- student_on_a_module_instance.COURSE_INSTANCE_ID
- staff.STAFF_ID
- staff_on_course_instance.STAFF_ID
- staff_on_course_instance.COURSE_INSTANCE_ID
- staff_on_mod_instance.STAFF_ID
- staff_on_mod_instance.MOD_INSTANCE_ID

**Desirable for presentation, but optional**

- assessment_instance.ASSESS_TYPE_NAME
- assessment_instance.ASSESS_DETAIL
- course.SUBJECT
- course.TITLE
- course_instance.ACADEMIC_YEAR
- course_instance.START_DATE
- course_instance.END_DATE
- institution.TENANT_NAME
- module.MOD_NAME
- student_on_a_module_instance.MOD_START_DATE
- student_on_a_module_instance.MOD_END_DATE
- student_on_a_module_instance.MOD_RESULT
- student_course_membership.COURSE_GRADE
- student_on_assessment_instance.ASSESSMENT_RESULT
 
 **Desirable for analysis, but optional**

- assessment_instance.ASSESS_TYPE_ID
- assessment_instance.ASSESS_WEIGHT
- course.COURSE_AIM
- module.MOD_SUBJECT
- module.MOD_CREDITS
- module_instance.MOD_ONLINE
- module_instance.MOD_ACADEMIC_YEAR
- student.DOB
- student.ETHNICITY
- student.SEXID
- student.AGE
- student.LEARN_DIF
- student.DISABILITY1
- student.DISABILITY2
- student.DOMICILE
- student.TERMTIME_ACCOM
- student.PARENTS_ED
- student.SOCIO_EC
- student.OVERSEAS
- student_course_membership.ENTRY_QUALS
- student_course_membership.COURSE_OUTCOME
- student_course_membership.COURSE_OUTCOME
- student_course_membership.COURSE_EXPECTED_END_DATE
- student_on_assessment_instance.ASSESSMENT_CURRENT_ATTEMPT
- student_on_a_module_instance.MOD_CURRENT_ATTEMPT
- student_on_course_instance.MODE
- student_on_course_instance.YEAR_PRG
- student_on_course_instance.YEAR_STU

**Comment by arc12** [comment]
Thanks Wilbert - I think those categories of desirability are helpful.
We will review the lists and feed back. What time-frame are you expecting to progress 1.2.7 to release?

Adam

**Comment by wilmTap** [comment]
I'll have v1.2.7 ready to roll by Monday, and will release it after the meeting unless people shout.

Patch incoming...

**Comment by robwynj** [comment]
Hi Wilbert,

Would be useful to review the 1.2.7 changes, yes, prior to the release :)

We are in the middle of a lot of data transfers at the moment, so stability will be key wherever possible of course!

Kind Regards

Rob

**Comment by arc12** [comment]
Wilbert, all, there are quite a few here which I would categorise differently (both ways).

I think we should work through the list interactively, because the explanation of why I think X or Y about a given attribute may need to be given.

I've reflected a little on the "desirable" word. To my mind, there are some fields where we would expect the majority of instances to have the data available otherwise we're in deep trouble. There are others where its more a case of the attribute being generally useful. One of the issues is that some attributes are only likely to be useful for analysis if the level of population is good enough; if we think it likely that institutions will have only low levels then we should avoid making them think it is important, but OTOH if they DO have lots of records with the attribute then it may be worth putting the effort in to e.g. map stored values to UDD. SOCIO_EC is like this; its generally been too sparse from data I've seen so far, but if it were collected thoroughly....

I'd be happy to work through the list either on the main call or in a break-out (but I do think it needs to be more than me and Wilbert coming to a common understanding). The way we express this, and how the attributes are cattegoriesed is, I think, quite important for the message which institutional stakeholders receive, and how they prioritise the effort that goes into extraction.

It may be that we should have a separate "data extraction guide" which explains the likely* importance of each entity and attribute. This has been a topic of conversation at f2f client meetings. 
* - replete with caveats about "often it depends on what your objectives are"

**Comment by wilmTap** [comment]
Agreed that a discussion is needed, preferably with @robwynj and others.

I've tried to stick to the distinctions we agreed at the last meeting, but found that a) the distinction between needed for presentation and needed for analysis seems very debatable in many cases and b) the degree of necessity is almost infinitely varied but c) optionality is binary: it is or it is not.

Messaging is indeed crucial, so is consistency, and both may override nuance, I fear. Perhaps what we need is slightly different categories:
1. mandatory
2. critical, but a couple of missing records can be dealt with. Stuff will break if it's not there, up to you how much breakage you can live with.
3. desirable. Performance will be degraded if its missing.

Perhaps category 2 can be validated on an 80/20 basis: if something is missing on more than 20% of records, it won't be accepted. Category 3 is where I suspect some nuanced conversations would be helpful. But it'll also be stuff that we just can't count on.

**Comment by arc12** [comment]
Avoiding temptation to word-smith until after we've discussed the categorisation of the attributes...
i.e. I think the number and character of categories will more clearly emerge from trying to apply them.

BTW: I quite like metaphorical category names like platinum, gold, silver... or, for the more adventurous, how about pants, trousers, shirt ... to give a more visceral feeling of things you wouldn't want to be without in public ;-)
