### ISSUE TITLE
Dealing with Learning Difficulty and Disability Fields

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#114]
Ref #112 and #101. Separate issue created specifically for the LEARN_DIF and DISABILITY aspects. Attempt to simply state the issues!

Issues:
- LEARN_DIF and DISABILITY fields are conceptually overlapping
- value-spaces for categories defined for each field are conceptually overlapping
- HESA factorisation of LD and disability has changed for 16/17
- FEILR and HESA differ in factorisation
- there has been some code re-use
- there were mismatches between UDD and HESA codes in UDD <=1.2.6

**Comment by arc12** [comment]
Working through how the HESA and ILR legacy could map to a unified concise code list.

[UDD Proposed Rework Learndif, Health, Disability.pdf](https://github.com/jiscdev/analytics-udd/files/495741/UDD.Proposed.Rework.Learndif.Health.Disability.pdf)
[UDD Proposed Rework Learndif, Health, Disability.docx](https://github.com/jiscdev/analytics-udd/files/495742/UDD.Proposed.Rework.Learndif.Health.Disability.docx)

**Comment by wilmTap** [comment]
With regard to the final point about the mismatches; UDD <=1.2.6 student.LEARN_DIF or student.DISABILITY1/2 have a data type of int, so I wouldn't expect it to be represented as "01" . From what I can see, that is exactly what the LRW does; it's always '1'

That means that the mapping I proposed for v1.2.7 would work and is consistent with UDD <=1.2.6 data. That does not mean, however, that we couldn't jump to v1.3 now and abandon v1.2.7, and thereby adopt both string datatype for codelists of this sort, and Adam's mapping at the same time.

There might be an additional good reason for jumping to v1.3, as I've uncovered a snag with UDD <=1.2.6 student.LEARN_DIF values: because NULL was the defined value for 'no learning difficulty' in student.LEARN_DIF, and because the LRW doesn't handle required properties with NULL values, every student in there has '1' "Moderate learning difficulty" now...

As to Adam's proposal: I'd personally have no objection to it, other than that I suspect we may want to distinguish between visual and hearing impairments. The distinction is clear in all the source data, and I'd imagine that the experience of learning activities could be so different for both populations that you would want to at least be able to check whether there is a significant correlation with outcomes or other properties.

**Comment by arc12** [comment]
Picking up the three variations Wilbert suggests:
1. visual and auditory - happy with this
2. mental vs physical health - not so sure. See for example http://bjp.rcpsych.org/content/178/6/490. Some blurring of boundaries for ME/CFS. Fundamentally, I'm not convinced that the illness classified as "mental" share much in common, in terms of effect on student success etc, or that those classified as "general health" ditto; i,e, that mental/physical is a practically-meaningless distinction.
3. LEARN_DIF code 97 surely means "other learning difficulty" so should be in the learning category, not "other [disabilities]". i.e. where I put it.

Cheers, Adam
