### ISSUE TITLE
Add explicit 'not applicable yet' code to MARK properties

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#116]
With the move to strings for all UDD properties (see issue #85), it becomes possible to define a specific code for all MARK properties that indicates that they are not known yet. This, in turn, allows us to make some of these fields category 1 requireds.

**Comment by arc12** [comment]
@wilmTap the proposal was to make all categoricals be strings.
Mark is numerical.
If a mark is not known, it really must be left as missing data otherwise all manner of chaos...

If people really want to code up "not yet known" (and I still don't understand why this is necessary) please do this in a categorical RESULT field.

**Comment by wilmTap** [comment]
No change needed
