### ISSUE TITLE
Taking STUDENT_COURSE_MEMBERSHIP_SEQ out of entity PKs

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#129]
Give that we're heading towards getting rid of STUDENT_COURSE_MEMBERSHIP_SEQ as a property in v1.3, perhaps we ought to remove them from composite PKs in v1.2.7

**Comment by robwynj** [comment]
Considering it's not been interpreted as a PK (or part of a composite PK) with certain institutions/ plus the LRW API only treats STUDENT_COURSE_MEMBERSHIP_ID as the PK for data validation/ load. I would want to try and avoid adding this in now, especially if it's going in 1.3.x.

Kind Regards

Rob

**Comment by arc12** [comment]
we think it would be safest to keep the _SEQ in the PK specification for 1.2.7 because SITS institutions might require that for uniqueness.

We will continue to check for uniqueness with _SEQ as part of the composite.

Adam

**Comment by wilmTap** [comment]
Looks like a bind to me: without _SEQ, it seems we can't guarantee uniqueness for historic SITS data, but with it, other people have to make up data only to drop it again later. On balance, is adding a blanket "1" for non-SITS sites in ETL the least worst option?

I'd propose to settle this question definitively during the next scrum.

**Comment by arc12** [comment]
I hope we can get 1.3 (without SEQ) agreed fairly quickly.
Leave us to worry about migration; I imagine we'd just clean down the LRW and re-load. i.e. we'd sort the historic SITS data.

For non SITS sites, yes, using a single value in all instances is fine, not even a "least worst option". More than that: if they don't think SEQ is relevant it SHOULD be a single value (e.g. 1) so that the uniqueness check works.

The issue for us is that, until Craig can write/test ETL modifications allow us to dispense with SEQ, its not safe to move off.... which is why we'll continue to make the check on ingestion into our pipeline.

**Comment by robwynj** [comment]
Agreed 1.3 should exclude/ deprecate _SEQ. I do not want it as a composite PK on 1.2.x though (just for the sake of one or two versions potentially aka 1.2.7!)

**Comment by arc12** [comment]
OK.
I think what we suffer from is that 1.2.6 and prior are ambigious about uniqueness.
being specific about PKs in 1.2.7 was meant to change that, but we have some baked-in assumptions in the LRW.

We'll continue to require uniqueness on import but content to go with the flow for UDD.
