### ISSUE TITLE
Dealing with placement and exchange years

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#133]
Some institutions (e.g. Aston) routinely have one year of a programme which is not normal tuition. The data for that year will clearly be different, saying something different about a student's progress but also potentially meaning we should skip them from predictions for that year.

UDD doesn;t currently support this scenario.
I think a minimal requirement is to be able to signal placement/exchange at Stu on Course Inistance.

Candidate for 1.3 please.

**Comment by alanepaull** [comment]
HESA handles this issue through Location Of Study (https://www.hesa.ac.uk/collection/c16051/a/locsdy/).  This HESA field covers not just sandwich years, but also years abroad, which I think would be another case for this issue.

I think it would be worth investigating how much detail we need in the UDD for this.  Is it simply to record a year which is not normal tuition, or the reason for it as well?  If the former, then one standard statement or code would do.  If the reason is also required, then a coding frame of some sort would be in order.  There are also cases where a student is away for most of the year, or a significant part of it (thin sandwich or a period abroad but not the whole year).  If we need to cover these examples too, then we would need to consider going down the HESA coded values route, I suspect.

student_on_course_instance would be the logical place to hold the information.  That would also match HESA's practice, via INSTANCE.LOCSDY.  student_on_course_instance has the COURSE_LOCATION property that is derived from HESA Campus ID.  However, it's conceptually similar to HESA Location Of Study, though the content of COURSE_LOCATION is very different from both HESA fields.  COURSE_LOCATION is String with any value, whereas HESA's CAMPID and Location Of Study are single character codes.

The simplest solution to meet Adam's minimal requirement would be a flag on student_on_course_instance to indicate a year which is not normal tuition, coupled with a careful definition.

Rather than providing alternative solutions at this stage, I'd like to wait till we have a view on the "detail" question above.

**Comment by arc12** [comment]
@alanepaull - thanks for that clear summary.
I suspect a flag would do for now, but that we'd regret the decision. We'd have to define the flag in terms of the HESA codes, I suppose, and there are not so many that just adopting the code list would be a problem. We can then map to our own flags according to different requirements, which may emerge over time.

I imagine that a similar set of categories apply to FE/skills but that we will need considerably more detail. For example, I imagine that we will need to allow for work experience periods to be covered in UDD.

My vote is to adopt the HESA LOCSDY.

Adam

**Comment by alanepaull** [comment]
Monday 19 Dec:
Implement as @arc12 suggests above.

**Comment by arc12** [comment]
I move to include in v1.3.0

I think we are close to agreement.
