### ISSUE TITLE
Confirmation of Cardinality eg. STUDENT entity fields (Mandatory vs Optional)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#134]
Hi Wilbert (and all),

I want us to review and confirm (for sign-off for UDD 1.2.7) the mandatory / optional aspect of certain fields in UDD 1.2.7 proposed branch.

https://github.com/jiscdev/analytics-udd/blob/v1.2.7/udd/student.md

I knew we had "NULL" in as a value / option in those fields, when mandatory - now NULL has been removed, these fields have NOT become mandatory. I just want to discuss and confirm, with the wider team - prior to sign-off of 1.2.7, if these fields eg. ETHNICITY, which have predictive relevant too, should indeed be optional? It just doesn't feel right to me, when institutions should attend to these - and use some of the other options/ values available to denote them as "Not Known" etc.

I think some of these fields (and possibly others elsewhere) should remain mandatory?

Discuss!

Kind Regards

Rob

**Comment by arc12** [comment]
Rob -
I understand you are posing several queries, for which my understanding/views are:
1. lists of codes give the permitted values. Optional attributes may also have missing values. NULL is a placeholder for "missing" when a storage value is required so can always be used for storing/transferring values of optional attributes.
2. I think it is helpful for lots of useful attributes to remain optional if they don't actually stop anything working. i.e. keep mandatory for when something is absolutely required for validity. Other things we might prefer may not be available, or a client may decide they are not comfortable with their use. We should inspect these are part of onboarding QA. Yes, institutions should attend to these but with guidance rather than requirement.
3. I would prefer explicit "not known" codes to only be used when the SRS has explicit "not known" codes stored. These will generally be minority codes. This means it is easy to consistently count and trap NULLs across all attributes.

Adam

**Comment by alanepaull** [comment]
I've had a read through of the previous discussions over NULL values  (#110), and compared 1.2.6 (current master) with 1.2.7.  1.2.7 has the following characteristics for this issue:

1) NULL values have been removed from the coding frames.
2) In Student, the following fields were changed to optional:
	DOB [0..1]
	ETHNICITY [0..1]
	SEXID [0..1]
	AGE [0..1]
	LEARN_DIF [0..1]
	DISABILITY1 [0..1]
	DISABILITY2 [0..1]
	DOMICILE [0..1]
	TERMTIME_ACCOM [0..1]
	PARENTS_ED [0..1]
	SOCIO_EC [0..1]
	OVERSEAS [0..1]
3) The implication of making these fields optional is that no data will be supplied if it is not available.
3) The Notes in many (most?) of these fields give a rationale or impact of not supplying the data.

However, some of the Notes are ambiguous now, because they imply that the data is mandatory when it is not.  For example DISABILITY1: "If disability is unknown, code '0' or '99' should be provided".  If the field is optional, then it should be explicit in the Notes that 'no data' is not the same as 'unknown', and that 'no data' means leave the field blank, while 'disability is unknown', means provide the code for 'unknown'.

I suspect that the confusion will disappear if we review the Notes and make it clear what to do when data is not available - I'm happy to do that, if we feel it's a good idea.

If a field is optional (as now for those fields listed above in 1.2.7), that would conventionally mean 'leave the field blank'.  Using NULL as a value for 'no data' means returning to making these fields mandatory - but have regard to the #110 discussion before going there.  Requiring a NULL value for 'no data' may be problematic, as Adam has indicated above.  Worse, as in Adam's point 3, would be using legitimate codes for 'not known' that are not actually in the data, because we are then changing the semantic meaning of the data.

Is blank better than 'NULL' values for these fields?

**Comment by alanepaull** [comment]
There are some cases where the field is indicated as 'optional', but in fact the coding frame covers all cases (I believe).  For example the SEXID vocabulary has values of 1, 2 and 3 that cover all the HESA and FEILR values, but also 4, which explicitly covers 'Unknown'.  So if there's no data, '4' would be expected, and that's stated in the Notes.  That instruction effectively makes SEXID mandatory.

**Comment by robwynj** [comment]
I would like to take a similar approach to HESA on this - and also we should align against the category denotation (especially categories 3 & 4, for predictive modelling purposes!) for mandatory fields....

When I saw the STUDENT entity earlier, it just doesn't look right!

Kind Regards

Rob

**Comment by wilmTap** [comment]
FWIW, I've written v1.2.7 so far with the following in mind:

1. Operationally, there is no way to distinguish between an optional property or a property that is mandatory but allows a NULL or blank value (see issue #110). As a result, UDD compliant data is expected to have either explicit values for a property, or the property just doesn't exist.
2. Apart from links between entities, the answer to the question "which property is mandatory?" is "it depends". It depends on which apps you need to support, what source data you have, and what you are trying to achieve. Hence the new guide to mandatory values (see issue #120).

Having said that, I think @alanepaull is right in that some comments may have gotten out of sync with the cardinality constraints. Also, the documentation should also be explicit about the difference between what you need to do if you support a property as an institution, but don't have a data point for a particular student, and what an institution needs to do if it doesn't support that particular property at all.

As to @robwynj's point about making some of the properties mandatory again: we could, but only if we create explicit 'unknown' or 'not provided' values for each of them. But, getting consensus about  that approach, consensus about the choice of properties to make mandatory again and making the changes to the UDD source itself could well set us back another week or two. It depends on what people feel is the priority...

**Comment by arc12** [comment]
I agree with the comments made about documentation being (part of) the issue here. I think its the main issue, actually, and that 1st call should be to try to fix the documentation. I think we've been going in the right direction recently and I an application of logic and consistency to what we have will "do the trick".

I think it is also worth looking to the future; I see it as being quite likely that there will be some UDD attributes which are "FE only" or "HE only", for which the situation is that FEonly attributes simply do not exist in a HE context. I hope there won't be many of these but it would be a reasonable price to pay for avoiding forking the UDD.

**Comment by wilmTap** [comment]
In the documentation, I think it's mostly the notes that lagged a bit; being agile has a cost... These are all being addressed by @alanepaull, however.

I think the nub of this is issue is how best to communicate to institutions what properties are really important: putting them in a category that says what they are needed for, or making them mandatory but allowing a "not known" value in case they really can't submit it?

I propose to take the definitive decision during the next scrum on Monday.
