### ISSUE TITLE
Change of LEARN_DIF in 1.2.7 is breaking

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#137]
The code list for 1.2.7 and master branches differ.
e.g. 99 has gone.
e.g. the meaning of 1 has changed.

This is IMO a breaking change.
I need to rely on the codes assigned by institutions who have already mapped to ETL.

**Comment by wilmTap** [comment]
The difference between student.LEARN_DIF v1.2.6 and v1.2.7 is intentional. 

As per issue #130, AFAICS, _all_ student records in https://jiscv2.learninglocker.net/api/jisc/v1.2.5/ have been coded with "1", which, according to HESA learndif and the UDD prior to v1.2.6, should mean "Moderate learning difficulty". That every student would have such a challenge seems a little unlikely. More likely is that all these records were marked as "1" to get past the student.LEARN_DIF requirement constraint.

Given the choice, fitting the definition to the data seemed less bad than persisting with the definition when we know all current data doesn't comply, and makes future data indeterminate.

**Comment by arc12** [comment]
That can't be right!

I checked on the Edgehill and Aston data in LRW.
Their records have 99 for LEARN_DIF, and no 1 in sight!

And our previous work with UCS and Exeter (which never made it into LRW) used the pre-1.2.7 coding.

And there are the people using the current spec for mapping as of now.

As a cure for bad data, this is worse than the illness! If code lists dont stay consistent, I'll end up in the mad house. Seriously!

If anyone feeds us data with everyone having moderate learning difficulty, they will find out from our QA process.

**Comment by wilmTap** [comment]
I just double checked with the v1.2.6 UDD API, and if I search for records with a student.LEARN_DIF value that is anything other than "1", I get nothing

`https://jiscv2.learninglocker.net/api/jisc/v1.2.6/student?query={"LEARN_DIF":"!=1"}&limit=100`

If I search for student.LEARN_DIF with a value that is "1" (or "01"), I get however many I want

`https://jiscv2.learninglocker.net/api/jisc/v1.2.6/student?query={"LEARN_DIF":"01"}&limit=100`

What am I missing?

**Comment by wilmTap** [comment]
I can see what I'm missing now: real data.

When I run `https://jiscv2.learninglocker.net/api/jisc/v1.2.6/institution` I only get "Tenant001". The students don't look entirely plausible either, so I'm guessing I'm only authorised to see the University of Jisc.

From what @arc12 is saying, the real data he can see is rather different from the dummy data, so I'm assuming that the other datasets aren't as categorically wrong either, but that might be worth checking by those who have access.

I'll reinstate the v1.2.6 LEARN_DIF vocabulary.

**Comment by arc12** [comment]
ta!
