### ISSUE TITLE
Strategy for Dealing with HE/FE Differences

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#145]
We will shortly have to come to terms with this.
The sooner the better since the strategy needs to be implemented asap if we are to avoid/minimise rework.

0. principle of clarity
Whatever method of dealing with the differences is adopted, it must be clear what is passed to downstream systems. i.e. the differences should be somehow declared to allow for validation and alternative processing routes without deep inspection and guess-work (which may be hard on fragmentary updates)

1. principle of uniformity of the entity-relational structure
Most important for us is avoiding divergence of the entities in UDD (ignoring for now the detail of the associated attributes). Keeping consistency in PKs and relational structure will be important for LRW dev/maintenance too. I believe we should have as a principle that the set of entities is uniform across sectors. It may be that we need to finesse some of the descriptions of what the entities are so that the alignment between the entities and on-the-ground practice is documented for different sectors.

2. requirement for sector-specific attributes (fields)
It is clear that different sectors have different attributes in their data landscape. e.g. entry points for HE, school for FE. Other attributes will be common; although they may be described using different categories, the concepts which the attribute captures are close enough to be practically indistringuishable at the data-level (i.e. there may be nuances but the actual data misses these nuances due to the practicalities of capture/management). The LRW does not need to care about the attributes actually used.
Do we agree this is a requirement?
Proposed approach for UDD:
- document the union-set of all attributes for a given entity in the UDD markdown
- group attributes as "core", "HE" and "FE" (possibly require >1 FE set for Scottish FE)*
- "core" is always required
- UDD schema declaration (see https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/institution.md) includes a sector identifier, e.g. v1.3#HE indicates UDD v1.3 with the HE extended attributes
- validation of non-core sets switches according to the schema declaration

\* - rather than grouping these in the attribute list at the top of the markdown, it may be better to initially list the attributes as either "core" or "extended" and then to separately indicate those for each sector, in order that the same extended attribute can be used in more than one sector list without making the initial list of attributes having to contain repeats.

3. requirement for sector-specific code lists
Different code lists are in use but are often mappable to a broad set of categories (e.g. the disability and learning difficulty case https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/student.md#difflearn1).
In some cases broad categories loose detail.
Principle: if it is tractable to define a small code list with broad categories to which different sector practices can be mapped, then this should be done - i.e. a UDD-defined code list applied to all sectors with the mapping to sector detail codes provided as an informative aid to mapping source data. For cases when the detail is required, an additional UDD attribute should be created (one attribute, NOT one per sector).
Proposal for dealing with cases where a set of broad (mapped-to) terms is not tractable, or where supplementary detail attributes are required:
- permit different code lists to be used for the same UDD attribute
- document these code lists in the UDD, aligning them to the UDD schema declaration of sector (see #2 above)
- switch validation accordinly

-------
I think that strikes a reasonable balance between suppressing and accommodating differences, and ensuring that the differences are manageable in the validation/lrw/analytics pipeline.

**Comment by alanepaull** [comment]
First many thanks to @arc12 for such a clear exposition of the problem and approach to a solution.

I am in broad agreement with the approach and the principles here.

Although there is a parallel between Uni <> HESA, and FE Coll <> ILR, the structure and details in the HESA v ILR returns are very different, owing to their differing purposes.  While we've placed the UDD pretty close to HESA in a few places, for convenience, I think we'll have to re-address that perhaps in some cases.  I think it's much more preferable to align with institutional systems (Unis and FE Colls) rather than HESA / ILR (or Scottish Govt).

Looking at the principles:

0. principle of clarity - agreed.  Any complexity should lie in our working out the best way to do it, not in the presentation of the outcome.

1. principle of uniformity of the entity-relational structure - I very much hope we can do this.  A difficulty may come with any extra demands that FE may place on UDD, owing to their greater focus on funding initiatives and the broad issue that 'apprenticeships may be different' ( I don't yet know the answer to that).  There are some interesting and useful extra structural components that FE might well seek to include (for example LearnerDestinationandProgression, which is after course completion and therefore not in the UDD).  Of course, useful ones from FE may be useful to HE too, so could go in the core.  Although the ILR output structure is different from UDD (they have no course_instance entity for example), I suspect that FE Colleges should be able to map to the current UDD structure from their FE Coll systems.

2. requirement for sector-specific attributes (fields) - from a data spec point-of-view this should be do-able.  There will be implications for Rob and Huw's validation tool, because that picks up the details from these files.  This approach would mean we'll have to be extremely careful to be consistent and accurate with the layout and formatting, both for reader understanding and for the validation tool.  The detail of how we construct this will probably have to be decided by Rob and Huw.

3. requirement for sector-specific code lists - I agree.  I think it will be necessary to be very careful that the semantic meanings of attributes with separate code lists are in fact sufficiently synonymous; as we know, sometimes things can look similar, but be very different (cf. course_id vs learning_aim_reference).  Otherwise there may be a danger that the analysis will be damaged.

In all of the above we'll need to be very aware that any 'finessing of descriptions' (from point 1) or sector-specific changes (from points 2 and 3) might impact on the dashboard, student app or other usages of the processed data, even though it might give us a consistent way of importing the data across FE and HE.

Alan
