### ISSUE TITLE
String(8) for post codes is not adequate

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#148]
For overseas students, their local postcode format might be long
e.g. {some numbers} TRONDHEIM

This should not cause validation failure

Propose: increase number of permitted chars

**Comment by alanepaull** [comment]
This only applies to ENTRY_POSTCODE, not POSTCODE, I believe, because the latter it term time postcode, so should be a UK postcode.

Taking information from here (admittedly not a standards body): http://www.pidm.net/postal%20code.html (particularly the validation section towards the end), I've increased the postcode property to 10 characters, specifically noting that "the longest postal code currently in use in the world is 10 digits long."

I've tweaked the Valid Values and Notes bits too, because the HESA-derived version only has 8 characters as it covers only UK domiciled students.

**Comment by leebaylis** [comment]
Just thinking about distance learners, year abroad students, or students attending branches of institutions in other countries etc — couldn't their POSTCODE could be non-UK?


> On 19 Dec 2016, at 14:34, alanepaull <notifications@github.com> wrote:
> 
> This only applies to ENTRY_POSTCODE, not POSTCODE, I believe, because the latter it term time postcode, so should be a UK postcode.
> 
> Taking information from here (admittedly not a standards body): http://www.pidm.net/postal%20code.html (particularly the validation section towards the end), I've increased the postcode property to 10 characters, specifically noting that "the longest postal code currently in use in the world is 10 digits long."
> 
> I've tweaked the Valid Values and Notes bits too, because the HESA-derived version only has 8 characters as it covers only UK domiciled students.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800.

**Comment by alanepaull** [comment]
Good point, Lee.  Perhaps both should be changed.  I'll do that now.

**Comment by robwynj** [comment]
Agreed. Usually not collected by HESA for those outside the UK aka GB domiciles...
