### ISSUE TITLE
Prior attainment

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#158]
FE colleges collect, store and use a wide range of information about the learner's prior attainment, for example English language and Mathematics qualifications.  This information is reviewed and used to formulate learning plans (including specific pathways to qualifications) and targets.  Much of this information will be available within FE student record systems and / or other supporting systems.  It is used not only to monitor and improve the progression of students, but also  to assess the value-added produced by the college.  Therefore, it is highly likely to be relevant to FE college use of learning analytics.

UDD currently only has ENTRY_QUALS and ENTRY_POINTS (properties of student_course_membership).  These have coded values lacking in detail.

In the medium term, it is possible that some institutions in both the HE and the FE sectors will want to include this type of information in the Learning Analytics service.

**Comment by arc12** [comment]
That sounds like a sensible inclusion.

To what extent can we define a list of the important facets of prior attainment?

If we can lay these out as concepts...

ENTRY_QUALS seems worth continuing. Its codes are crude but still potentially discriminating. Even in the case where they are all the same for some institutions, thats not a problem
ENTRY_POINTS is formally UCAS entry points, I suppose, but other points systems may come to pass.

Maths and English seem uncontroversial, and could be used for situations other than GCSE level prior attainment. Potentially for entry exams at HE. So: conceptually, I would avoid any tie in to a kind of qualification, although particular code lists might be applicable,

**Comment by alanepaull** [comment]
Current ENTRY_QUALS covers both the ILR codes for prior attainment and the HESA one - both are broad (or crude if you prefer).  ILR also has fields for English and for Maths, which are updated each year, so they start out as prior attainment fields.

We need some more information from FE on what they capture, noting that it will vary.  I'm due to visit Bedford College again soon, so I should be able to follow up then, even if Roy and Conn are not able to join this conversation.  However, some wider appreciation - Dumfries & Galloway, NI and Wales, as well as more English colleges - would be very useful.

For HE, unis do tend to collect more than just UCAS points, even if it's just to check that students have achieved what they've stated.  But then again, I'm unsure of how much this type of information is currently used; or might be in future.  Uni and FE college perspectives would be very useful.

**Comment by alanepaull** [comment]
From FE group discussions on Monday 6 Feb:

Using our FE spreadsheet (https://docs.google.com/spreadsheets/d/1f4iaubCTbIVqBcBoLuRM_3nBatGkbHhrJmzQWUM5C1Y), we will capture any new data items that FE colleagues would like to include for analytics purposes within the areas of prior attainment and initial assessment, for example for English and Maths.  Where there are data items that can be included in the UDD without breaking the current master version, we will add them to a draft v1.2.8.  See the spreadsheet for drafts of v1.2.8 - these will be added to github after mapping work and further discussions.

Alan

**Comment by alanepaull** [comment]
I've started to add in tentative properties to the UDD draft v1.2.8 tab on the google doc at https://docs.google.com/spreadsheets/d/1f4iaubCTbIVqBcBoLuRM_3nBatGkbHhrJmzQWUM5C1Y.  I've addressed them through student_course_membership and student_on_course_instance.  Each student will have 1 live student_course_membership record at any one time, representing the student studying on 1 programme of learning.

So far, I've suggested 5 optional properties on student_course_membership:

AV_GCSE_POINTS_SCORE
PRIOR_ATTAINMENT_ENGLISH
PRIOR_ATTAINMENT_MATHEMATICS
INITIAL_ASSESSMENT_ENGLISH
INITIAL_ASSESSMENT_MATHEMATICS

and 2 optional properties on student_on_course_instance:

PREDICTED_OUTCOME
TARGET_ATTAINMENT

These properties should only be included, if we have an explicit rationale for usage in analytics.  Others could be added using this criterion.

For this type of property, please add your comments to this issue.

Alan

**Comment by arc12** [comment]
In terms of version management, I'm keen to NOT have a 1.2.8 but to move to 1.3.x; dealing with forking will cause us overhead we can;t afford.

Query: why do we need to have a new field for a GCSE score when ENTRY_POINTS already exists? The only case we'd need two fields is for datasets which contain both HE and FE students.  My vote is to use one element.

What about the new GCSE grading? I assume there will be a compatible scale so that new and old GCSE grade students will be comparable.

For the prior and initial attainment/assessment:
is it feasible for these to be numerical values? The actual scale doesn't matter, so long as there is consistency across an institution's data. Un-ordered codes will be unhelpful here. Better to require the data provider to map onto a scale of some kind.  For prior GCSE, this could be the points as per AV_GCSE_SCORE. 

Re the SoCI additions:
We'll need these to be comparable with themselves and other data elements. If they are expressed as "mark or grade" we'll be unable to make sensible use of these in a routine process. I think the use cases for these data points need some exploration, from a data analytical point of view.
I DO think it will be useful to identify students who seem to be achieving below what would be expected and we could look at predictive analytics to identify students who may fail to reach their potential. Is that what "TARGET" signifies? We need to be careful about including as data something which is a staff member target agreed with a student, or the predictions of a staff member. These MAY be useful but there is potential for misunderstanding and mishap. If staff predictions, then what happens when learning analytics systems start to get used by staff; do we build some unwanted feedback?

**Comment by alanepaull** [comment]
Thanks for your comments, @arc12.

We don't need AV_GCSE_POINTS_SCORE (my bad, sorry).  We should use ENTRY_POINTS, and I'll adjust that one.  In terms of the FE type of content, I would like more responses about what Colleges currently have and what is needed in the analytics.  If there is more than one approach, then we want to map to a single consistent one that does the job. Re new GCSE grading - I assume there will be some form of similar points scale that can be mapped.

I agree.  We need some form of consistent scale, so that it can be used in the analysis.  For this, we'll need some practical examples of what's currently in the domain.

Re the SoCI additions:
My understanding of the user need here (from the staff perspective) is that there should be a record of a predicted outcome, as a way of comparing against progression.  It seems logical to associate that with the mark or grade scheme of the course stage, and / or course as a whole.  I know this is a complex area (for example there's ALIS and ALPS that have large scale systems for such work), and I'm not an expert in it.  I guess a question is whether we adopt something that is consistently applied across many institutions and is straightforward to understand, or whether it is consistent across specific mark or grade schemes and understanding comes from the local context.  The former may require users to adapt to a different notation or visualisation, though it might be sufficiently simple to work well.  The latter may be more difficult to implement, but may be more directly understandable by users.

Predicted outcome usually depends (I believe) on a range of factors, and may be calculated (rather than a subjective prediction by a staff member.  I'm not certain of the detail behind this.  However, "target" signifies a level of attainment set and agreed with the student as a means of motivation.  My discussions at Bedford College suggested that both predicted outcome and attainment target were important, because they offer different ways of measuring progress and achievement.

In respect of EBS, or other Tribal systems, what's the data like that might support these new properties?

Alan

**Comment by arc12** [comment]
@alanepaull thanks Alan. For the SoCI cases, I think the core issue is probably whether the use cases are like:
"Teachers/etc just want to be able to see this information as part of the student page in the dashboard"
Implication = this is anything goes text
or like
"This will be involved in the LA"
Implication = anything does not go!

Key point is that people should not expect us to do "magic" data analysis unless the content of these data elements are clear, comparable, etc. If its just propagating student profile info... fine
I suspect the informative rather than analytical intention, and I rather suppose we'll not make rapid progress unless we nail "informative only" onto the door. Maybe simply clarify intention.

**Comment by alanepaull** [comment]
I'm hesitant to address the versioning question, because there seem to be some conflicting pressures that I haven't sufficient overall perspective to comment on.

Strictly in terms of github management, it's easier for us to have a v1.3 development strand series, rather than to introduce a new v1.2.8.  If all development goes into v1.3, then we can easily suggest ideas, discuss and commit solutions to that version, so that all the v1.3 changes are implemented via one branch.  If some need to be delayed, we can use 1.3.1, 1.3.2, and so on, relatively painlessly, as we did with the earlier version series.  A new v1.2.8 would require agreed changes to be fitted to the 1.3 version as well as the current v1.2.7 master, because v1.2.8 would be a second different branch in front of v1.2.7.  If there were only limited changes, this could be handled through additional commits to v1.3 as well as v1.2.7.  So by no means impossible, as long as changes in v1.2.8 were small in number and impact.

Alan

**Comment by arc12** [comment]
I think this needs some discussion to identify what, if anything is appropriate for a v1.3.0

I suspect only the average points score is clear enough at present, and that the others will need further work informed by available data.

**Comment by alanepaull** [comment]
Proposal is to update the ENTRY_POINTS property of student_course_membership, so that, as an alternative to UCAS points for HE entry, it can be used in FE for average GCSE points score.  Precise description of "average GCSE points score" is needed, as there are several different ways of doing this, with different weightings for English and Mathematics for example.

Is there a need for historical data in this area?  This might require variation in what average GCSE points score means, or using a compatible mapping for valid comparison.

FE colleagues to advise on this, please.

**Comment by arc12** [comment]
I don't think we mind what the precise description is. More important is that there is consistency between past and current students and amongst students in the same year. I imagine colleges or other upstream data handlers will have dealt with both of these consistencies.

**Comment by alanepaull** [comment]
There is not a single consistent way in which FE colleges calculate the average GCSE points score.  Commonly used are the QCA one (58 points for A*, 52 for A, 46 for B, 40 for C, and so on), or the ALPS system (8 for A*, 7 for A, 6 for B, 5 for C, and so on).  I think that, for now, we can ask for consistency across the institution (historical and live data), but not insist on a particular scheme.

**Comment by arc12** [comment]
I totally agree.
