### ISSUE TITLE
Multiple personal tutors

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#160]
We currently have a single field on STUDENT: TUTOR_STAFF_ID

This hasn;t been a problem yet, but then we haven't really progressed to the stage in any pilot where it would.

The question is: can we reasonably forsee a case where more than one member of staff would have an arbitrary set of students assigned to them which are not disjoint? i.e. student could have >1 tutor not associated with course/module membership
I think the answer is "yes".

Assignment by course or module group is covered.
I think it would make sense to future-proof ourselves with a simple joining entity akin to the staff-on-module-instance, but which associates staff with students in a personal-tutor-like role. Indeed, it may be a no-brainer as the LRW UDD support moves to a RDBMS.

**Comment by arc12** [comment]
Unless anyone can identify a harmful consequence for changing, I suggest we add to v1.3.0.

**Comment by alanepaull** [comment]
Proposal is to replace the current tutor_staff_id property on STUDENT with the following.

- create a new STUDENT_TUTOR element:
Description: This entity relates each student to 0, 1 or more academic staff, usually in a role akin to personal tutor.

Properties:
student_id *
staff_id *

- add relationships:
STUDENT has 0, 1 or many STUDENT_TUTOR.
STAFF has 0, 1 or many STUDENT_TUTOR

**Comment by michaelwebbjisc** [comment]
I can see the theory,  but I'm still reluctant to introduce things that force db joins for any commonly accessed information, regardless of db type, unless it's absolutely necessary.  At the moment for our pilots it's always a 1-1 relationship.  So can we park this until it is actually a live issue, and then come up with a solution that only requires db joins if the institutions does actually have a many to one relationship.

**Comment by robwynj** [comment]
Agreed

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk/>

**Comment by alanepaull** [comment]
Monday 13 Feb: Agreed to park this for future version.

**Comment by alanepaull** [comment]
Is "multiple personal tutors" an issue that we'd like to address for v1.4? It's a breaking change, so shouldn't go in v1.3.1.

**Comment by arc12** [comment]
I have no view, other than "this might happen" and that we might want to future-proof ourselves.

In practice, the comment made by our sites is: "we dont have personal tutor data in a form suitable for extract or reliable enough for access control", or something along those lines. We've still not processed real data for this.

Suggest the answer to the question is to ask pilot sites whether they expect to have singular personal tutors.

**Comment by robwynj** [comment]
I would say so – HEIs are going to be (on several fronts!) variable of course in approach to how they manage interventions, and other processes at their specific institution – staff in student support may perform interventions (not the tutor) for example, or they are both able to see student data, so do you have a separate field for that purpose (to hold support/ intervention staff id), or just allow multiples anyway. It does make me think about the types of (and how) staff linking to student, or linked or able to access data per dept/ organisation level entity which may also be required in future (but let’s wait for institutions to ask for these as feature requirements, and bring them into the product planning piece for UDD).

Kind Regards

Rob



--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by robwynj** [comment]
I would like to put this in, yes, but again, not been drive by customers (not seen by me, yet, anyway!) – keen to have staff id for a non-tutor (intervening) member of staff, included. Also keen to look at staff linkage to organisational units provided, to go beyond module/ course instance student (data/ views) access.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by leebaylis** [comment]
Doesn't tutor change from year to year -- so shouldn't tutor_id be on studentcourseinstance or studentcoursemembership (I can never remember which is which) instead at least...

I have a use case in that data explorer site admins want to be able to build caseloads of students so that they can evaluate the tool as if they were a personal tutor. There are of course other ways we can achieve this, and so the question is whether we achieve it by distorting the data explorer code or by abstracting the UDD.

**Comment by alanepaull** [comment]
Current description of TUTOR_STAFF_ID is: "This is the unique identification number for the learner's academic or course year supervisor/ tutor, or alternatively the id of the contact who will be responsible for handling Learning Analytics alerts and notification regarding the student". So, I would agree that looks like it should more properly be on, or linked to, the student_on_course_instance entity, from a logical model point of view. There may have been practical reasons why it was put on the student entity though.

I suggest that we consider this in the light of the multiple tutor records issue with respect to v1.4. Switching this property from student to student_on_course_instance would presumably be a breaking change.

**Comment by arc12** [comment]
It would break our code to change this.
Having it on student isnt an issue so long as there is only one; the attribute can just be updated.
... but it is conceivable for there to be multiple staff members.

I'm not convinced putting it on student-course-instance is a good idea, as it doesnt really solve the multiplicity issue. I think that the only robust approach to multiplicity will be a "joining entity".

I suspect the path of least action is for DataEx to have some business logic which takes a union of UDD-origin tutor relations (1:1) + some DataEx bogus tutor relations.

**Comment by leebaylis** [comment]
I think a joining entity is the only way we'll solve multiple tutors, for sure -- although we may want to add a period field as well so that we have historical information about changing tutors from year to year etc. 

Yes, I would not really suggest mutating the UDD just for this DatEx application -- although I also hesitate to hack about with the DatEx code just for this as well :(

**Comment by robwynj** [comment]
My suggestion, even initially, would be to have something like OTHER_STAFF_ID (extra optional field, linking to STAFF, who maybe the person intervening/ able to view student info via SSP for example) or have multiple staff entries (whether they are tutors or not!) associated with the STUDENT... to be discussed for UDD 1.4/5 etc.

**Comment by leebaylis** [comment]
I dunno about that, I can see it becoming used for loads of different things as a catchall -- maybe better to have an optional staff role field in the joining table

**Comment by alanepaull** [comment]
We've had wide-ranging discussions about the issues around associating multiple members of staff to students, primarily in the context of the student entity, but also in relation to staff_on_module_instance and staff_on_course_instance. Other relevant entities, such as student_course_membership and student_on_course_instance have also been mentioned. It feels to me that we don't (yet) have a clear view of potential new requirements around the staff relationship to students in a formal UDD sense.

I've started to investigate some form of generic staff role entity that might replace  staff_on_module_instance and staff_on_course_instance, and also fulfill a requirement relating staff and student. These relationships include things like staff <> student, staff <> course, staff <> course_instance, staff <> module_instance, staff <> assessment_instance. A logical model for this type of relationship would consist of joining entities for each candidate, so that the nature of the relationship - mandatory/optional; 0, 1, many - and any necessary or useful attributes could be considered. I'm not sure whether a physical model with one generic joining entity has advantages over specific ones, especially as a generic entity would presumably have to include FKs to multiple existing entities. My recommendation at this stage would be to consider each requirement for an explicit relationship as and when it arises, rather than to attempt to put in place something generic soon that might not satisfy new requirements in the future.

The OP was a clearly expressed request for a joining entity between the staff and student entities to cover the case where "more than one member of staff would have an arbitrary set of students assigned to them which are not disjoint". Maybe we should address this particular example, at least as an exercise even if we don't implement it quickly. We could then get a handle on the types of extra properties that might be required and might be useful. I'll start on that aspect and see how it develops.

Meanwhile, I'll leave the issue open for discussion at a later date.

**Comment by alanepaull** [comment]
Monday 19 March 2018: agreed to close issue. Covered in #241.
