### ISSUE TITLE
v1.3.0 Prior/initial - Change Entity?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#170]
Currently these are on STUDENT:
PRIOR_ATTAINMENT_ENGLISH [0..1]
PRIOR_ATTAINMENT_MATHEMATICS [0..1]
INITIAL_ASSESSMENT_ENGLISH [0..1]
INITIAL_ASSESSMENT_MATHEMATICS [0..1] 

BUT... I think the logic of these fits better with STUDEN_COURSE_MEMBERSHIP
e.g. student starts HNC with school GCSEs but retakes them as part of their programme, then progresses to HND. Prior attainment is now the retakes.
In those SRS which do store this on student, and over-write, the data can just map to SCM, but if the data is stored against an enrolment then we're better having it that way.

Propose these 4 attributes are on STUDENT_COURSE_MEMBERSHIP

**Comment by alanepaull** [comment]
@arc12's model works OK for HE, where a student does one course at a time (HNC, then HND, then UG degree, then Masters, for example).  However, I was attempting to cover FE, in which case we have students usually doing more than one course at a time, for example, a couple of courses in IT, a GCSE in English, and a GCSE in Maths.  In this case, I think PRIOR_ATTAINMENT sits more logically with the student entity - or we end up repeating the data in student_course_membership, or not knowing which of multiple student_course_membership records to put it.

If it's on student_course_membership, the logic might be to put it on the "appropriate" one, for example a PRIOR_ATTAINMENT_ENGLISH on the GCSE English student_course_membership.  However, the difficulty here is where the student is assessed as not needing to take a GCSE in English (probably because they already have a high grade), in which case we have no place to record PRIOR_ATTAINMENT_ENGLISH or INITIAL_ASSESSMENT_ENGLISH, because we don't have the relevant student_course_membership record.

Alternatively, we mark one of the student_course_memberships as the "main" one; but in this case we're just admitting it should go on student :).

In the view I've described here, PRIOR_ATTAINMENT is what they achieved before their first enrollment at the institution, and INITIAL_ASSESSMENT is how the college assessed them immediately they enrolled on the programme of learning.  If they achieved a GCSE in English alongside their HNC, that would be recorded in the GCSE English student_course_membership - it wouldn't be a PRIOR_ATTAINMENT.

**Comment by arc12** [comment]
@alanepaull repeating data is not a problem IMO.

If a student begins multiple courses at the same time,whether or not as a "programme" then the prior attainment would appear on each. The interpretation may differ: for the GCSE English retake it is the baseline, for a HNC it is still an indicator of the student's English ability. We don't lose a place to put it if the student on a programme does not need to retake; it goes on the HNC etc.

I think knowledge of the student's maths and english ability at the start of a course has general utility. 
It is in the same boat as entry quals, entry points. It helps us to work out students who are more/less well equipped for a given course, not just english/maths courses.

re " If they achieved a GCSE in English alongside their HNC, that would be recorded in the GCSE English student_course_membership - it wouldn't be a PRIOR_ATTAINMENT."
I think in both places. We, as data processors, need a simple logic. One place to look for "what is the english/maths ability of this student on entry to the course"

I see "prior" as being pertinent to a course, not refering to a prior institution, because we're working on course-level risk. Furthermore, the loss of information which will occur due to overwriting a value on STUDENT is undesirable. Problems for 14-19 age in FE?

**Comment by alanepaull** [comment]
If repeating data is not a problem, I think my objections largely disappear.  PRIOR_ATTAINMENT, as you say, then is relevant to a particular course start.

**Comment by michaelwebbjisc** [comment]
Yes, I think we live with the repeating data issue for now.
