### ISSUE TITLE
v1.3.0 Prior/initial value space/definition/type

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#171]
PRIOR_ATTAINMENT_ENGLISH [0..1]
PRIOR_ATTAINMENT_MATHEMATICS [0..1]
I think the language here should not be purely GCSE. Consider the Scottish system.
I also think we will find a grade-centric approach to be too limiting and will want to have a point-value for prior attainment as well (the grade may be useful for display in a dashboard or student profile). I suspect this is not feasible for 1.3.0 but wonder whether the names should be PRIOR_GRADE_* so that we keep the option open for a different way of expressing the attainment without ending up with confusing attribute names.

INITIAL_ASSESSMENT_ENGLISH [0..1]
INITIAL_ASSESSMENT_MATHEMATICS [0..1]
Having these as strings feels like a horrible limitation. I strongly urge that these should be numerical not just that the text should say "usually numerical". These should, when possible be a mark against a consistent range, preferably a percentage. If the source data does not have a mark then use a numerical rank for the ordinal position of the grade, or a 0/1 for fail/pass. The problem with strings is that we might get ideosyncratic values which differ between all sites. We would have to treat them as opaque categories whereas the results of an initial assessment can be ordered. At least for GCSEs we know what the order of grades is, and there are extant points-values, so we can (although I'd rather not) translated.
For 1.3.0 I strongly urge a numerical treatment, potentially with some renaming of the attributes to accommodate the reality that we might want to add a grade at some point.

**Comment by alanepaull** [comment]
I agree with @arc12.  I hope that FE colleagues may chip in, because we're singing in the dark a bit.

PRIOR_GRADE_* looks like a good solution, with a simple amendment of description to:
"States the best relevant qualification grade in xxxxxx achieved by the student before enrolling."

Re Initial Assessment properties, I was hoping to cover a few of the angles.  Some colleges may not be able to provide a numerical value?  Is it not the case that we need consistency across an institution, but not between institutions here?

I think that, maybe, for v1.3.0 we could go with a numeric value requirement, then if there's problems we can refine for v1.3.1.  For now, could we keep it simple, and just say Format = numeric, but leave Valid Values = Any numeric?  Then we don't have to impose specifics till we know more about what they are.

**Comment by michaelwebbjisc** [comment]
'I think that, maybe, for v1.3.0 we could go with a numeric value requirement, then if there's problems we can refine for v1.3.1' makes sense to me.

**Comment by alanepaull** [comment]
I've gone with the INITIAL_ASSESSMENT_* properties as Format = Decimal; PRIOR_GRADE_* as string (10).
