### ISSUE TITLE
Add attribute to see if student came in via clearing to student course membership

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#176]

**Comment by arc12** [comment]
This has been raised in our conversations with clients too.

+1 for inclusion

**Comment by craig-petch** [comment]
+1. It's been raised as possible extension for one site at least.

**Comment by alanepaull** [comment]
Small question: do we also want to include Adjustment? See: https://www.ucas.com/ucas/undergraduate/apply-and-track/results/adjustment-%E2%80%93-if-you%E2%80%99ve-done-better-expected
I've included this in the valid values in case it's important.

New property on student_course_membership:

CLEARING [0..1]
Student was accepted on the course via the post-A level results UCAS Clearing scheme or via Adjustment.

Valid values:
0 - not accepted via Clearing
1 - accepted via Clearing
2 - accepted via Adjustment
3 - not known

Format: string (255) - because it's a coded value.
Default value should be '3'.  However, we don't use that concept in the UDD, I think, so in effect blank also means 'not known'.

**Comment by alanepaull** [comment]
Alternatively:
0 - accepted, but not via Clearing, or not on a course in the UCAS undergraduate scheme.

**Comment by craig-petch** [comment]
In SITS we have the following values, reviewing some counts there looks to be more cases of RPA, than Adjustment so we should probably capture that as well
N = Normal application (0)
C = Clearing (1)
A = Adjustment (2)
R = RPA (3) (An RPA is a Record of Prior Acceptance, where an application is submitted to UCAS via an institution when an unconditional firm has been offered and accepted by the applicant.)
4 or blank - 'not known'

**Comment by arc12** [comment]
... or generalise this attribute to be entry method

we might want to deal with clearing vs not clearing but there may be other facets
unconditional offer?

**Comment by alanepaull** [comment]
... Also Extra?... And these are just UCAS ones. We might want to include a code for those courses not recruiting through UCAS.

Do we need all of these?  I can see the value of knowing about Extra, Clearing or not Clearing.  But Adjustment and RPA students are very akin to 'normal' applications, so may not be very relevant to learning analytics.

**Comment by craig-petch** [comment]
Yes, these will be UCAS ones.   I suspect that Not Clearing, clearing, Extra would be sufficient. We could expand the remit to capture conditional/unconditional offers but it maybe more straightforward for that to be a new attribute also on SCM maybe ENTRY_OFFER_TYPE?

**Comment by arc12** [comment]
I would go with a general purpose attribute which can accommodate UCAS or non-UCAS application processes, and define a short code  list with
a) a "may be extended" caveat
b) initial set of codes which explicity referr to the undergrad UCAS process.

Agree with Craig that a separate offer type attribute would be best, should we wish to use that fact

**Comment by alanepaull** [comment]
Monday 13 March: we agreed that for v1.3.0, we would have just Clearing or not Clearing. Any more sophisticated stuff can be considered for v1.3.1.

**Comment by alanepaull** [comment]
We need details of the use case(s) and data likely to be available, so that we can make progress with this issue.

**Comment by alanepaull** [comment]
Monday 24 April: Agreed to leave the issue open and discuss again later if necessary. Keep under review.

**Comment by alanepaull** [comment]
Noting that we wanted to keep the issue of Admissions Route on the agenda, do we yet have relevant data to allow us to make progress with this item? Is there any action in extensions for this data?

Current property on student_course_membership is:

## ADMISSIONS_ROUTE
### Description
States whether the student was accepted via UCAS Clearing or via some other route.

### Purpose
Analytics

### Derivation
SRS systems

### Valid Values
 <table>
            <tr>
                <td>ADMISSIONS_ROUTE</td>
                <td>DESCRIPTION (ENGLISH)</td>
                <td>DESCRIPTION (WELSH)</td>
            </tr>
            <tr>
                <td>0</td>
                <td>Student was accepted onto the course via a route other than UCAS Clearing</td>
                <td> </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Student was accepted onto the course via UCAS Clearing</td>
                <td> </td>
            </tr>
</table>

### Format
String (1)

### Notes
Code list may be extended in future.

**Comment by robwynj** [comment]
Definitely put this in IMHO. Have we had institutions bat for this, out of interest?

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Monday 19 March 2018: Proposal - add in a new value for Widening Participation initiatives. I propose to add also some of the values indicated by @craig-petch above, so that the whole new value space for v1.4 looks like this:

0 Accepted through default application route
1 Student was accepted onto the course via UCAS Clearing
2 Student was accepted onto the course via a Widening Participation initiative
3 Student was accepted onto the course via UCAS Adjustment
4 Student was accepted onto the course via UCAS Record of Prior Acceptance

These particular admissions route values can, I believe, be readily identified in student record systems, if a provider wishes to provide this data.

Description becomes:
States whether the student was accepted via the default application route, via Clearing or another specialist route.

Notes:
Code list may be extended in future. Similar codes related to this property or to offer types can be specified using the extensions functionality.

**Comment by alanepaull** [comment]
Monday 9 April 2018: agreed to implement the above proposal. Now done
