### ISSUE TITLE
v1.3.0 COURSE.AWARDING_BODY

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#180]
There should probably be some guidance for what instititions with DAP should put here;  bearing in mind that there may institutions with self-awarded and externally awarded quals, and some "not known" data, simply leaving it blank for self-awarded may be not a good idea (but is, I suspect, what will happen), unless ALL courses are self-awarded.

**Comment by alanepaull** [comment]
There is a list of awarding bodies used in the KIS I believe.  However, I'm not sure what info the FE colleges in particular would have.  They should be able to get stuff from LARS - however, that's not likely to be a source that HE would use.

However, isn't this likely to be used by the institution?  They may have an internal "standard" for this.  If we have a good source of awarding body names and uni/college names, we should use that.  KIS has already addressed this I think, so I'll do a bit of research.

**Comment by arc12** [comment]
I had a quick look at Ofqual. They do have names and identifiers. Then I thought that the current UDD words around "just be consistent within your data" was OK. Maybe experience with a variety of real data will tell us otherwise. My hunch is we'll be OK seeing what we get, but still I wonder: what should appear when a course is awarded by the institution iteself?

**Comment by alanepaull** [comment]
I've tried to find a good list of awarding bodies and providers over the years, for use in XCRI and elsewhere.  It was always a bit of a nightmare, because of how 'awarding body' was defined.  So, I was quite glad when official organisations like Ofqual and HESA (via KIS) started doing it; though they very often have purely funding based definitions that aren't wide enough for general usage.

If there's a good source that is easy to use by everyone, then that's the one to go for... but a big IF.

**Comment by michaelwebbjisc** [comment]
Can it be the UKPRN?

**Comment by alanepaull** [comment]
Unfortunately, UKPRN only includes providers, not other awarding bodies.
Ideally, we'd use their main URL as the ID, I guess.  For XCRI-CAP we said "The common name of the awarding body"; that was because back then we couldn't find a good enough source.

**Comment by arc12** [comment]
Suggest: for 1.3.0 simply add that for cases where a dataset includes both externally-awarded and internally-awared (DAP) course outcomes then the institution should identify itself using its preferred short-form name/code.

**Comment by alanepaull** [comment]
Monday 13 March: We agreed to use UKPRN as the default value.  After a bit more investigation after Monday, it turns out that most awarding bodies seem to have UKPRNs, though there may be exceptions.  There doesn't seem to be a good definitive list anywhere of *all* awarding bodies.  However, UKPRNs seem to be a useful starting point.  So, UKPRN as default, with preferred short form name as alternative.
