### ISSUE TITLE
MODULE.MOD_SUBJECT - Should be changed to allow multiple JACS3 codes per individual MODULE

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#184]
The multiples here would therefore align with how HESA hold this information

**Comment by arc12** [comment]
see #100

**Comment by alanepaull** [comment]
Monday 13 March: we agreed to introduce 2 new entities:  module_subject and course_subject, and to remove the subject properties from the course (SUBJECT) and module (MOD_SUBJECT) entities.

module_subject entity will have the following properties:
MODULE_SUBJECT_ID - single PK, like others with composite uniqueness constraints.
MOD_ID (foreign key to module)
MODULE_SUBJECT_CODE (JACS initially)

course_subject entity will have the following properties:
COURSE_SUBJECT_ID - single PK, like others with composite uniqueness constraints.
COURSE_ID (foreign key to module)
COURSE_SUBJECT_CODE (JACS initially)

**Comment by arc12** [comment]
I believe this needs some more thought.

I assert that the point of UDD is to support analytical use - specifically learning analytics - rather than to simply propagate SRS situations where multiple codes are associated.

I contend that we have not given adequate attention to what SUBJECT should contain. Full four character JACS codes have been developed to support national statistical use including the analysis of vulnerable etc subjects. We are not doing this; the scale and information requirement is different. Four figure codes draw distinctions which are unusable in practical learning analytics at institutional level. In practice, I expect we will only very rarely be able to make effective use of anything more detailed than the primary group (JACS letter code).

Question: how much of the problem would go away if we used only the primary group?

Allied to this: considering the rollout of HECoS, what are the operational benefits of having only the primary groups (or a level 2 code)? (both in terms of handling the codes and managing the case when we have some source data JACS coded and some HECoS coded)
Similarly, considering transitition from FE to HE, it will be easier to use a mapping to a common subject spine based on broad subject areas. For example to work out whether there is a common subject area between prior studies and the course in progress.

The single most important fact is the answer to "what is the main subject area"? If this is known, we have a workable approach in the current UDD. I am a little sceptical about the idea that this cannot be stated for modules, except in some edge cases. For courses, it is clear that there are more than edge cases due to joint and combined awards. For many of these, however, I would expect a major/minor split to exist.

IF we are going to accommodate multiple subjects then we really should have a weighting. If the source data system cannot provide a weighting then we're probably as well ditching the subject data and using a proxy (e.g. the department), unless the use of primary subject makes the problem go away because all the codes have the same letter or a guess could be made based on the proportion of letters.

Multiplicity of coding does imply an overhead in terms of data processing: ultimately we need to get to a tabular data structure at e.g. student-on-module-instance level to feed into a machine learning algorithm. It would be easy to make SUBJECT effectively unusable!

Finally: it may be better to always call the attribute SUBJECT rather than differentiating module and course, given the semantics and coding scheme will be the same.

IN summary: need more thought about the use of SUBJECT before complicating the data structure.

**Comment by alanepaull** [comment]
I agree we'll need further discussions about subject.  We have already agreed that in #100.  This is an interim decision prior to these further discussions.

Notwithstanding that agreement on future discussions, it was the view at Monday's meeting that we needed multiple subjects in v1.3.0. I suspect that for modules this is less important (though this was the context of the initial issue raised here), but describing courses with 1 JACS is problematic, if the intention is to identify a main, unambiguous subject - this was part of the rationale for HECoS after all.

I suspect that subject in the course entity at least is effectively unusable, if it's just 1 JACS code.  For modules, I suspect we *could* get away with just 1 in most cases; but that is where the request came from.

I named the properties COURSE_SUBJECT and MODULE_SUBJECT, so that they were clearly differentiated, as in many cases the content of a MODULE_SUBJECT may not relate to COURSE_SUBJECT.

I agree that we need to give this more thought. If there was to general agreement to go back to the previous version (SUBJECT on course, MOD_SUBJECT on module), I wouldn't lose any sleep! However, institutions will at least understand the multiple subjects, because it enables them to output a la HESA.

Does the implementation in v1.3.0 cause problems?

**Comment by arc12** [comment]
Changing subject was not on the cards when we were agreeing scope a few weeks ago, for v1.3.0
Making the change will prevent us from using subject where we are using it now.
I would only want to make a change to our code if the changed-to position is "known good". An interim decision which throws a spanner in the works is not good!

**Comment by alanepaull** [comment]
I remain actively disinterested in the outcome for v1.3.0 - I'm happy either way.  However, I would like to make sure that we have agreement for one or the other in respect of v1.3.0 before we progress further.  Bearing in mind that the new subject entities WILL require existing data to change (spanners in works!), please indicate support for **Proposal 1** or **Proposal 2**, preferably giving brief reasons.

**Proposal 1**: Revert the subject changes back to the v1.2 form, in other words, course has SUBJECT, module has MOD_SUBJECT, removing the new subject entities.  Consider change at greater leisure.

**Proposal 2**: Leave v1.3.0 as it is, in other words, retain the new subject entities.

I'm counting @arc12 as FOR proposal 1 👍.

**Comment by alanepaull** [comment]
Rob also agrees with Proposal 1 (remove multiple subjects) in relation to v1.3.0.
Unless I hear of any interest in Proposal 2 (retain new subject entities) by close of play today, I will carry out Proposal 1 (Revert the subject changes back to the v1.2 form, in other words, course has SUBJECT, module has MOD_SUBJECT, removing the new subject entities. Consider change at greater leisure.)

Alan

**Comment by alanepaull** [comment]
Now completed the reversion.  Will wait till Monday's meeting (27th) to close.
