### ISSUE TITLE
Length of TENANT_ID too short for LRW

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#186]
Currently the TENANT_ID is String(8), but if the LRW generates the TENANT_ID, it will be String(36) because it generates a version 4 UUID. Can we please change this to String(36) in the spec?

**Comment by alanepaull** [comment]
Looking at #169, I believe we'd agreed that the LRW would generate primary keys only where the key was a composite one.  So there would be no need for the LRW to generate the PK for institution.  I suggest that the following entities don't need LRW PKs, because there isn't a composite uniqueness constraint, and the PKs must be supplied by the data provider:

assessment_instance
course
course_instance
institution
module
module_instance
staff
student
student_course_membership

Also student_id_map currently only has a composite primary key, not a single one.

So, the ones that need a generated PK would be:

module_vle_map
period
staff_on_course_instance
staff_on_mod_instance
student_on_a_module_instance
student_on_assessment_instance
student_on_course_instance

I've omitted course_subject and module_subject for the moment, because they're being discussed separately.

**Comment by arc12** [comment]
add to this that the ids for the following MUST always be meaningful to people in the institution:
course
institution
module
staff
student

**Comment by ryansmith94** [comment]
Ok thanks @alanepaull, I'll change the LRW so that we only generate primary keys for the following the models:
- module_vle_map
- period
- staff_on_course_instance
- staff_on_mod_instance
- student_on_a_module_instance
- student_on_assessment_instance
- student_on_course_instance

The [student_id_map will require a primary key in order to work with extensions](https://github.com/jiscdev/analytics-udd/issues/74#issuecomment-283012036).

**Comment by alanepaull** [comment]
I'm pulling @ryansmith94's final comment out as a separate issue, because it's not part of this one.
