### ISSUE TITLE
student_id_map: does it require a primary key in order to work with extensions?

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#187]
If student_id_map needs a single primary key property generated by the LRW on loading or supplied by the data provider, I can add into v1.3.0.  Can we confirm this?

**Comment by arc12** [comment]
I don't forsee we'd need to either
a) refer to entity instances
b) extend them

So I think we can leave this as it stands and avoid generating etc

**Comment by ryansmith94** [comment]
I should point out that you will also have no way to retrieve a single student_id_map via the API without a single primary key.

**Comment by ht2** [comment]
@ryansmith94 raises a good point here. We now have a primary ID across all other entities that allows the new API to directly reference a model. 

If one isn't specified by the UDD here, then we will have to generate a custom `ID` that we will store on each model anyway and be return with a newly created model. Otherwise we'll need to create a completely unique method for GET/PATCH/DELETE on this entity, probably based on concatenation again, which given we'd ruled out everywhere else, I'd be keen to avoid now.

**Comment by arc12** [comment]
good point - needed for delete and patch.

**Comment by alanepaull** [comment]
Hmmm... STUDENT_ID_MAP_ID.  Strictly correct naming, so I'll use it unless anyone objects?

**Comment by alanepaull** [comment]
Now completed.  Will close after Monday meeting, if no problems.
