### ISSUE TITLE
Challange - MOD_FIRST_MARK documentation

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#189]
see #115 

I think this issue was incorrectly "resolved"/closed.

I believe FIRST was first introduced in the v1.2 proposal from Tribal and noted as being the first mark/grade awarded for the given module instance. This is particularly useful when looking at re-assessment data. This would be the initial Mark they obtained so provides some history.

This first mark is an essential fact. Students who get a 2nd attempt at assessment for a module will get the ACTUAL/AGREED marks set to the 2nd attempt values. This will clearly mess up our attempts to create a predictive model for 1st attempts. Also, 2nd attempts are likely to have their mark capped at the passing score.

This is how we have been using FIRST since last spring. Issue #115 includes a comment from me to this effect but this aspect was not further addressed before the issue was closed. The current text refers to first-marker which is a) marginal in utility, b) likely not to be available.

You might claim "this is a spec change". However, prior to the commit indicated in #115, the usage of FIRST was "The first or initial grade a student achieved on the module." Hence, I think the change to refer to first-marker is unjustified and should be removed (in addition to the fact that it puts a spanner in our attempts to reconstruct history)

**Comment by alanepaull** [comment]
An important part of this might be: What is the current interpretation across our users?  Are folks following what's written against the current master, v1.2.7 and v1.3.0, or is common practice as stated in @arc12's comment here?

If it's the former, then we have a small problem.  If the latter, then we can change documentation to fit practice and not lose any sleep over it.

So we have 2 proposals, I believe:

**Proposal 1**: leave it alone, so MOD_FIRST_ is described as "The mark awarded by the initial marker prior to any moderation process."  In this case, we would have to address "1st attempt" in some other way.  This doesn't look like an attractive proposal to me, because it probably requires a substantive change to resolve "1st attempt".

**Proposal 2**: change MOD_FIRST_ description to something like it was in the earlier days of v1.2, but clarified: "The mark/grade a student was awarded on their first attempt at the module."  **Notes**: "This mark/grade should not be changed after subsequent attempts at the same module, as it is used in analytics."  Should we make explicit reference in the notes to moderation / confirmation?  I think not, because MOD_FIRST_ seems to address a different issue.

Views?

**Comment by arc12** [comment]
Re current usage:
- all SITS sites we've handled use the first-attempt semantics
- Our non-SITS sites appear to do the same based on the data (see attached plot)
![index](https://cloud.githubusercontent.com/assets/842131/24151534/f9c03380-0e40-11e7-9c20-2b7c1b0345d5.png)

**Comment by alanepaull** [comment]
Monday 27 March: Proposal 2 agreed.
