### ISSUE TITLE
Future student predictive/ analysis field to collect? CARELEAVER (HESA collected field)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#193]
Maybe we talked about this in the past, but would the collection of this field via UDD (typically via studentcoursemembership) have direct relevancy and benefit to our OFFA/ widening participation angle with Learning Analytics?

https://www.hesa.ac.uk/collection/c16051/a/careleaver

Kind Regards

Rob

**Comment by alanepaull** [comment]
CARELEAVER is a mandatory field in HESA returns for Home/EU UG and PGCE students. There doesn't seem to be a comparable FE ILR field, though that will need to be double-checked by FE colleagues; I suspect it's covered in FE via funding sources.

If we decide to adopt this property, it would sit in student_course_membership, because it applies at the point a student joins a course. The HESA code values could be mapped to equivalent UDD values, so that we would retain the opportunity to map relevant FE values across to a common set.

**Comment by arc12** [comment]
are "estranged students" also in a similar category?

**Comment by alanepaull** [comment]
Monday 24 April: we agreed to consider the data perspective first, evaluate the need using an extension, look at demand and then examine its inclusion in the UDD.
General principle: use an evidence-based approach to the inclusion of new data. In principle, we will need evidence of data availability, usefulness for learning analytics and demand.
Issue left open as a reminder that folks may wish to experiment with this item.

**Comment by alanepaull** [comment]
We reviewed this before - we leave alone - could be an extension or HEI bats for it if they want it for predictive modelling
From Rob.
Now close.
