### ISSUE TITLE
Student Assessment Instance Actual Marks

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#199]
One institution has raw assessment marks that can be over 100.

Assess agree mark and Assess actual mark are constrained 0...100

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md#assess_agreed_mark

Is this constraint necessary given we have :

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md#max_points

The would like tutors to be able to view the actual mark rather than a percentage in data explorer etc.

Although we could reverse calculate the score on display we could end up with rounding errors, so it seems better to me to store the actual values.

**Comment by michaelwebbjisc** [comment]
Talking to myself... (by actually been talking to Josh offline).

By constraining the value from 0..100 we've implied its a percentage mark, but we haven't actually stated that.

Having it as a percentage is better from a calculation percentage.

We've actually got another issue, in that some institutions want to show grades, and some marks.

Another option is to introduce a new value:

ASSESS_DISPLAY_VALUE  (or something)

which is the value that should be shown on a dashboard etc.  We can leave this as a string, so it could be a grade or a value.  

We could then clarify that assess_xx_marks is a percentage.

**Comment by alanepaull** [comment]
On assessment_instance MAX_MARKS is defined as a Decimal: "The maximum numeric marks that an instructor can allocate to an assessment. Used to indicate the marking scale used for an assignment." This value is not constrained, so for example a 0-200 point marking scale would be MAX_MARKS = "200". This value is used in LA calculations on numeric fields, I think.

On student_on_assessment_instance, we have:
ASSESS_AGREED_MARK
ASSESS_ACTUAL_MARK
MAX_POINTS

ASSESS_ACTUAL_MARK is something of a misnomer, because it's constrained to 0-100. If I score 80 marks on a 0-200 point scale, I'll have ASSESS_ACTUAL_MARK = "40". ASSESS_AGREED_MARK is similarly constrained, so both these fields contain data already processed into percentages on import into the LRW.

MAX_POINTS is a String defined as: "The maximum points that an instructor can allocate to an assessment. Used to indicate the marking scale used for an assignment." Its Purpose is apparently "Analytics", which is a bit counter-intuitive, as it's a String, and the Notes suggest it's not used for calculations.

Question 1: Do we want the LRW to contain numeric marks that are processed into percentages?
  Answer: Yes?! It currently does, and I guess that analytics is dependent on this. These percentages exist in historic data, so I would bet that changing this might be A Bad Idea.

Question 2: Do we want the LRW to contain raw numeric marks that haven't been processed into percentages?
  Answer: Only if we need to display them? So, from what Michael is saying here, Yes.

Question 3: If the answer to Q2 is Yes, do we need the raw numeric marks to cover both raw actual marks and raw agreed marks?
  Answer: If we have raw actuals, then raw agreed seems to follow logically.

**Conclusions**
I suggest these changes (I think non-breaking, so could be in v1.3.1):

1) Make ASSESS_AGREED_MARK, and ASSESS_ACTUAL_MARK explicitly into percentages for clarity.

2) Introduce 2 new optional properties into student_on_assessment_instance: RAW_AGREED_MARK and RAW_ACTUAL_MARK for those institutions that want to record and display these.

3) Clarify the descriptions and purposes of MAX_POINTS and MAX_MARKS.
    a) MAX_POINTS (on student_on_assessment_instance): Ideally I'd change the name of this to MAX_MARKS, because it's defined as a String, not numeric. Be explicit in its Purpose that this is for display, not calculation? Description should say: "The maximum **mark or grade** that an instructor can allocate..."
    b) MAX_MARKS (on assessment_instance): Ideally I'd change the name of this to MAX_POINTS, because it's a Decimal, and it's used for calculations. This stays as unconstrained Decimal, so that it can be used to show the actual marking scale for numeric marking schemes.

I guess we could get away with not swapping those names, but changing the documentation to clarify.

**Comment by ht2** [comment]
FYI: Attaching the xAPI way of handling this for reference: 
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#Score

**Comment by alanepaull** [comment]
Monday 5 June 17: We discussed this issue at length. We agreed the following points:

(1) to change the format of student_on_assessment_instance.md#max_points to Decimal and adjust Notes accordingly.

(2) to add RAW_ACTUAL_MARK (decimal), with the usual purpose to enable storage of the original numerical score from the VLE.

(3) to add RAW_AGREED_MARK (decimal), with the usual purpose to enable storage of the original numerical score from the SRS.

(4) to document the format of ASSESS_AGREED_MARK and ASSESS_ACTUAL_MARK explicitly as percentages (currently they're only implied as this).

As we don't normally change a live version, I'd like clarification (Michael? Rob? Huw?) about whether these changes should be made on v1.3.0 directly or restricted to v1.3.1.

**Comment by alanepaull** [comment]
Changes in previous comment implemented in v1.3.1.
