### ISSUE TITLE
Student on Course Instance > X_YEAR_AVERAGE_MARK > No definition

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/analytics-udd#203]
Looking at:
https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/student_on_course_instance.md

Although the field "X_YEAR_AVERAGE_MARK" is listed, there is no body definition for this field. The Web Validator unit tests are failing because of this.

**Comment by alanepaull** [comment]
Good point. That's because the property definition has been entitled X_YEAR_AVERAGE_GRADE, rather than MARK. That's also true in the master and v1.2.7 versions.

I propose to change all titles. This will leave the list of properties at the top unchanged, but will change the title of the property definition from X_YEAR_AVERAGE_GRADE to X_YEAR_AVERAGE_MARK. Is that OK?

**Comment by alanepaull** [comment]
Now completed. I'll close it at the next Monday call.
Alan

**Comment by huwrobertsjisc** [comment]
Thank you

**Comment by alanepaull** [comment]
Monday 5 June 17: we agreed to mark X_YEAR_AVERAGE_MARK on student_on_course_instance as deprecated and to review the other properties with "X" values.
