### ISSUE TITLE
Should "extensions" be part of the formal UDD specification (UDD v1.3.x)?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#208]
https://github.com/jiscdev/analytics-udd/blob/v1.3.1/extension.md

This may need exposure within the UDD for customers, and also sourcing for use in UDD validation too (and encryption of fields, if required).

Kind Regards

Rob

**Comment by alanepaull** [comment]
#74 refers. We decided that it was too difficult to control extension labelling within the UDD itself, because these were likely to come up quickly. It would be a matter for the responsible owner of the extension to ensure it was used properly.

I believe the intention was as follows. Any specific extension would not normally be used by a large section of customers, but primarily as an experiment by  1 institution, a vendor, or perhaps by a small group. Once an extension moves towards general acceptance, then it can be moved formally into the UDD, as a specific entity and/or property.

So, in formal terms, extensions are not part of the UDD.

**Comment by robwynj** [comment]
I think we need to discuss any elements (referred to which are within the UDD) which are encrypted…….

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk/>

**Comment by arc12** [comment]
My 10p:
try to differentiate between UDD as a data specification and aspects which are formally part of the Jisc LRW

IMO the point of extensions capabilities are for off-specification activity:
- allowing for handling single institution special interests which don;t generalise
- allowing for experimental implementation while UDD version remains stable (possibly with a view to battle-tested ideas becoming part of UDD in a version-cycle)
- etc

First question: is it possible to have separate documentation of aspects which are particular to the LRW implementation of UDD? (actually, I think file names fall into this category)

If not, then I suggest the UDD repository gets a clear section which is "LRW Implementation Information", signposted as being outside the formal UDD spec. Arguably, this might be decoupled from the UDD spec version change control.

**Comment by alanepaull** [comment]
I suggest we have a new folder called LRW Implementation Information, which would contain the filename conventions file and the extension file, plus a ReadMe to explain why we've got this section.

**Comment by alanepaull** [comment]
I've moved extensions and filename_conventions to a new LRW Implementation Information folder in v1.3.1.
