### ISSUE TITLE
More GCSE information, for a reliable (UCAS) ENTRY_POINTS fallback for analytics

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#217]
Analytics studies agree that prior achievement is a crucial (early) predictor until there are significant number of records of student performance at the university. UCAS points coverage is not general enough to cover all students entering university, not all students have UCAS points from their ENTRY_QUALS. GCSEs are universal and would help bridge the gap.

### I would like to expand the UDD spec to allow more GCSE information (UDD 1.3 has Maths and English) if it is present in that University. 

- There is significant variety in the GCSEs taken so we must proceed carefully, I would like to propose an optional (but important) attribute to store **science GCSE grades** if available.
- In addition an **overall average of all GCSE grades** allowing Universities with all student GCSE grades to provide a more powerful indicator of student performance than just Maths and English GCSEs.

**Comment by arc12** [comment]
Josh - 
I suggest in the first instance that some "proof of concept" work using the UDD extensions facility would be useful, to gain evidence for questions such as:
1. is other GCSE data available in quanitity and of sufficient quality
2a. does it add anything as a predictive feature where UCAS points are also available
2b. do they add anything as a predictive feature where maths/english data is available
3. are these GCSE data points actually available when UCAS points are not?
4. is this information really useful for FE situations (address Q1 in particular for FE)
5. are the cases where UCAS points are missing for HE students also often cases where GCSE data is also systematically absent (e.g. overseas students, mature students, professional students such as healthcare)
6. is there other data which is available which might help to quantify on-entry academic ability/potential, either at HE or FE, both for cases where UCAS points are/are-not availble

Cheers, Adam

**Comment by robwynj** [comment]
I agree we should try and fit this in (for one of the HEIs we are trying to chase this information for at the moment) via the UDD 1.3.x extensions facility, in the first instance.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
I was investigating some of this in response to an email exchange with Josh a month or so back. Looking at Adam's points in succession:

1. Universities *should* have this data, because they *should* collect it at enrolment. It's available from the Learning Records Service, so should be collectable. If they're serious about analytics, universities should have it or get it, IMHO.
a. Recent research says yes. GCSEs are a very important predictor prior to A level results (or equivalent), and even when A level results are available, the combination of GCSEs and A level results is better than 1 alone.
b. Yes. Overall GCSE average is useful as an overall predictor. Maths and English are used in FE, because they're used to judge the FE Colleges (and schools) added value. There's research on that too.

2. I don't know. Most applicants will have UCAS points, as they've entered via conventional routes. However, it is likely that some of these data points will be missing, or of disputable quality. It's also the case that much of this data *should* be available to HE institutions from the Learning Records Service, so if they haven't got it, they should get it in order to enhance their analytics.

3. In my limited experience with Bedford College through looking at their Grade Tracker in Moodle, and its supporting functions, it seems immensely useful as initial measures for analytics, and as a way of assessing teaching performance (so, not just learning by students, but teaching by staff). You cannot easily measure added value without this detail, and analysing the reasons for performance is tricky without it.

4. Undoubtedly. But these are likely to be a minority, albeit important ones.

5. FE generally do their own initial assessments of incoming students for base-lining. We have some fields for this already - student_course_membership.INITIAL_ASSESSMENT_ENGLISH and INITIAL_ASSESSMENT_MATHS.

Seems like ideal candidates for extensions, then drop in the ones that prove useful. It would be good to use this type of thing as a lever to get universities to collect the easy to get data on GCSEs, if they don't already have it. I suspect that, even if our initial experience is that the data isn't readily available from participating universities, this would be a mechanism for encouraging them to get it and use it.

I have various links to research articles on this topic. It might be worth having a word with folks in UCAS' Undergraduate Advisory Group to see if they have any views on this.

**Comment by Josh-Ring-jisc** [comment]
> 1. is other GCSE data available in quanitity and of sufficient quality

This is something I think we shall find from experience.

> 2a. does it add anything as a predictive feature where UCAS points are also available

I think UCAS points are similar in predictive ability to average GCSE grades, though there is some discussion around this. It may depend on the specific course in question. It is meant to help suppliment UCAS points where they are not available.

> 2b. do they add anything as a predictive feature where maths/english data is available
are these GCSE data points actually available when UCAS points are not?

A broader sample from which to judge a student's ability is likely to better represent them. 


> is this information really useful for FE situations (address Q1 in particular for FE)
are the cases where UCAS points are missing for HE students also often cases where GCSE data is also systematically absent (e.g. overseas students, mature students, professional students such as healthcare)

Some qualifications do not award UCAS points at all, as you point out it is not perfect, but without having the data it is not possible to know if it is any better. Let's not pre-judge if domestic student data can benefit.

> is there other data which is available which might help to quantify on-entry academic ability/potential, either at HE or FE, both for cases where UCAS points are/are-not availble

**A good question and yes is the answer.** For non-traditional entry_quals we can record their grade and or percentage, so we can better understand within that entry_qual how well did they do.

**Comment by alanepaull** [comment]
Monday 4 Sep 17: We agreed that Cetis will draw up a "reasoned" proposal for handling this issue in the UDD, taking into account what might be available in student record systems.

**Comment by robwynj** [comment]
RWJ to ask LA Pathfinder institutions to find out what (any) detailed qualifications on entry information/ points they have held/ available, at their institution.

**Comment by alanepaull** [comment]
Monday 13 Nov 17: Suggestion - have a longitudinal calculated value of some sort; a distillation of prior qualifications and UCAS tariff that placed students in broadly similar statistical groupings, but didn't have to be refined to a detailed level. Alan to work on this.

Also noted that the new UCAS tariff needs to be taken into account.

**Comment by alanepaull** [comment]
See 2nd comment above: "I suggest in the first instance that some "proof of concept" work using the UDD extensions facility would be useful".

Has anyone addressed this? If so, results would be good to see. If not, can it be addressed?

**Comment by alanepaull** [comment]
Current situation as at 22 January 2018:
As far as I know, there's no proof of concept work yet using the UDD extensions facility. However, we have had useful discussions with providers on the Basecamp forum. At present the providers that responded to the issue are unable to supply much more detailed data. As a result of discussions, I posted a summary along the lines of the following:

Our current data collection on the student_course_membership entity in the UDD is as follows:

- ENTRY_QUALS - derived from HESA.QUALENT3 or ILR.priorattain, both of which encode the highest qualification on entry
- ENTRY_POINTS - the UCAS tariff or average GCSE points score
- PRIOR_GRADE_ENGLISH and PRIOR_GRADE_MATHEMATICS - encode the best relevant qualification grade in each subject.

Issues with this data:

- UCAS tariff data isn't comprehensive; some data is missing or perhaps unreliable. How much is missing or unreliable is probably dependent on provider systems, and also on whether it's derived from verified or unverified data.
- Putting UCAS tariff and average GCSE points score in the same property seems not terribly sensible now, as the meaning of the data is entirely different.
- We have a major gap, in that the above data doesn't cover much prior to level 3 qualifications, so the level 2 or below stuff is mainly missing; some GCSE English and Maths may be available, but this is small scale and patchy at best. Believing this to be relevant to learning analytics, we may wish to try to collect it, subject to cost, time and quality.

An initial approach to improvement might look like this:

1. Separate out UCAS tariff and average GCSE score into separate properties.
2. Make both of these "preferred" data items, at least for home UG students.
3. For UCAS tariff, ask providers to calculate and supply the new UCAS tariff for all home UG students (and / or provide a tool to do it).
4. For average GCSE scores, adopt an external standard, probably either Attainment 8 or ALPS.
5. Retain highest qualification on entry.

Christine Couper (Greenwich) said: "Working in an institution where we are very vigilant in coding entry qualifications, I know that we have reached the point that to gather any thing else would pass into that area where the benefit would be unlikely to justify the cost."

This type of evidence from providers suggests that we're not far off what's practical at present using our existing implementation, and that getting much more would be difficult and not viewed as cost effective. We could implement the 5 points above (4 changes, as point 5 is status quo), but we'd have to accept that average GCSE scores might not be readily available, and some providers might have difficulties with extending the new UCAS tariff calculations for all their home UG students.

On the other hand, I think that we might want to encourage providers along this path for the future. If we adjust the specification in relation to entry qualifications along these lines, without jeopardising existing data collection and functionality, then this might enable some providers to provide the data, or work towards providing it, in order to take advantage of better analytical processes in the future.

The impact of points 1, 2, 4 and 5 would be minimal, I believe. Points 1 and 5 make no new demands. Point 2 stresses the importance of supplying the data. Point 4 asks for 1 item of specific data, if available in source systems, though providers would be free to calculate it, so there could be extra work here. Point 3 is potentially bigger - the new UCAS tariff data will already be available from some, but asking all to provide it for all home UG students might be a major request.

Are there any further views on this?

**Comment by alanepaull** [comment]
Monday 22 January 2018: The original post was whether we could extend GCSE coverage beyond Maths and English. As a result of our investigations, the answer is clearly "No". In addition, asking providers to supply more detailed information about other aspects of entry qualifications is problematic, owing to extra costs and resources that providers will be extremely reluctant to commit.

However, there are some small changes that we can productively make for v1.4, following the 5 points mentioned in the previous comment.

1. Separate out UCAS tariff and average GCSE score into separate properties.
2. Make both of these "preferred" data items, at least for home UG students.
3. For the UCAS tariff, make it clear to providers that the new UCAS tariff values should be provided rather than the old, and that we strongly encourage as comprehensive coverage as possible.
4. For average GCSE scores, there is no current pressure to change the definition: "...average GCSE points score or similar numeric value where GCSEs are not relevant." This will be an optional property. It is likely to be used mostly by FE providers, and there is no difficulty in using an average GCSE score standard, such as Attainment 8 or ALPS, as long as this is consistent across the provider.
5. Retain highest qualification on entry.

**Comment by arc12** [comment]
Re: "make it clear to providers that the new UCAS tariff values should be provided rather than the old, and that we strongly encourage as comprehensive coverage as possible."

Feels somewhat problematical; I think this is a recipe for a mixed bag without clarity on which scale is being used. Its like saying you can give the weight packets of breakfast cereal in lb or kg and asking me to work out which is the best value for money!

There is probably no elegant solution here, but an unclear mixed bag will make this a useless feature for analytics. Direct cross-walk may be impractical. Maybe we could use points bands?

**Comment by alanepaull** [comment]
Well, we could spell it out. Old UCAS tariff up to but not including 2017 entry, new UCAS tariff from 2017 entry onwards. That's the official position. Happy to be explicit. Would that help?

Points bands may be a red herring I fear. I'm not sure what advantage they would have. That wouldn't help differentiate the 2 schemes; in specific areas they have a different starting point.

We're not going to get to a situation where we have consistency across historic and new data though.
