### ISSUE TITLE
Assessment_instance.ASSESS_TYPE_ID  needs to be made categorical

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#221]
To make effective use of the type of assessment (_Assessment_instance.ASSESS_TYPE_ID_) and it's potential impact on learning inside analytics or elsewhere, we need to converge to a standardised coding of this attribute into a **fixed set of categories** which can generalise across whole departments and universities.

**A starting list:**

* Coursework
* Quiz (multiple choice or filling in the blanks)
* Tutorial exercise
* Group work or discussion

**Comment by Josh-Ring-jisc** [comment]
If universities find this list is incomplete we can expand this list.

**Comment by robwynj** [comment]
Suggesting additional classification of “OTHER” – a workaround for some, but worth using to avoid unnecessary pollution of other classifications potentially….



--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by Josh-Ring-jisc** [comment]
Refer to my previous comment

**Comment by arc12** [comment]
We currently define our own set of standard assessment types and then map from ASSESS_TYPE_ID to those. The values stored in the SRS for ASSESS_TYPE_ID are rather "wild"! Part of our engagement is to agree on the mapping of the local ideosyncratic codes to our standard list. Presently we do this post-UDD, which avoids front-loading the mapping exercise into the ETL. This gives us a lot more agility/flexibility.

In general, we've found that getting agreement on a mapping from local codes is a source of delay (often LONG delays), except when the insttution already has a mapping from their local codes to HESA codes (and UDD has a defined mapping from HESA to UDD codes). Agreement requires the coordination of too many busy people on the client side.

I counsel against requiring the mapping to be in the ETL for this reason. Lets keep the agility by doing the mapping downstream ...

If you REALLY want to include a standard list in UDD, please also retain the ideosyncratic codes as used in the SRS. i.e. a similar approach as taken with PROGRESSION and PROGRESSION_SOURCE
That would also allow for the mapping to be checked with client stakeholders using a simple pivot table.

**Comment by joshring** [comment]
> "We currently define our own set of standard assessment types and then map from ASSESS_TYPE_ID to those. The values stored in the SRS for ASSESS_TYPE_ID are rather "wild"! Part of our engagement is to agree on the mapping of the local ideosyncratic codes to our standard list. Presently we do this post-UDD, which avoids front-loading the mapping exercise into the ETL. This gives us a lot more agility/flexibility."

So do you think it's worth maintaining such a lookup table in an open way so all can benefit from this? Since it is of limited value without such a mapping as you suggest.

**Comment by arc12** [comment]
@joshring - yes, at some point. I think we're not ready yet... things a bit immature, and subject to change, and would benefit from some bedding-in. I'm cautious of things un-cooked being picked up when they are really only speculation.

**Comment by Josh-Ring-jisc** [comment]
That reminds me of an approach using regex rules per-institution, but that's rather labour intensive and fragile, ideally it would need to be done in the Uni themselves.

Because of the length of time it takes, I feel the earlier we can make a start on this the better. Have it not blocking for the time being but make it throw up deprecated warnings and inform on a future deadline version for doing this would be a good approach.

**Comment by arc12** [comment]
FWIW, our internal condensed list is:
- coursework
- exam
- practical
- oral/viva

arguably, a viva and oral are exams of a type....

Rationale for a very short list is that crude distinctions are easier to map to, whereas more detailed distinctions are more at risk from being incompatible with institutional decisions.

**Comment by alanepaull** [comment]
Monday 4 Sep 17: We agreed to start working on a UDD list, but aimed at implementation for version 1.4, alongside the raw institution codes. We have the option of testing a standard list via the extension utility.

**Comment by alanepaull** [comment]
I've started to examine this issue in detail. This comment and the following one is a summary of where I am so far with this issue.

I've looked at the classification of assessment types / methods by HESA (for Unistats), QAA, HEFCE. I've had useful feedback from Tribal, and also Josh has posted a generic "starter-for-ten" above. I've also read a few commentaries from institutions on this problem, and read some papers on how it's used (or might be used) in analytics. For the moment, I'm setting aside the academic questions about whether this type of data **should** be used for LA, and its relationship to "better support for learners" on the one hand, and "institutional success goals" on the other. I think that this aspect is best left to researchers. So, I've focused on the practical data aspects, rather than the philosophical or theoretical.

It's worth noting that this is assessment_instance defined as: "any learning activity in a module, for which a student receives a grade and/or mark. The assumption is that grades and/or marks in assessment_instances are summative." So, we're avoiding anything about formative v summative, and any other way of cutting assessment types.

Institutions tend to have their own ways of defining assessment types and methods. As you'd expect, these are focused on the practicalities of delivering this aspect of learning, rather than on data collection. They define assessment types and methods for their student record systems for collecting the data for their own purposes. This means that there isn't currently a standard way of defining them, nor standard wordings. It's clear from reading institutional sources that there are very many different definitions, even for something that seems relatively simple like "written exam". For this reason, institutions can experience difficulties mapping their own internal classification schemes in the SRS (already a compromise from the descriptions used by academics) to more generic external ones.

**HESA** has a summary "assessment type" set of values for Unistats. It's very broad brush: "written examinations", "coursework", "practical". Guidance at the moment is to include a URL that points to an institutional web page about assessment, so it's not clear whether they will be collecting this in detail in the future and using it.

**QAA** is a main source of "assessment method" information for generic purposes. They stop short of any actual classification system. Instead there is an "indicative list of assessment methods", "to reflect that approaches to assessment vary according to the subject, mode of delivery and institution, and can change over time. Descriptions are intended to distinguish between methods from the perspective of presenting course level information rather than to present a detailed pedagogical account of each approach." Note: this is indicative, not definitive, and isn't designed to distinguish between methods for classification purposes. On the other hand, if we're looking for a relatively detailed set of values, it's probably the best we've got for now.

**Other central bodies**, such as **HEFCE**, don't seem to collect this type of detailed information, though I've not been completely exhaustive.

**Josh** suggested "coursework", "quiz", "tutorial exercise", "group work or discussion".

**Tribal** has an internal condensed set of values: "coursework", "exam", "practical", "oral/viva". Institutional values can usually be mapped to this set.

**Comment by alanepaull** [comment]
The initial statement of the issue was: "To make effective use of the type of assessment (Assessment_instance.ASSESS_TYPE_ID), and its potential impact on learning inside analytics or elsewhere, we need to converge to a standardised coding of this attribute into a fixed set of categories which can generalise across whole departments and universities."

On the other hand, an individual institution may be able to use its own esoteric classification to do this. However, it may be possible to provide some standardised features of the Jisc LA service, if we do use a standardised vocabulary.

If we do have a standardised vocabulary in the UDD, then we should retain the raw institutional codes for their use - as we have with similar vocabularies.

There are some practical aspects of the issue that we need to address:

1. What reliable data can we currently get from institutions? Bearing in mind that if we ask for stuff and it proves useful, then some institutions may be persuaded to collect / code more data.
2. If the data is institutionally classified and institutionally mapped, what reliable target for the mapping can we use? There are sub-issues of granularity (eg Unistats v QAA lists) and exclusivity of term definitions here. We do not want a complex or ambiguous mapping, or it will likely undermine the purpose. For simple mapping, we would need a readily understandable and probably short list.
3. How do we take into account technology enhanced assessment, and new assessment types in the future?
4. If we agree a standardised vocabulary, should it be in the UDD?

My take on these 4 aspects is:

1. We can get their raw codes, and probably have these mapped to a simple, standardised vocabulary.
2. I don't know. As the simple Unistats list is currently used by institutions, it might be a useful starting point, as institutional practice may already be mapped to this. However, we would need to address whether this broad brush categorisation is useful for LA purposes. The other candidate would the QAA indicative list. For this to be used, we would need to know that institutional data could be mapped to it; on the face of it, some adjustment would be needed, because, for example, the QAA list breaks down "coursework" into separate types, whereas an institutional list may just have "coursework".
3. To be discussed.
4. As we're unlikely to agree a definitive vocabulary, I think it may be counter-productive to include it in the UDD at the present time.

I suggest that we need to experiment using the extension facility before making changes to the UDD in relation to this issue. It might be a route forward to test the use of a **structured** list of values, drawn from the Unistats and QAA materials, akin to the guidance given in the KIS (though this is in relation to how to classify between Exam, Coursework and Practical for Unistats purposes):

written examination
     set exercises - exam [under exam conditions but not practical]

coursework [no further detail known]
     written assignment
     report
     dissertation
     portfolio
     set exercises - coursework [not under exam conditions and not practical; probably default if precise nature of the test is not known]
     project output [other than dissertation or report]

practical [no further detail known]
     oral and presentation
     practical skills
     set exercises - practical [whether or not under exam conditions]

other [specified but not covered above]
not known [unspecified]

Here, you could use any of the 15 terms with the indented ones somewhat more detailed than the rest.

Alan

**Comment by alanepaull** [comment]
The suggestion was made at our meeting on 9 Oct that we look at a simple assessment type coding scheme along the lines of:

**Timed assessment** (eg exam)
**Assessment with deadline** (eg coursework)
**Other** (something else)

I would probably add "Not known" as well.

The main question I've attempted to address initially is "can we map easily to this scheme from assessment type data held at institutions?" without reference back to academics who might have set the assessment. In other words, can we easily map from a type referenced in a SRS to the above types? It doesn't have to be perfect, but I think it might need to be more than just "exam" or "not exam". If "exam" or "not exam" is sufficient, then we should probably stop there!

I have looked at some small samples of institutional coding from Tribal. There were a significant minority of entries that were problematic, bearing in mind I've no idea how many students those codes might refer to. Possible problematic ones were:

- Group assessment [would this be simply a piece of coursework or a timed group activity?]
- Multiple choice test [timed or not?]
- Practice Based Assessment [no indication whether it was timed. If we had a "practical" code, it would not be problematic.]
- Practical [as for Practice Based Assessment]

The difficulty with the suggested approach, in my view, is that, although we might all be able to look at a detailed description of an assessment type and classify it consistently as Timed, Deadline or Other, it's very tricky to do that from just an SRS code label. The institution is coding assessment type in their SRS for their own purposes and using the intimate knowledge of their modules and assessment methods, and the suggested approach doesn't seem to match particularly well with the institutional SRS data in these instances.

I may be wrong, but it seems that Tribal already has a method of handling this issue without disturbing the UDD spec. I'm wondering whether, at this stage, we should disrupt this method by seeking a different way forward?

Before we go too much further with assessment type, I think we ought to do 2 things:

(1) Consult and discuss with pathfinder institutions
(2) Carry out some experiments using the suggested simple scheme with existing data via the extensions facility. That would give us a bit more concrete practical experience to work on.

I'm happy to help with some mapping of data if we have some more extensive institutional data available.  Both Tribal and other would be useful.

**Comment by arc12** [comment]
I think consulting academic leads is important on this one. I am fairly confident that we will find practical is important in some disciplines, "important" = academics feel the practical component is an important distinct aspect of their discipline.

In consulting, we should be clear about the uses we expect to put this information to, otherwise they will be answering their own questions to a large extent.

We use this information (condensed down to our core set) to:
a) summarise the assessment style of a module
b) categorise assessment resultsm with a thought that different types might be differently predictive of module outcome
c) to guess at assessment sequencing when due dates are missing

I'm happy to make available cross-tabulations of SOAI counts for SRS vs our condensed codes but not on this open forum. I should also add that I would prefer to have had a chance for us to cross-check these with client sites first (or for this to be wrapped into a pathfinder consultation on this github issue)

**Comment by alanepaull** [comment]
**Monday 16 October:** agreed to handle this issue via application layer extension properties and test out any revised code lists.

We will continue to use the UDD defined material "as is" for ASSESS_TYPE_ID, as we do now. Note: this is String Any value, so can be used already for code lists at institution or vendor instigation.

To test any new generic code lists, we can use the ASSESS_TYPE_ID for raw values, coupled with an extension that defines and uses a generic code list to which the raw values are mapped.

We agreed to re-visit this issue in 6 months time.

**Comment by alanepaull** [comment]
Monday 19 March 2018: agreed to stick with the extensions solution for versions 1.3 and 1.4. If there is further demand for change in the future, the issue can be re-opened.

**Comment by Josh-Ring-jisc** [comment]
## I think this issue needs to be reopened.

#### A survey across the UDD's of many sites (in no particular order) has this `ASSESS_TYPE_ID` in complete disarray (one row per site), with some universities having ~9900 unique `ASSESS_TYPE_ID` values.

![image](https://user-images.githubusercontent.com/29859996/60900840-cd853800-a264-11e9-9336-fded8ff39fd3.png)


### I propose the following to solve this issue:


Column | Description
------------ | -------------
| RAW_ASSESS_TYPE_ID | University's internal ASSESS_TYPE name |
| ASSESS_TYPE_ID | Categorical ASSESS_TYPE_ID see below

### Coding:
I have adopted Tribal's set of ASSESS_TYPE_ID categories and added a category for group work, to indicate the final mark is a reflection of several people.


| ASSESS_TYPE_ID valid values | Description
------------------------------------------|----------------------
| "assignment or coursework" | Individually submitted work. |
| "exam" | Individual work under exam conditions. |
| "practical or observation" | Lab work, performance, demonstrated competence. |
| "group work or discussion" | The mark is a reflection of a group's efforts. |
| "oral exam or viva" | Competence demonstrated orally. |
| "other" | Misc entry, which cannot fit into the above categories. |
