### ISSUE TITLE
YEAR_PRG and MOD_LEVEL  moving from optional to required field, for JISC's (and likely other) analytics

### ISSUE THREAD

**Issue by joshring** [jiscdev/analytics-udd#224]
In order to estimate student dropout risk, these details are very important:

- The year on the course `student_on_course_instance.YEAR_PRG`
- The level of the module `module.MOD_LEVEL` , eg undergraduate or access/foundation course 

As such I would move to make them mandatory fields for analytics purposes.

**Comment by robwynj** [comment]
I would recommend that they be made mandatory on the predictive modelling field guidance template, for Jisc OLAP, and we then source this template into potential UDD Validator functionality for Jisc OLAP predictive modelling checks (providing warning according to field contents/ coverage, above UDD standard conformity/ cardinality checks).

Hope this makes sense!

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by arc12** [comment]
MOD_LEVEL not essential for us.
YEAR_PRG and ACADEMIC_YEAR (MOD and COURSE-INSTANCE) are essential.
Adam

**Comment by alanepaull** [comment]
Monday 4 Sep 17: We agreed to use the "field guide templates" for products and services to cover these usually mandatory items, rather than to make them compulsory in the UDD. Properties that are mandatory for the OLAP should be stated in the version of the template for that service. Josh would be addressing this one. Craig would be creating templates for Tribal's LA analysis purposes in the next few days.

**Comment by alanepaull** [comment]
Rob and I are suggesting some changes to the field guide template, so that it can be used as part of the UDD validation processes. The main changes are:

- Replacing the 4 Categories with the much simpler cardinality of "Mandatory" or "Optional". These values make validation much simpler, and any more detailed prioritisation of the properties can be included in the Comments column.

- All UDD mandatory properties pre-set to "Mandatory" in the template. This covers all UDD primary and foreign keys.

- Suggestion to delete all properties that are not currently used by the product or service and not mandatory in the UDD. This means that the field guide becomes a complete list of those properties that are used by the product or service and / or mandatory in the UDD.

A new version of the field guide template is here: https://github.com/jiscdev/analytics-udd/tree/v1.3.2/media

Alan

**Comment by alanepaull** [comment]
Monday 16 October: we agreed that the template would be a good location for the details of any extensions that a product or service was using. To be added to the template for completion by product and service providers. Also, amend extensions.md file to describe this.
