### ISSUE TITLE
Assessment dates, more information requested

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#226]
This has been suggested before for introduction later: https://github.com/jiscdev/analytics-udd/issues/38

Would like to be able to determine if a student is submitting their assessments late, early or on time.
So a `ASSESS_SUBMISSION_DATE` would be helpful and compliment the existing `ASSESS_DUE_DATE`.

I would like to point out this is required because the `GRADE_DATE` may be drastically different to the proposed `ASSESS_SUBMISSION_DATE` due to staff member's other commitments etc.

**Comment by alanepaull** [comment]
We currently have ASSESS_DUE_DATE and GRADE_DATE, defined as follows.
ASSESS_DUE_DATE: The date an assessment instance for a student was due for submission.
GRADE_DATE: The date at which the grade result has been confirmed and awarded.

We have further data in the xAPI for assignment-submitted and assignment-graded, but these are in the context of VLE, rather than student record systems.

Assessment submission date was discussed in #38, but it looks as if it was by-passed or marked for future action, while GRADE_DATE was the main focus. It strikes me that ASSESS_SUBMISSION_DATE might be uncontroversial, as it's a direct support to the existing ASSESS_DUE_DATE for those institutions that record both in their SRS. Demand for this property was expressed in #38. I don't believe this gets in the way of any future expansion to include, for example, the date of an exam or other assessment. It seems a standalone issue - though others may wish to explain any further complications.

I propose that we consider adding the property as follows:

## ASSESS_SUBMISSION_DATE
### Description
The date an assessment or assignment was submitted by the student.

### Purpose
Analytics and display

### Derivation
Jisc

### Valid Values
Date in ISO 8601 format - YYYY-MM-DD

### Format
String in ISO 8601 Date extended format - YYYY-MM-DD

### Notes

**Comment by Josh-Ring-jisc** [comment]
Agreed, that looks good @alanepaull.

**Comment by alanepaull** [comment]
Now complete.

**Comment by Josh-Ring-jisc** [comment]
Which version was this added to? I cannot see where it was added, Michael Webb suggests we can add it to the next minor udd version, since its currently not viewable in the docs

**Comment by arc12** [comment]
its on the 1.3.2 branch
