### ISSUE TITLE
Greater clarity required in documentation, between SoAI.ASSESS_SEQ_ID and SoAI.ASSESSMENT_CURRENT_ATTEMPT

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#227]
Confusion has arisen with regards the purpose of these two STUDENTASSESSMENTINSTANCE (SoAI) entity fields. Although ASSESS_SEQ_ID is a composite primary key, for cardinality, there appears to be some crossover in description between that and ASSESSMENT_CURRENT_ATTEMPT?

Clarification required in terms of purpose for ASSESSMENT_CURRENT_ATTEMPT please.

Kind Regards

Rob

**Comment by craig-petch** [comment]
Rob, it's to help reflect where mitigating circumstances apply. If I failed the exam my second attempt would see and ASSESS_SEQ_ID of 2 and Current_attempt of 2. If there were mitigating circumstances and I was allowed to take the exam again it would be treated at may first attempt so ASSESS_SEQ_ID would be 2 but the current_attempt would be 1.  It can be used to help to see if there is any capping to the scores being applied. Admittedly we may find we want to provided more info here but we'll learn more about it now we are using it.

**Comment by alanepaull** [comment]
Maybe we could add this text to the Purpose for ASSESSMENT_CURRENT_ATTEMPT:

Purpose
Enables an institution to record the number of attempts, including the current attempt, that are officially recognised by the institution as attempts. See Notes. It differs from ASSESS_SEQ_ID, which identifies all attempts, whether actually taken or not, and regardless of mitigating circumstances.

Then we would have the following relevant descriptive text for the 2 properties:

ASSESS_SEQ_ID
**Description:** A unique sequence number to indicate the order of opportunities afforded to a student against the assessment indicated by assess_instance_id. These opportunities might be referred to as "attempts" at an assessment, but should include all opportunities, even if the attempt was not in fact made, owing to illness for example.
**Purpose:** To identify the latest assessment attempt by a student, regardless of whether or not results were achieved, especially for those being reassessed. Each assessment attempt should have a unique student_on_assessment_instance record, regardless of mitigating circumstances or results.
**Notes:** The ASSESS_SEQ_ID number should be incremented in line with the chronological order of assessment opportunities afforded to the student in respect of the specified assessment. The first attempt or assessment opportunity would have ASSESS_SEQ_ID = 1. This property relates to the number of times a student has taken, or had the opportunity to take, an assessment, not the sequence of all the assessments on a module.

ASSESSMENT_CURRENT_ATTEMPT
**Description:** Number of attempts taken by a student so far on an assessment instance, that are recognised by the institution as separate attempts.
**Purpose:** Enables an institution to record the number of attempts, including the current attempt, that are officially recognised by the institution as attempts. See Notes. It differs from ASSESS_SEQ_ID, which identifies all attempts, whether actually taken or not, and regardless of mitigating circumstances.
**Notes:** Some institutions' regulations permit attempts with mitigating circumstances to be ignored as attempts, for example where a second attempt might otherwise limit the maximum mark available. Omitting this property may hinder the development or use of an effective analytics model.

Does this clarify matters? Please suggest text amendments if not.

**Comment by arc12** [comment]
I think we are close; the essential difference is now more clear. I would be inclined to rigidly use "assessment opportunity" when referring to seq and "attempt" for attempt. Opportunity is a good word , signalling eligibility to provide work for assessment.

I might also adjust the logic of the note to:
"Some institutions' regulations penalise a student's second attempt under normal circumstances. Mitigating circumstances might allow a student to have an additional assessment opportunity without penalty; in which case ASSESS_CURRENT_ATTEMPT would remain as 1, with ASSESS_SEQ_ID differentiating the first and second opportunities."

**Comment by alanepaull** [comment]
Thanks, @arc12. 

This should be better: 

ASSESS_SEQ_ID
**Description:** A unique sequence number to indicate the order of assessment opportunities afforded to a student against the assessment indicated by assess_instance_id. These assessment opportunities might be referred to as "attempts" at an assessment, but should include all assessment opportunities, even if they were not in fact made, owing to illness for example.
**Purpose:** To identify the latest assessment opportunity afforded to a student, regardless of whether or not results were achieved, especially for those being reassessed. Each assessment opportunity should have a unique student_on_assessment_instance record, regardless of mitigating circumstances or results.
**Notes:** The ASSESS_SEQ_ID number should be incremented in line with the chronological order of assessment opportunities afforded to the student in respect of the specified assessment. The first assessment opportunity would have ASSESS_SEQ_ID = 1. This property relates to the number of times a student has taken, or had the opportunity to take, an assessment, not the sequence of all the assessments on a module.

ASSESSMENT_CURRENT_ATTEMPT
**Description:** Number of attempts taken by a student so far on an assessment instance, that are recognised by the institution as separate attempts.
**Purpose:** Enables an institution to record the number of attempts a student has made, including the current attempt, that are officially recognised by the institution as attempts at the assessment. See Notes. ASSESSMENT_CURRENT_ATTEMPT differs from ASSESS_SEQ_ID, which identifies all assessment opportunities, whether actually taken or not, and regardless of mitigating circumstances.
**Notes:** Some institutions' regulations penalise a student's second attempt under normal circumstances. Mitigating circumstances might allow a student to have an additional assessment opportunity without penalty; in which case ASSESS_CURRENT_ATTEMPT would remain as 1, with ASSESS_SEQ_ID differentiating the first and second opportunities.

**Comment by alanepaull** [comment]
master branch and v1.3.1 also updated.
