### ISSUE TITLE
student course membership - uniqueness constraints

### ISSUE THREAD

**Issue by timstratton** [jiscdev/analytics-udd#230]
One institution implementing LA is generating duplicate student_on_course_membership records. They're using the same course membership ID for different students on the same course. That's clearly invalid as it's a primary key. However, looking at the definition, should not the combination of course_ID and student_ID have a uniqueness constraint? I'm pre-empting an objection that I can see coming my way soon!

**Comment by arc12** [comment]
It is possible for a student to have more than one SCM record which refers to the same course id. This can happen when, for example the student's pathway to a qualification changes. the SCM ID is the PK; if a site is providing duplicates they need to fix that.
Imposing course + student uniqueness will prevent valid data.

The underlying issue is that the meaning of "course" is not simple in HE!
