### ISSUE TITLE
Modify ADMISSIONS_ROUTE

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#233]
We have found the concept of "True Articulation" in Scottish HE (customer request).
This is a funding council inspired situation where students who succeed at HNC can enter a degree course in year 2 and HNDs enter in year 3. Based on student records data we have seen, this is stored as a yes/no.1

This _appears_ to be consistent with the idea of an admissions route, but we suggest this should be a topic of discussion. We need to be clear that there is no conflict of semantics! (e.g. is our belief that a true articulation entrant could never have entered via UCAS clearing a correct belief?)

If this is the case:
- modify the description of ADMISSIONS_ROUTE to be more inclusive
- extend the code list to include True Articulation.

If we agree that there is no semantic issue, I suggest we revise this asap and propagate the new code list to the Jisc/LRW validation, so that we can efficiently handle this data point.

**Comment by alanepaull** [comment]
In the UCAS rules, it's explicit that a student entering a course in the UCAS scheme in Y2 or later (with credit or advanced standing, including HNC/HND) must apply through UCAS. However, this might be via a Record of Prior Acceptance rather than in the main scheme. It wouldn't be via Clearing. Of course, that's not to say that these rules are universally adhered to - it would be easy to omit the inclusion of these students.

It shouldn't be too difficult to identify the HNC/HND => degree students from SRS systems I think? These would normally be guaranteed a place if they do well enough. We might need to consider other groups? For example there are other credit arrangements for admissions after Y1. There are also institutions with Y0 admissions and auto-progression to Y1.

Perhaps this could be covered by a property that indicates the entry point in terms of Y0, Y1, Y2 and so on?

**Comment by alanepaull** [comment]
Monday 13 Nov 17: After discussion, consensus was to collect information about further similar issues with a view to extending the possibilities for values for the property. Links to similar issue in #234. May need to consider these 2 issues in the round. No action needed until we have more information.
