### ISSUE TITLE
Offer Type

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#234]
Raised by a client: could we include the kind of offer made to an applicant. The idea is intuitively simple, with examples like "unconditional offer" vs "conditional offer".

We would need to understand the kind of data stored in SRS and whether this is:
a) treated as a controlled list vs free text
b) mappable to a standard code list (if "a")
i.e. is it as simple as conditional vs unconditional, or is there more nuance?

One nuance is "contextual offer", which we've seen in Scottish HE, which I think is a conditional offer which was made taking account of the student's background (a WP tool).

**Comment by alanepaull** [comment]
"Type of offer" will depend on admissions route, I suspect. For the bulk of applications in the main UCAS scheme (not Clearing), the primary division is between Unconditional Offer and Conditional Offer.

The former means the applicant already meets all the requirements (academic and non-academic); usually because the applicant is a mature student or applying in the year or so after A levels. Conditional Offer covers all cases where there are any academic or non-academic requirements that the applicant doesn't yet meet. In most cases this will be A level grade requirements for forthcoming exams. However, there's a whole range of additional stuff that can be covered by the blanket term "Conditional Offer". If we go down this route, we'll have to be careful to include only the detail that's relevant for LA, or that's easy for providers to give us.

Contextual offer generally means a Conditional Offer that has lower requirements than the provider's normal grade requirements or points tariff for the course, usually taking into account personal adverse circumstances or WP perspectives. Providers may or may not record this type of offer in their admissions system or SRS - it's not a formal part of the UCAS scheme (I think), but may be a specific policy of a provider or a department. There's a bit on contextual admissions on the UCAS website, aimed at advisers: https://www.ucas.com/widening-participation.

These types of offer might not apply at all to mature students, part-time, online, overseas or PG students.

I think that we should consider this issue alongside the ADMISSIONS_ROUTE property in student_course_membership. ADMISSIONS_ROUTE identifies whether or not a student was accepted via Clearing, which would be an Unconditional Offer, but not the same as an Unconditional Offer in the main UCAS scheme. It may be that the specific issue here is whether an offer was unconditional or contextual, and the "standard" Conditional Offer isn't relevant.

**Comment by alanepaull** [comment]
Monday 13 Nov 17: This issue to be considered with #233 in the future. More information about this type of issue is needed to find out if there are more general situations that can be addressed by ADMISSIONS_ROUTE and by extra coded values.
