### ISSUE TITLE
New staff relationships entity

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#241]
This one concerns:

https://github.com/jiscdev/analytics-udd/issues/238
https://github.com/jiscdev/analytics-udd/issues/160

and I think some others that I need to find.

The proposal is to replace:

staffonamoduleisntanace entity
staffonacourseinstance entity
student.tutor_id field

with a new entity:

staffrelationship  (I'm not set on the name!)

This would be structured as follows (following the pattern form extensions)

STAFF_RELATIONSHIP_ID**
STAFF_ID
ENTITY
REF_NAME
REF_VALUE
RELATIONSHIP

staff on a module instance like this

| STAFF_ON_MOD_INSTANCE_ID  | STAFF_ID | MODULE_INSTANCE_ID  |
|---|---|---|
|100~MOD1|100|MOD1|

would be represented like this:

| STAFF_RELATIONSHIP_ID| STAFF_ID | ENTITY | REF_NAME  | REF_VALUE | RELATIONSHIP |
|---|---|---|---|---|---|
|1|100|MODULE_INSTANCE|MOD_INSTANCE_ID|MOD1|TEACHES|

I don't think there is any uniqueness constraint beyond the key field

so 

| STAFF_RELATIONSHIP_ID| STAFF_ID | ENTITY | REF_NAME  | REF_VALUE | RELATIONSHIP |
|---|---|---|---|---|---|
|1|100|MODULE_INSTANCE|MOD_INSTANCE_ID|MOD1|TEACHES|
|2|100|MODULE_INSTANCE|MOD_INSTANCE_ID|MOD1|MANAGES|

is valid if the person has two roles on the module

The relationship might be best as code list, but the values need to be updatable without updating the UDD API as we add more values.

Tutor would look like this, if student 9999 had tutors 101 and 102

| STAFF_RELATIONSHIP_ID| STAFF_ID | ENTITY | REF_NAME  | REF_VALUE | RELATIONSHIP |
|---|---|---|---|---|---|
|3|100|STUDENT|STUDENT_ID|9999|TUTORS|
|4|101|STUDENT|STUDENT_ID|9999|TUTORS|

**Comment by arc12** [comment]
This sounds reasonable.

Re relationship codes. I agree this needs to be flexible, but also the implication that we dont enbumber UDD spec with application-specific.

I do think we should have one reserved relationship code (and possibly reserve some more but indicate them as being NOT FOR USE for now, to keep some code-space free for future use). In particular, I think we do need a code which is a kind of universal relationship, which applications can interpret as granting all permissions. The scenario I'm concerned about is e.g. the attendance-only person is coded with a relationship code which we dont recognise.... what does that mean?

I suggest we talk through various use cases for RELATIONSHIP once we've agreed the overall stucture. I know Michael was resistant to this being tied to authorisation in the model, but that is how it will be used; we need to go beyond the declarative nature of the model and think about the system behaviour... and to document that, rather than leave it to guesswork ...

**Comment by arc12** [comment]
I both agree and disagree...

I agree that it would be inadvisable to be absolute in the coupling of relationship to  authorisation. However, I don't think it is reaslistic to be purely declarative. Doing so would place a requirement on any user-facing application which someone wanted to bring in. I'm also sceptical about the feasibility of clearly defining what each relationship means. Does a teaching assistant teach or only assist? What about postgrads who do tutorials?

Where I was trying to go with my last comment was to have a two-fold approach:
- have a code which means something like "full acces to all studnet information associated with this entity instance"
- for all other codes, the code means "no access to any student information except as allowed by application configuration which associates codes with application-specific behaviour"

**Comment by michaelwebbjisc** [comment]
On 1) lets, explore it a bit more. I can see where you are going with it, but can't quite grasp the detail. So is the idea if we the code is 'FULL_ACCESS' for example.  What does 'MICHAEL' has 'FULL_ACESS' 'MODULEINSTANCE' 'MOD1' mean.  Does it mean I can see all students wth studentmoduleinstance that match the module instance?  

I can see how that might work, but only for entities with a student id.  What about for a course, would it mean all student on a course instance making up that course?

I'm guessing that's what you mean by cleary defining it.

If I've got the right end of the stick I can see why we'd want this, but I think for 2) we'd be saying all other roles weren't saying anything thing about access to information other than as define in the application (which is slightly different to saying 'no access other than...' which implies they active block access).

**Comment by michaelwebbjisc** [comment]
Further thoughts, if I'm on the right tracks above I'm not comfortable with the concept of 'FULL_ACCESS'.  I'd replace this with a generic 'RELATES_TO'.  This would be saying that staff member x is related to object x, but is not saying anything about what the relationship is.

This would allow institutions to use this to define a relationship with anyone with anything they wanted to view, and an application to use this in its security model, if that matches the way the application(s) they wanted to use behaved.  

The more I think about it, any closer coupling of this entity and security/permissions just isn't a viable from a Jisc perspective..  The reason for this is that we (Jisc) don't have any controller over how this entity is used, but would be implying it's a security control.  If this looked like a permissions control then institution would be liable to assume that it was enforced by anything reading the data.  

This this mechanism has to stop at being a method for getting more information about a persons relationship with entities.

**Comment by arc12** [comment]
Taking a step to one side of the purpose of this entity...

We do need a mechanism for permissions control. How will that work?

My assumption is that institutions will want to know, in terms of data which leaves their sites, how that will determine who has access to sensitive data in the LA system(s) provided to their staff. At some point, they will want to see something "like a permissions control ... to assume that it was enforced by anything reading the data". How, concretely is "an application to use this in its security model, if that matches the way the application(s) they wanted to use behaved" to be realised in a way which is trusted?

**Comment by michaelwebbjisc** [comment]
The legal contract will be between the supplier and institution, and as part of due diligence the institutions will have to be happy with how the supplier intends to manage permissions within their application.

**Comment by alanepaull** [comment]
I've been looking at extracting requirements from our discussions about staff and relationships with students, modules and courses. It's obviously possible to create a new entity that lists staff and the relationships with other entities, but we're hung up on the meaning of the relationships and how they might be used. We don't want to be in a situation where we include in the spec something that enables poor practice in the use of data, particularly in the case of potentially sensitive student data. I suggest that a more traditional approach to requirements in this case might be less problematic.

It might be helpful to ask the basic question: What do we want to be able to do? Then we might get answers of the form:

                I want to be able to...

and this might enable us to focus in on the meanings of the relationships, via scenarios or use cases or examples.

Examples might be:

                I want to be able to output a report for tutors containing detailed information about the students they are tutoring.
                I want to enable a provider to configure a report on analytics data so that only staff with explicit permission can view the data.
                I want to be able to list all the staff at a provider by module and course they teach.
                I want to be able to see all student assessment results and the staff who were involved in assessment grading.

The above examples may not be realistic, and I would hope that practitioners could generate better genuine exemplars. Then we could investigate further how to express and implement the associated data requirements.

**Comment by alanepaull** [comment]
Monday 8 Jan 18: Agreed to implement as a top priority for v1.3.3 - non-breaking change. Existing relationships to be deprecated for this version, dropped for v1.4. There are no security / data protection issues for this data entity, as these issues will be handled through applications and via vendors. Description limited to "describing relationships" without prescribing usage. Alan to make proposal.

**Comment by ht2** [comment]
Would be good to decide on name if possible which will let us build out the API endpoints etc - I see you had `staffrelationship` above?

**Comment by alanepaull** [comment]
Proposed description and properties for a new staff_link entity:

# staff_link
## Description of staff_link entity
A staff_link record relates a member of staff to any other entity in the UDD. A staff_link specifies that there is a relationship between the member of staff and the concrete entity referenced by REF_ID. The type of relationship is described in the RELATIONSHIP property, but the meaning of the relationship, and any functionality associated with it, is not prescribed in the UDD. Instead these are defined by any application that uses the record. For this reason the RELATIONSHIP codes are not maintained in the UDD.

STAFF_LINK_ID [1]
Primary key. Where not supplied by data provider, the primary key will be generated by the Learning Data Hub loading mechanism. _[standard text]_

ENTITY [1]
Names the UDD entity referenced by this record.

REF_KEY [1]
Holds the unique single primary key identifying the record in the UDD entity referenced.

RELATIONSHIP [1]
Code describing the nature of the link between the staff entity and the referenced entity. [alphanumeric]
Codes can be any alphanumeric string from a vocabulary maintained via applications, not in the UDD.
The value "RELATES_TO" is a reserved code for an unspecified relationship.

Examples: 

| STAFF_LINK_ID| STAFF_ID | ENTITY | REF_KEY | RELATIONSHIP |
|---|---|---|---|---|
|1|100|STUDENT|9999|TUTORS|
|2|101|STUDENT|9999|TUTORS|
|3|100|MODULE_INSTANCE|mod_001|TEACHES|
|4|102|ASSESSMENT_INSTANCE|assess_123|MODERATES|
|5|101|COURSE|crs_011|RELATES_TO|

Staff 100 tutors Student 9999.
Staff 101 tutors Student 9999.
Staff 100 teaches on Module mod_001.
Staff 102 moderates Assessment assess_123.
Staff 101 relates in some way to Course crs_011. [For example, this might be as 1 of the design team or as course director.]

Notes

1. The design follows that of extensions.md, which also uses REF_KEY for the primary key identifier for a referenced entity.
2. REF_NAME is not necessary, because REF_KEY always refers to the entity's single primary key property; cf. extensions.md.

Initial questions: 

- name of entity? I've avoided the slightly dubious STAFF_RELATIONSHIP :).
- any more examples that might be useful?
- any more reserved codes needed?

Once we've settled these basics, I'll draft a full MD file.

**Comment by arc12** [comment]
Quick thought - 
if the meaning of the codes in RELATIONSHIP is " from a vocabulary maintained via applications", I think this means, for example that anyone using the LDH with Tribal Student Insight would create records which use our vocabulary. That way, we define those relationships which we use to control, for example, access to student-level information and either: a) work with them to relate these to SITS data when we are doing the ETL, or b) provide documentation to the site and whoever is doing the ETL.

Everyone else gets to see these but cannot expect to use these codes to control behaviour in their system.

Some implications, maybe to explore:
- a site using data-ex, studygoal, Tribal SI would be expected to provide relationships for at least two, and maybe three applications, and to understand that they have responsibility for this being right (either by doing the ETL or defining the business rules for whoever is doing the ETL)
- we should avoid codes like "MODERATES" which are not namespaced to an application in those cases where a system behaviour is to be controlled. Conversely, when behaviour such as access control is required, we need a namespace mechanism. This might be best achieved using a separate attribute, and making sure the column is indexed in the LDH, so that we can query for only those relationships which are relevant to our application.
- suppliers (including Jisc) should infer NO system behaviour control except when one of their own namespaced relationships is provided
- suppliers MAY use relationships outside their prescribed list for display or analytics, for example to augment a student list with their relationship to the logged-in staff member, or to construct a social network graph

**Comment by alanepaull** [comment]
Good points. For the avoidance of doubt, we should probably add a namespace as a **mandatory** property. Including the RELATED_TO or any other reserved code. Could we use the CONTROLLER mechanism that we have for extensions? In effect it performs the same service, I think, although technically outside the UDD. If not, then maybe a conventional IRI style namespace.

As an aside, CONTROLLER in extensions could have used an IRI style namespace if desired.

**Comment by alanepaull** [comment]
As an aid to exploring this issue further, I've drafted a staff_link entity in v1.3.3: https://github.com/jiscdev/analytics-udd/blob/v1.3.3/udd/staff_link.md

**Comment by alanepaull** [comment]
Revised staff_link entity produced here: https://github.com/jiscdev/analytics-udd/blob/v1.3.3/udd/staff_link.md.

**Comment by michaelwebbjisc** [comment]
Hi everyone,

We're moving forward with the ingestion process for this information now.  At the moment this will be held outside of the UDD.

The ingestion process isn't going to match the entity precisely, as we are going to introduce a 'scope' field.  We may decide this is a more elegant way of actually storing the data.  This is because institutions will find providing the relationship as a uri too complex.

We're going to start with the data explorer specific relationship.

For ingestion, we're going to all institutions to provide multiple staff-link files, as we think they will come from  multiple sources.

So in the udd/daily-update will process files that look like this;

stafflink-<description>.tsv

so for the Data Explorer links the file will be stafflink-datax.tsv

and for the general it will be stafflink-general.tsv

etc

The format of the file will be:

STAFF_LINK_ID [1] **
STAFF_ID [1]
ENTITY [1]
REF_KEY [1]
RELATIONSHIP [1]
SCOPE  <----- an extra field 
PROVIDED_AT [0..1]

So our initial files from the institution will look like this:

STAFF_ID, ENTITY, REF_KEY, RELATIONSHIP, SCOPE
1000, INSTITUTION, 1234,site-explorer,datax
1001, INSTITUTION, 1234,site-explorer,datax
1002, INSTITUTION, 1234,site-admin,datax

We might decide we actually want to add the scope to the entity, but if not, this would be transposed to:

STAFF_LINK_ID [1] : 1
STAFF_ID [1] : 1000
ENTITY [1]: INSTITUTION
REF_KEY [1]: 123
RELATIONSHIP [1]:https://jisc.ac.uk/datax/site-explorer
PROVIDED_AT:2018-15-02T....

This doesn't need any action from anyone, as this is information that is coming to us anyway, we're just going to change the process to start aligning with this.

We will also look at a creating a process to change the existing entities that we propose falling under this scope directly to the new format.  This will make it easier for institution to transition. So we add a process that creates entries that match student.TUTOR_ID, staff on a module instance and student on a module instance as stafflink-general.tsv.

Again, this doesn't require any action from anyone.

M.

**Comment by alanepaull** [comment]
Monday 9 April 2018: agreed to consult with Michael on Monday 16 April. Consensus at the meeting is that it may be too soon to implement the above solution for v1.3.3 and it could be implemented for v1.4 within the UDD. To be confirmed.

**Comment by alanepaull** [comment]
Monday 16 April 2018: we've agreed to wait and go ahead with v1.3.3 without staff_link.

**Comment by ht2** [comment]
Thanks @alanepaull - I will shortly "release" the 1.3.3 UDD API codebase and deploy it live today

**Comment by gmoger-jisc** [comment]
Can I flag this one for discussion next month?

We require a more dynamic way to determine the relationship between staff and institutional components.  That might be their relationship to students, courses, modules, institutional tiers and perhaps subjects.

This would also allow for students to have multiple personal tutors, where the student entity only allows for 1 tutor to be recorded currently.

The fields might be:

STAFF_LINK_ID [1] **
STAFF_ID [1]
ENTITY [1]
REF_KEY [1]
RELATIONSHIP [1]
SCOPE
PROVIDED_AT [0..1]

I am unsure at this stage how it might work for instance if we wanted a user to see all records where a COURSE.INST_TIER1 = 'Faculty of Arts' for example.  

| STAFF_LINK_ID | STAFF_ID | ENTITY         | REF_KEY                 | RELATIONSHIP | SCOPE | PROVIDED_AT         |
|---------------|----------|----------------|-------------------------|--------------|-------|---------------------|
| 123456        | GMOGER   | student        | STU12345                | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123457        | GMOGER   | courseinstance |    JISC-COURSE1-2017    | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123458        | GMOGER   | courseinstance |    JISC-COURSE2-2017    | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123459        | GMOGER   | moduleinstance |    JISC-MOD2-2017       | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123460        | GMOGER   | moduleinstance |    JISC-MOD3-2017       | TUTOR        | DATAX | 2018-07-01T16:50:06 |

I need to review with Matt Cownie how this might be implemented to ensure the spec can be used functionally.

Ultimately I see this as replacing staff on course instance and staff on module instance.

**Comment by gmoger-jisc** [comment]
I think this one has gotten a bit lost recently perhaps because of the parked status but we will need to review soon so flagging for the next monthly call.

**Comment by gmoger-jisc** [comment]
I don't think we want to have SCOPE values under UDD control as they will be specific to individual implementations.

Let's discuss the permissions aspect on the call as the conversation above does not present a clear picture to me (yes we are defining relationships but these are ultimately being used to control content views in the application layer, which are permissions, no?  Or do we define permissions as functionality?)

Would we eventually look to deprecate staff on module/course instance entities in place of this (yes is my view)?

How can we build in the capacity to define relationships based on institutional tiers (or even subject groupings)?  This is frequent request from our customers so I want to ensure we are considering it here.

**Comment by gmoger-jisc** [comment]
No need for SCOPE values in the spec as these should be implementation specific.

Lets' discuss the permissions aspect on the call as I'm unclear on the position after reading above.  Yes we are defining relationships between staff and the rest of the UDD but ultimately this is being used to control content views in the application layer.  If permissions is being defined as functionality then no, it will not be used in this way.

Are we looking to deprecate staff on course/module instance following this?  My view is yes.

We need to consider other relationships also such as those to institutional tiers or subject groups.  This is a frequent request from our users so I want us to discuss integration options with this piece to look at the feasibility.

**Comment by gmoger-jisc** [comment]
No need for SCOPE values in the spec as these should be implementation specific.

Lets' discuss the permissions aspect on the call as I'm unclear on the position after reading above.  Yes we are defining relationships between staff and the rest of the UDD but ultimately this is being used to control content views in the application layer.  If permissions is being defined as functionality then no, it will not be used in this way.

Are we looking to deprecate staff on course/module instance following this?  My view is yes.

We need to consider other relationships also such as those to institutional tiers or subject groups.  This is a frequent request from our users so I want us to discuss integration options with this piece to look at the feasibility.

**Comment by gmoger-jisc** [comment]
No need for SCOPE values in the spec as these should be implementation specific.

Lets' discuss the permissions aspect on the call as I'm unclear on the position after reading above.  Yes we are defining relationships between staff and the rest of the UDD but ultimately this is being used to control content views in the application layer.  If permissions is being defined as functionality then no, it will not be used in this way.

Are we looking to deprecate staff on course/module instance following this?  My view is yes.

We need to consider other relationships also such as those to institutional tiers or subject groups.  This is a frequent request from our users so I want us to discuss integration options with this piece to look at the feasibility.

**Comment by gmoger-jisc** [comment]
No need for SCOPE values in the spec as these should be implementation specific.

Lets' discuss the permissions aspect on the call as I'm unclear on the position after reading above.  Yes we are defining relationships between staff and the rest of the UDD but ultimately this is being used to control content views in the application layer.  If permissions is being defined as functionality then no, it will not be used in this way.

Are we looking to deprecate staff on course/module instance following this?  My view is yes.

We need to consider other relationships also such as those to institutional tiers or subject groups.  This is a frequent request from our users so I want us to discuss integration options with this piece to look at the feasibility.

**Comment by gmoger-jisc** [comment]
No need for SCOPE values in the spec as these should be implementation specific.

Lets' discuss the permissions aspect on the call as I'm unclear on the position after reading above.  Yes we are defining relationships between staff and the rest of the UDD but ultimately this is being used to control content views in the application layer.  If permissions is being defined as functionality then no, it will not be used in this way.

Are we looking to deprecate staff on course/module instance following this?  My view is yes.

We need to consider other relationships also such as those to institutional tiers or subject groups.  This is a frequent request from our users so I want us to discuss integration options with this piece to look at the feasibility.

**Comment by alanepaull** [comment]
Re 4. to clarify. I attempted a simplistic review of the complex discussion above between @arc12 and @michaelwebbjisc. I *think* that the point here was the institutions and vendors must not use this mechanism for security purposes (permissions), but simply for filtering to provide views of the data already permitted to the individual.

**Comment by arc12** [comment]
Re permissions:
I think my point was that permission info is not general-purpose.
I am sure we will need to be able to propagate information about what staff members should be from their systems, and UDD seems like the obvious place. My belief is that _in a scenario where multiple organisations are serving the institution_ we MUST use some form of namespace for the permission-tainted relationships to avoid collision of intention.

**Comment by arc12** [comment]
[something odd happened with github. the comment my Alan, which I have added an "confused" emoji to actually came before the one I added an "eyes" emoji to]

**Comment by alanepaull** [comment]
Yes, something weird happened, meaning that Gareth’s comments were also affected. Seems OK now though, so presumably a temporary glitch.
Alan

**Comment by gmoger-jisc** [comment]
| STAFF_LINK_ID | STAFF_ID | ENTITY | FIELD       | VALUE                                        | RELATIONSHIP | SCOPE | PROVIDED_AT         |
|---------------|----------|--------|-------------|----------------------------------------------|--------------|-------|---------------------|
| 123456        | GMOGER   | course | INST_TIER_1 | College   of Physical Sciences & Engineering | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123457        | GMOGER   | course | INST_TIER_1 | College   of Physical Sciences & Engineering | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123458        | GMOGER   | course | INST_TIER_2 | School   of Engineering                      | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123459        | GMOGER   | course | INST_TIER_2 | School   of Engineering                      | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123460        | GMOGER   | course | INST_TIER_3 | Department   of Mechanical Engineering       | TUTOR        | DATAX | 2018-07-01T16:50:06 |
| 123461        | GMOGER   | course | INST_TIER_3 | Department   of Civil Engineering            | TUTOR        | DATAX | 2018-07-01T16:50:06 |

Potential implementation for inst tiers

**Comment by alanepaull** [comment]
Monthly call 10 May 2019: @alanepaull to make a proposal taking into account use cases relating staff to students via Inst_tier and via subjects, as well as a generic staff_link mechanism to link staff to any UDD entity. Options that should be considered are with or without a new inst_tier entity.

**Comment by alanepaull** [comment]
Monthly call 29 May 2019: Agreed no requirement for separate InstTier entities. Agreed to draft a version of a generalised staff_link entity based on @gmoger-jisc's comment above, to cover Inst Tiers as well as primary key properties. This should give more flexibility for implementation. Note that Scope defines the precise usage of the Field and Relationship properties. To be included in v1.5.

staff_on_course_instance and staff_on_mod_instance entities, and TUTOR_STAFF_ID on student are to be deprecated in v1.5 (but removed later).

@alanepaull to draft changes.

**Comment by alanepaull** [comment]
I'm suggesting that there is a uniqueness constraint for staff_link: 

STAFF_LINK_ID [1] **
STAFF_ID [1] *
ENTITY [1] *
PROPERTY_NAME [1] *
PROPERTY_VALUE [1] *
RELATIONSHIP [1] *
SCOPE [1] *
PROVIDED_AT [0..1]

\** indicates that the property is the primary key for this entity
\* indicates that the property is part of a uniqueness constraint for this entity.

This should mean that repeated records are not permitted, which I believe is correct.

**Comment by alanepaull** [comment]
There may be this case:

STAFF_LINK_ID | STAFF_ID | ENTITY | PROPERTY_NAME | PROPERTY_VALUE | RELATIONSHIP | SCOPE 
-- | -- | -- | -- | -- | -- | -- 
3 | apaull | course | INST_TIER_3 | Department of History | tutors | DATAX 
4 | apaull | course | INST_TIER_1 | Faculty of Arts and Humanities | tutors | DATAX 

If we have INST_TIER_1 = Faculty of Arts and Humanities, INST_TIER_2 = School of History and Philosophy, and INST_TIER_3 = Department of History, then...

Record 4 may make Record 3 redundant; or are both (and the relation to INST_TIER_2) required? This may be covered in the current implementation, and that logic may apply, but I thought it worth raising.

**Comment by alanepaull** [comment]
An example of staff_link eliminating staff_on_course_instance, staff_on_module_instance and tutor_staff_id. This also shows a course_subject link, effectively filtering on V160 (ancient history).

STAFF_LINK_ID | STAFF_ID | ENTITY | PROPERTY_NAME | PROPERTY_VALUE | RELATIONSHIP | SCOPE
-- | -- | -- | -- | -- | -- | --
1 | apaull | course_instance | COURSE_INSTANCE_ID | ci01_1 | relates_to | jisc
2 | apaull | mod_instance | MOD_INSTANCE_ID | mi01_1 | relates_to | jisc
3 | apaull | course | INST_TIER_3 | Department of History | tutors | DATAX
4 | apaull | course | INST_TIER_1 | Faculty of Arts and Humanities | tutors | DATAX
5 | apaull | student | STUDENT_ID | bsmith | tutors | DATAX
6 | gmoger | student | STUDENT_ID | bsmith | tutors | DATAX
7 | apaull | course_subject | SUBJECT_ID | V160 | relates_to | jisc

**Comment by arc12** [comment]
Two short comments:
1. re possible redundancy of records 3 and 4
I think this is a per-site, relationship, and entity-specific question, within the given scope.
i.e. given how the implementation of a scope is, and the required behaviour, what data should be created. Otherwise there are far too many unknowns. What I'm saying is that the structure is just a way of making statements, a simple grammar, rather than working out what they mean. For example, relationships with semantics of belonging vs control are likely to look at the hierarchy either bottom-up or top-down.

2. I think ENTITY is redundant and potentially a source of confusion
Since the property names are unique across entities, we know that STUDENT_ID identifies a student, for example. So gain nothing by asserting entity=student
Potential source of confusion is that including ENTITY permits ambiguous statements such as ENTITY=student-course-instance + PROPERTY_NAME=course instance id. What does that mean?
I suppose, though, following my comment #1 that the answer to "what does that mean" is not in scope for us :-) Still, it invites a level of complexity which I think software developers would not appreciate.

Adam

**Comment by alanepaull** [comment]
1. I completely agree.
2. What you're saying here I think is that the statement is about the member of staff and a PROPERTY from somewhere, rather than an necessarily a specific entity. That works for filtering, for example, where a module_instance_id can be used across module_instance and student_on_module_instance. Some PROPERTY_NAMES, typically foreign keys are repeated across entities. Does this matter? As the staff_link records are statements about a relationship of a specific member of staff, rather than a categorical entity-relation, I suspect it doesn't.

This feels to me very much like an implementation issue. It would be useful to get @gmoger-jisc's view.

**Comment by alanepaull** [comment]
Bits related to staff_link have been deprecated in v1.5_development.

**Comment by gmoger-jisc** [comment]
Agree on point 1 and 2.  Entity feels redundant and wouldn't make much difference to us whether it was included or not.
