### ISSUE TITLE
Trailing modules.

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#243]
We've had this one from Uni:

'a hugely significant element of a ‘non-clean’ progression would be trailing modules “FAIL_CON” (fail but continuing) – this will lead to issues for the student to manage if they need to repeat and is of great interest to the tutors looking at the dashboard – how can we flag the module(s) which is/are being carried, and how can this be clearly labelled?

I think this needs a new entry on studentmoduleinstance, as I think this is different to:

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_a_module_instance.md#mod_retake

Views?

**Comment by alanepaull** [comment]
Would it be sufficient to add this as a new value to MOD_RESULT?
We have 1 Pass, 2 Fail, 3 Not known. Could add in "Fail but continuing" as 4. It has the weakness of potential overlap with 2. Re-defining "Fail" though seems to over-complicate things. However: 2 "Fail not re-taking" versus 4 "Fail but continuing" might work.
There may be practical reasons for having a separate flag, but if not, it's possibly better to extend an existing property than to add a new one.
Alan

**Comment by arc12** [comment]
I think I recognise "FAIL_CON" as our internally mapped code for PROGRESSION_SOURCE (at student-cours-instance level).

We can cover the scenario of reassessment, without a full repeat, using current/completed attempts. I understand this issue is about a full repeat. In which case, what is it about MOD_RETAKE which makes it unsuitable?

Alternatively, if the issue IS about students with re-assessment opportunities, I see two options:
- use current/completed attempts (customer may not be aware of these)
- extend MOD_RESULT to include an under-reassessment flag (not quite the same semantics as Alan's code 4, but similar). This would technically be a breaking change, because it would modify data previously coded as 2.

**Comment by craig-petch** [comment]
In addition to the above points which handles capturing what happened and that the student's outcome on the given module instance was a "Fail but continuing" outcome or whatever.  But is the use case here also about being able to identify that the module instance the student is currently undertaking a "trailing module". Which is likely to be a new module instance for the following year. This could be derived by looking at a variety of historic items but isn't a nice and clear way of doing so. A flag to capture this would be useful. you could neatly identify that on the module instance you are looking at there are x students who are trailing. Given that this can be a little messy in to identify in the SRS it would make sense for institutions to be able to wrap that logic up into a single flag so the end user of data could easily pick this info up.

**Comment by michaelwebbjisc** [comment]
Yes, Craig has summarised nicely.

**Comment by alanepaull** [comment]
Monday 27 Nov: we agreed that "trailing modules" covers the circumstance of students who have failed a module, and are taking it again in the following academic year in addition to their normal modules. This is different from a re-take or re-sit (covered by MOD_RETAKE), because these usually happen in the same academic year.

**PROPOSAL:** This is best represented by a new flag as follows:

## MOD_TRAILING
### Description
Whether the student failed the module and is taking it again in the following academic year in addition to other modules, while continuing on the course.
### Purpose
Analytics
### Derivation
Jisc
### Valid Values
<table>
<tr><td>MOD_TRAILING</td><td>DESCRIPTION(ENGLISH)</td><td>DESCRIPTION(WELSH)  </td></tr>
<tr><td>1</td><td>Yes</td><td>Ie</td></tr>
<tr><td>2</td><td>No</td><td>Na</td></tr>
</table>  

### Format
String (255)

### Notes
For a retake in the same academic year, use MOD_RETAKE, not this property.

**Comment by arc12** [comment]
possible ambiguity in "these":
"This is different from a re-take or re-sit (covered by MOD_RETAKE), because these usually happen in the same academic year."

How about 
"MOD_TRAILING is different from MOD_RETAKE; a re-take or re-sit (indicated by MOD_RETAKE) may happen in the same academic year."

I think we need to clarify whether MOD_TRAILING == "Yes" necessarily means that MOD_RETAKE == "Yes". I think that would be cleanest, otherwise we'll end up needing to alter the MOD_RETAKE definition to be clear it is in-year only (and it may be that this is harder to work out from SRS data than just "its being retaken").

**Comment by alanepaull** [comment]
Point taken. 

How definite can we be about the difference between MOD_RETAKE and MOD_TRAILING in practice? If MOD_TRAILING is always a sub-set of MOD_RETAKE, then your revised wording nearly works, and we can specify "If MOD_TRAILING=="1", then MOD_RETAKE=="1". I would favour that, because, as you say, it is clean.

Then we'd have:
"MOD_TRAILING is a sub-set of MOD_RETAKE; if MOD_TRAILING is set to "1", then MOD_RETAKE must also be set to "1". A re-take or re-sit (indicated by MOD_RETAKE) may happen in the same academic year as the original module instance. MOD_TRAILING only happens when the student takes the trailing module alongside continuing modules in the next academic year.

I really don't want to have to separate out these 2 properties entirely, because folks will find it hard to get it right - it's a bit esoteric.

**Comment by alanepaull** [comment]
Checked and closed.
