### ISSUE TITLE
Unmoderated module and assessment marks

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#244]
Moderation is valuable internally for an institution.

For model building purposes I think it would be beneficial to have the unmoderated marks so we can gain access to student performance earlier in the year (before the committees have met which is often infrequently). 

It also means we can choose to build a model with either moderated or unmoderated marks, whichever gives more accurate predictions, which is good for all concerned.

**Comment by arc12** [comment]
Josh - these are the ACTUAL values, whereas AGREED are the board-approved marks

**Comment by Josh-Ring-jisc** [comment]
No, Not quite.
> The mark awarded to the learner **after any moderation process**, but before any formal confirmation process. Moderation processes typically involve multiple markers, and confirmation processes typically involve external examiners.
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_a_module_instance.md#mod_actual_mark

**Comment by alanepaull** [comment]
I believe Josh is correct, strictly according to our definitions. For clarity, student_on_assessment_instance has:

ASSESS_ACTUAL_MARK - "The mark, expressed as a percentage, awarded to the learner after any moderation process, but before any formal confirmation process."

ASSESS_AGREED_MARK - "The mark, expressed as a percentage, recorded after any moderation or confirmation processes, or the only recorded mark if there are no moderation or confirmation processes."

ASSESS_RAW_ACTUAL_MARK - "The original mark scored by the student." However, from Notes: "ASSESS_ACTUAL_MARK contains a representation of ASSESS_RAW_ACTUAL_MARK explicitly as a percentage."

It's the same for module marks. So, according to our definitions, we don't have the unmoderated value.

I think that ASSESS_RAW_ACTUAL_MARK is intended to be the original raw unmoderated figure, so the Note against ASSESS_ACTUAL_MARK is incorrect. If any of these are derived values (the % ones for example), then we need to clarify and amend the documentation.

Alan

**Comment by Josh-Ring-jisc** [comment]
The problem with RAW values is they are not percentages, so are less reliable since they are relying on max marks being not missing. A percentage attribute which is un-normalised would be more valuable.

**Comment by alanepaull** [comment]
If practice is different from the documented definitions and notes, then...

**Proposal**: make it so that ASSESS_RAW_ACTUAL_MARK and ASSESS_ACTUAL_MARK are really defined as the unmoderated figures.

**Comment by Josh-Ring-jisc** [comment]
Percentages please.

**Comment by alanepaull** [comment]
ASSESS_RAW_ACTUAL_MARK = not necessarily %.
ASSESS_ACTUAL_MARK = %.

The important point here is that ASSESS_ACTUAL_MARK currently says (1) it's after moderation and (2) it's also ASSESS_RAW_ACTUAL_MARK expressed as a %. These may be mutually incompatible statements. What we want, I think, is for both properties to be BEFORE moderation. Does @arc12 have a view on this?

**Comment by Josh-Ring-jisc** [comment]
@alanepaull Ah OK I think I get you, yes that makes a lot of sense.

**Comment by arc12** [comment]
I suspect there is some wording oddity.

We also need to be very wary about marking practices and how realistic it is to properly model real practice.

RAW were introduced explicitly to cope with non-percentage scenarios. IMO the actual/agreed should perfectly mirror the non-raw case.

AGREED should be the final recorded mark which is used to determine progression or award. This will be agreed by a formal process, but the process may also AFAIK adjust marks. Hence the reality is likely to be that "moderation" in some form occurs at the same time as confirmation.

ACTUAL should reflect a provisional "what the student got". I would expect this to be what goes to Board. There may or may not have been some moderation process already, for example double-marking. I *think* that was the intention of the word "moderation" in the spec. Furthermore, I would expect that this is what gets recorded in the SRS (if at all), and I doubt that we'll easily find marks from earlier stages other than in spreadsheets (or be able to model the variety of practice while retaining usability).

**Comment by craig-petch** [comment]
For info, for SITS sites. The Assessment Actual mark will be BEFORE moderation. The state of this could be down to timings and how those marks get entered into the system.  But they will be in there prior to exam boards.  Agreed is the mark POST exam board. Although you may see more changes here at the module rather than the assessment level. It's won't see a raw mark from SITS unless there's some hybrid with the VLE been arranged.

**Comment by alanepaull** [comment]
As a result of discussions Monday 27 November, I propose to update the documentation on the v1.3.3 dev branch to make it clear that ACTUAL is the mark first entered in the SRS (usually before moderation and exam board), while AGREED is post exam board. This applies to the similar properties on both student_on_a_module_instance and student_on_assessment_instance entities.

MOD_ACTUAL_MARK definition was: "The mark awarded to the learner after any moderation process, but before any formal confirmation process. Moderation processes typically involve multiple markers, and confirmation processes typically involve external examiners."

**Proposed change to:** "The mark awarded to the learner as first recorded in the SRS, usually but not always, prior to formal moderation and exam board confirmation. The value of MOD_ACTUAL MARK is expressed as a percentage; for example, a value of "63.75" means 63.75%, a value of "50" means 50%."
Notes: "MOD_ACTUAL_MARK should only be part of a UDD compliant dataset if there is a moderation process and if the result of that process is available in the source data."

MOD_RAW_ACTUAL_MARK definition stays as it is: "The original mark scored by the student."
With Notes "Can contain any decimal value, for example "59", "162.87", and so on; this value may or may not be a percentage. MOD_ACTUAL_MARK contains a representation of MOD_RAW_ACTUAL_MARK explicitly as a percentage."
Purpose: "Storage of the original numerical score." The words ", typically from the VLE" have been deleted, as they may not in practice be correct, because the data comes usually from the SRS.

MOD_AGREED_MARK definition stays as it is: "The mark recorded after any moderation or confirmation processes, or the only recorded mark if there are no moderation or confirmation processes. This mark is typically the one used to determine degree classification."

Please refer to the MD files for all the definitions, including a similar change to MOD_ACTUAL_GRADE.
