### ISSUE TITLE
Full versioned history of the UDD, to make representative training easier

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#251]
I would be useful to have a versioned history of the UDD, so we can look back in time and get a representative view of what was known at a given time, so we can perform training of models based on what was known at that period of time more easily.

**Comment by alanepaull** [comment]
Do you mean that you would like to be able to look at previous versions of the UDD? If so, that's possible via the tagged versions back to v1.2.3. You can find these at the "Tag" tab of the Branches button. Alternatively, there are the code releases, again back to v1.2.3: https://github.com/jiscdev/analytics-udd/releases. These have summaries of changes (release notes) since the previous version.

**Comment by Josh-Ring-jisc** [comment]
More on the data-side actually. So we can dial back the clock to the same point in the year for different datasets.

**Comment by alanepaull** [comment]
I think that's an implementation issue? Not to do with the UDD specification? This repository is about the UDD spec, rather than the actual data content stored in the Learning Data Hub. Unless I have the wrong end of the stick :).

**Comment by michaelwebbjisc** [comment]
Not a UDD spec issue, but interested if this is useful for anyone else.

**Comment by alanepaull** [comment]
Monday 8 Jan 18: clarified as implementation issue and noted.
