### ISSUE TITLE
WITHDRAWAL_REASON default value is a missing value

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#252]
It would make sense to have a **coded value** for WITHDRAWAL_REASON representing the most common case in live data, "Student has not withdrawn", in this way we can distinguish it from data which is missing more easily.

**Comment by alanepaull** [comment]
Monday 8 Jan 18: Agreed, for v1.4.

**Comment by arc12** [comment]
Is this not functionally overlapping ACTIVE_MEMBERSHIP?
It also messes with the semantics of withdrawal-reason.

I dont like two places for the same information. Suggest we re-open this issue to clear this up.

**Comment by Josh-Ring-jisc** [comment]
How do you suggest to distinguish missing data from the normal case where they have not withdrawn then?

**Comment by alanepaull** [comment]
@arc12 is correct that it messes with the semantics of WITHDRAWAL_REASON. Our codes for this are derived from HESA and FEILR, and adding in a WITHDRAWAL_REASON code that doesn't state a reason for withdrawal is against the definition of the property.

The reason for this semantic difficulty is that HESA (I haven't checked FEILR) has a specific additional property for completion status (CSTAT), which indicates withdrawal. In addition, HESA has a property for why a student has ended an instance (RSNEND), which is wider than withdrawal. We have implemented these HESA properties through WITHDRAWAL_REASON and COURSE_OUTCOME. We also have ACTIVE_MEMBERSHIP, which focuses on the positive "the student is on the course" rather than a more descriptive status like CSTAT.

To answer Josh's point that he posted while I was drafting this - "How do you suggest to distinguish missing data from the normal case where they have not withdrawn". ACTIVE_MEMBERSHIP = 1 shows the student hasn't withdrawn or otherwise stopped being on the course. So, if data in WITHDRAWAL_REASON is missing and ACTIVE_MEMBERSHIP = 1, then the student has not withdrawn.

To get the full picture, you need to look at ACTIVE_MEMBERSHIP for overall "status", and both WITHDRAWAL_REASON and COURSE_OUTCOME for more details.

**Comment by alanepaull** [comment]
For discussion at the next fortnightly meeting? I suspect that "no change" should be under consideration.

**Comment by arc12** [comment]
@Josh-Ring-jisc - as Alan said.
A big issue I have with coding schemes as you suggest is that people doing ETL just default the code wjem they dont find an explicit withdrawal reason, and so you never get to see any missing values in the data anyway. ACTIVE_MEMBERSHIP drives the ETL logic from a different direction which will actually make it easier to determine whether a student is no longer on the course but the reason (completion or withdrawal) is missing. In practice, I have found that some missing reasons may be spotted when there is an end date but no course outcome.

**Comment by Josh-Ring-jisc** [comment]
>  people doing ETL just default the code wjem they dont find an explicit withdrawal reason

Often they set everyone to have withdrawn in the first week of term, because there is no sensible value to assign :/ Or they have a null

**Comment by alanepaull** [comment]
Maybe we need to add specific notes to WITHDRAWAL_REASON:

### Description
The reason a student has withdrawn from a course (if they have). If the student has not withdrawn, omit this property.

### Notes
This property should be used only if a student has withdrawn from a course. If the student has not withdrawn, omit this property; do not supply with a null or blank value.
This property should also be set when a student changes course, so that historical records can be maintained and analysed later; in addition the COURSE_END_DATE should be set accordingly.

**Comment by arc12** [comment]
re "do not supply with a null or blank value."
When data is supplied as CSV/TSV, I think that is precisely what should be done when a student has not withdrawn.

**Comment by robwynj** [comment]
I agree

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Lead – UK Data & Analytics Services; Senior Data & Analytics Integrator
email: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> skype: robwynj twitter: @robwynjones
mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Yes, with CSV/TSV - I shall have to make that clear somehow.

**Comment by Josh-Ring-jisc** [comment]
There are cases where "ACTIVE_MEMBERSHIP" is entirely missing from a given Uni, so these solutions fall down.
>  In practice, I have found that some missing reasons may be spotted when there is an end date but no course outcome.
This is relying on additional attributes which are equally likely to be missing

If we have an attribute presence it shouldn't need multiple (2-3) other attributes to make sense.

**Comment by alanepaull** [comment]
Monday 19 Feb 2018: we decided to leave WITHDRAWAL_REASON as it is now. However, ACTIVE_MEMBERSHIP should be mandatory, which would resolve the issue. Change for v1.4

Now done.
