### ISSUE TITLE
YEAR_STU and YEAR_PRG integer type

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#256]
Strings are harder to standardise than integer, it's very possible in future a uni will submit a combination of:
"year1", "year_1", "year__1", "year   1", ... and whatever else you can imagine! 
Unless we standardise this. This makes it more possible to return to them meaningful error messages when they go to validate their data, and makes the data much cleaner.

It makes sense to allow values [1, 2, 3, 4, ..., 25 ]
Right now we receive values for each attribute which start at different points some from zero some from one, inconsistently.

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#year_prg
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#year_stu

**Comment by arc12** [comment]
Those two used to be integer type and TBH I hadnt noticed they were no longer. We actually assume they are integers and do arithmetic!

Also see use of 0 for YEAR_PRG, which appears to be things like foundation years, so that UG normal first year gets YEAR_PRG == 1 irrespective of the entry-point of the student. In that sense, the 0 is consistently applied and meaningful.

So:
+1 for making these integers
I feel that forcing people to not use 0 will cause problems because we'd obscure meaningful differences. i.e. allow 0

**Comment by Josh-Ring-jisc** [comment]
What does zero mean here? Honestly thing it's a mistake as I can see:
0-6 is the range of one variable and 1-7 is the range of the other, where the ranges would be expected to be the same.

So unless zero means anything vote to exclude it.

**Comment by arc12** [comment]
YEAR_PRG
A typical English UG course has three programme years: 1, 2, 3
Some courses allow for entry in a foundation year which allows the students to progress to the normal "year 1". I have seen this consistently indicated as YEAR_PRG == 0. It is not an error. It means something.

YEAR_STU
Counts from student enrolment as YEAR_STU == 1 and advances for each year.
A student in a foundation year would have YEAR_PRG == 0 and YEAR_STU == 1
A student who enters via a foundation year and progresses cleanly through the whole course will end with YEAR_PRG == 3 and YEAR_STU == 4.

**Comment by alanepaull** [comment]
I propose the following (changes indicated in bold italics, plus a new table in YEAR_STU):

## YEAR_PRG
...

### Valid Values
**_0-25_**

### Format
**_Int_**

### Notes
**_"0" indicates a foundation year or other bridging year aimed at students who are not quite ready to enter the first year of the course. See Notes in YEAR_STU._** 
Omitting this property may hinder the development or use of an effective analytics model.

## YEAR_STU
### Description
**_A count of the number of years that the student has been on the course since enrolling. This could be different from the year of the course if the student has changed course or retaken a year or was on a foundation year._**
...

### Valid Values
**_1-25_**

### Format
**_Int_**

### Notes
Omitting this property may hinder the development or use of an effective analytics model.
**_Summary of relationship between YEAR_STU and YEAR_PRG:_**
<table>
  <tr>
    <td>Year</td><td>YEAR_STU</td><td>YEAR_PRG</td>
  </tr>
  <tr>
    <td>Foundation year</td><td>1</td><td>0</td>
  </tr>
  <tr>
    <td>First Year</td><td>2</td><td>1</td>
  </tr>
  <tr>
    <td>Second Year</td><td>3</td><td>2</td>
  </tr>
    <tr>
    <td>Re-take of Second Year</td><td>4</td><td>2</td>
  </tr><tr>
    <td>Third Year</td><td>5</td><td>3</td>
  </tr>
</table>

**Comment by arc12** [comment]
I would explicitly say that last table is an example.
