### ISSUE TITLE
Clarifying MISSING BY DEFAULT for CURRENT students, who HAVE NOT yet dropped out or finished

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#270]
# **Unis frequently confused by undocumented by-default missing value semantics of:** 
## WITHDRAWAL_REASON 
**Frequently find WITHDRAWAL_REASON equal to either of the below when they do not know if the student will dropout in future, IE they are still studying,** Obviously this is incorrect and makes the students appear to have left so I feel we need to clarify that this attribute should be left blank when the student is still studying

- 97   Other 
- 98   Reason not known 
- 99   Completion of course - result unknown

## COURSE_OUTCOME
**Frequently find COURSE_OUTCOME equal to either of the below when they do not know if the student will dropout in future, IE they are still studying,** Obviously this is incorrect and makes the students appear to have left so I feel we need to clarify that this attribute should be left blank when the student is still studying

- 11   Other
- 98	 Completion of course - result unknown
- 99	 Unknown

## COURSE_END_DATE
**Frequently find COURSE_END_DATE equal to a date like the COURSE_EXPECTED_END_DATE, but they are still studying,** 
Instead it should be a missing value

**references:**
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#withdrawal_reason

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#course_outcome

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#course_end_date

### Updated to add COURSE_END_DATE

**Comment by arc12** [comment]
+1

**Comment by willblenkhorn** [comment]
+1

**Comment by alanepaull** [comment]
WITHDRAWAL_REASON - I agree; see below.

COURSE_OUTCOME: Definition is: "This field indicates the outcome/ status of the learner's current course or learning aim. " In contrast, HESA RSNEND: "This field is used to indicate for what reason the student left the student instance detailed in this return."

For COURSE_OUTCOME, my understanding is that a student who is continuing should be classified "13" ("The learner is continuing or intending to continue the learning activities leading to the learning aim"). Possible confusion here is that this property is NOT the same as HESA RSNEND, but is extended from that, partially to cover FE. I think that situations where this property is not used should be rare, but we perhaps need to discuss this more.

COURSE_END_DATE: can be clarified in the Notes that this only applies to courses that have ended.

# **Proposals: Update Notes as follows.**

## WITHDRAWAL_REASON
### Notes
If the student has not withdrawn, this property should be omitted (leave blank in TSV).
This property should also be set when a student changes course, so that historical records can be maintained and analysed later; in addition the COURSE_END_DATE should be set accordingly.
**_[only change in the second sentence is addition of "...also..."]_**

## COURSE_OUTCOME
### Notes
If the student is continuing or intending to continue studies on this course, use the code "13". Unless there is an explicit statement to the contrary "intending to continue studies" is implied and code "13" should be used.
Omitting this property may hinder the development or use of an effective analytics model.
**_[Is 2nd sentence useful?]_**


## COURSE_END_DATE
### Notes
If the course has not ended, this property should be omitted (leave blank in TSV).
Note that there may be many reasons why a student leaves a course. This is recorded in WITHDRAWAL_REASON.
**_[Second sentence unchanged.]_**

**Comment by robwynj** [comment]
+1

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk/>

**Comment by Josh-Ring-jisc** [comment]
- In these attributes we need *strong* emphasis the default values for certain circumstances, they must not be hidden in a wall of text.

- It is not an exaggeration to say I have not seen a university yet, which has not been confused by this. Clarity is critical.




## WITHDRAWAL_REASON
### Notes
###### Default value for non-withdrawn, currently active students: omitted (blank in TSV)
This property should also be set when a student changes course, so that historical records can be maintained and analysed later; in addition the COURSE_END_DATE should be set accordingly.


## COURSE_OUTCOME
### Notes
###### Default value for non-withdrawn, currently active students: "13"
Unless there is an explicit statement to the contrary "intending to continue studies" is implied and code "13" should be used.
Omitting this property may hinder the development or use of an effective analytics model.


## COURSE_END_DATE
### Notes
###### Default value on-going courses: omitted (leave blank in TSV).
If the course has not ended, this property should be omitted (leave blank in TSV).
Note that there may be many reasons why a student leaves a course, these reasons are recorded in WITHDRAWAL_REASON.

**Comment by alanepaull** [comment]
Monday 21 May 2018: Agreed to align with HESA codes for COURSE_OUTCOME. This means that continuing students have this property omitted; codes 13 and 14 are dropped.

**Comment by Josh-Ring-jisc** [comment]
@alanepaull we would really benefit from the emphasis suggested in my earlier comment

eg:

### WITHDRAWAL_REASON
## Notes
##### Active students: omit the property (leave blank in TSV).
This property should also be set when a student changes course, so that historical records can be maintained and analysed later; in addition the COURSE_END_DATE should be set accordingly.

**Comment by alanepaull** [comment]
Josh: I've edited above to make it bold.
Alan

**Comment by arc12** [comment]
a cardinal sin it is to use structural markup (such as a heading) to achieve a formatting effect rather than to define structure (with the semantics of the element). Markdown should be structural!

If you want emphasis, try something like :star: (type a colon then "star" then another colon)

**Comment by Josh-Ring-jisc** [comment]
Ok then, new line and bold. 
Not fussed about the star, I just want the Unis to see it! :)

**Comment by alanepaull** [comment]
True, Adam, but that boat sailed long ago in practice for many text files. Just look at HTML.

I’d be happy to go with bold and a new line, if I can force that.

--
Alan Paull
alan@alanpaull.co.uk<mailto:alan@alanpaull.co.uk>

On 22 May 2018, at 17:37, Adam Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:


a cardinal sin it is to use structural markup (such as a heading) to achieve a formatting effect rather than to define structure (with the semantics of the element). Markdown should be structural!

If you want emphasis, try something like ⭐️ (type a colon then "star" then another colon)

**Comment by alanepaull** [comment]
I would be happy if users would read the words :).

--
Alan Paull
alan@alanpaull.co.uk<mailto:alan@alanpaull.co.uk>

On 22 May 2018, at 17:39, Josh-Ring-jisc <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok then, new line and bold.
Not fussed about the star, I just want the Unis to see it! :)

**Comment by Josh-Ring-jisc** [comment]
Let's not get ahead of ourselves
