### ISSUE TITLE
Cardinality constraints need sorting

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#29]
At the moment, attributes on more than one entity are linked rather than duplicated. Which is fine, but it means that the cardinality constraint in the definitions of those attributes may not be correct for some entities. 
Moreover, I suspect that those constraints need checking anyway, because I'm not sure they're entirely consistent, and also because some might need to allow for more than 1 instance?

**Comment by arc12** [comment]
Wilbert - 
I can't decode: "attributes on more than one entity are linked rather than duplicated". Could you expand please...
Do you mean cases such as location?

As to cardinality, are you referring to sections such as
"Compulsory
Yes (if applicable)"
[this wording comes across to me as being ambivalent, and as a general principle, I think we need to be restrained about making anything compulsory if UDD is to be flexible for different institutional processes and data management practices, not least to include FE provision. My current view (it may change, according to the wisdom of others) is that RFC2119* required/recommended/optional captures three levels of obligation (and the adjectives to apply to the specification) which are applicable to UDD, with "should" allowing for wiggle in the case where data is not available and "may" giving latitude of choice.]

A related point: it might be worth being explicit in UDD about the primary key for each entity, and whether this is simple or compound. This is implicit in the use of "unique" in some cases.

Cheers, Adam

* - for non-standards wonks... https://www.ietf.org/rfc/rfc2119.txt

**Comment by robwynj** [comment]
That's fine Wilbert, best way for me
