### ISSUE TITLE
ACTIVE_MEMBERSHIP potentially misleading documentation in 1.4

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#296]
We used to have code 3 for not known and optional.
In 1.4 there is no code 3 and it is mandatory.

This is fine, so long as data providers know that the values in ACTIVE_MEMBERSHIP **will be used in business rules** which control which students are shown as individuals, used in aggregations etc.

So:
A) I think this needs to be emphasised, both in the top-level entity notes and against the attribute
B) the statement "Where it is not known whether or not the student is active, "not active" should be supplied." seems to be rather tempting data providers to simply set the value to "not active" rather than writing proper ETL code. Really, I think it is up to the data provider to decide whether they want a student to be processed as active or not in the cases when their data is indeterminate.

It must be trustworthy if we are to use it... which was why we put it in!

And given the amount of time it takes to iterate a data extract, we should avoid the need to iterate, especially as everything would pass basic validation and only appear as an issue on inspection.

**Comment by alanepaull** [comment]
Reviewing this issue after a few months have passed...

It seems that there is a an importance nuance of emphasis to be conveyed here. I suggest the following documentation change:

In the Notes under ACTIVE_MEMBERSHIP, delete the final sentence: "Where it is not known whether or not the student is active, "not active" should be supplied." and replace it with:

"The ACTIVE_MEMBERSHIP property is used to determine which students' data will be included in business rules relevant to all those actively engaged on the course ; therefore, institutions can exclude students from inclusion in apps, aggregations and most analytics services by setting this property to "2" Not Active. Institutions should review carefully cases where data appears to suggest that active_membership status is unknown, so that students are not unnecessarily omitted."

This text can also be included as part of the entity notes at the top of the markdown file.

**Comment by arc12** [comment]
Alan - I think that is better. I think there is a sliver of scope for further clarification, to attempt to avoid an inference that ACTIVE_MEMBERSHIP is a mechanism to control whether or not a student's data is processed. ACTIVE_MEMBERSHIP indicates students who are ACTIVE, i,e "current", "on programme" etc. A setting of "2" would not wholly exclude the student; they would only appear in HISTORICAL aggregations and be used for training/reference data for learning analytics services.
ACTIVE_MEMBERSHIP is __not__ a mechanism to convey opt-out; that should be done using the LRW record [soft] deletion mechanism.

One of the benefits of ACTIVE_MEMBERSHIP is that it allows for the ETL to use definitive status codes from the SRS, rather than for downstream users to have to rely on dates, which are often tinged with fiction.

**Comment by alanepaull** [comment]
Revision to ACTIVE_MEMBERSHIP completed.
