### ISSUE TITLE
PROVIDED_AT showing wrong example

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#299]
PROVIDED_AT should be a string in ISO 8601 format.  The example given is:
YYYY-MM-DDThh:mm

However this does not include the timezone which is necessary for ISO 8601.  The example should be:
YYYY-MM-DDThh:mmZ

Can we please update across all entities?

**Comment by arc12** [comment]
AFAIK ISO8601 does not require locale information for validity.

I would generally be happier to go with the status quo, which I understand as "this is the local datetime according to the source system clock"
This accords with the role of PROVIDED_AT which is to consider the source, rather than LDH, time.

There is a bit of an issue with knowing whether local time is adjusted for "daylight savings", in which case knowing we're talking UTC would help, in the possible scenario that data extract occurs. around the twilight zone of a "clocks go back".

So: so long as we're confident source system ETL correctly represents its timestamps as UTC, rather than simply appends "Z" to the string (!), I can see requiring UTC has some (albeit small) advantage... just not for the same reasons as Gareth starts with

**Comment by gmoger-jisc** [comment]
This is the way that HT2 are handling it, and rejecting records with no timezone.  So there is a mismatch between the documentation and implementation.

I don't have particularly strong feelings on it either way so I am happy to go with the consensus.  

Options being:
1. HT2 update validation to match existing specification and allow format YYYY-MM-DDThh:mm
2. Specification is changed to be clear that timezone should be provided.

I think this statement about the field from Adam is correct: "this is the local datetime according to the source system clock".  The worry is that they will just append 'Z' to a date string.  In which case I think it is safer to stay with option 1 and get HT2 the implement as per the spec.

**Comment by arc12** [comment]
Understood.
The key thing for me is that PROVIDED_AT provides an indexed field that can be queried to acquire data "deltas". So long as that is reliable, I dont care, no matter what my comments might indicate... :-)

**Comment by gmoger-jisc** [comment]
OK - let's confirm on the next call and I will feedback to HT2 if we want it to be timezone agnostic.

**Comment by alanepaull** [comment]
Agreed. I'll note this for the next call.

**Comment by alanepaull** [comment]
From 5 Nov 18 call: Amend so that suppliers give the Z if they have it, but don't insert it otherwise.

**Comment by alanepaull** [comment]
Completed in 1.4.1_development
