### ISSUE TITLE
course aim code list omission

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#300]
For course aim, this is valid according to HESA but not in the documentation

I78 | Level 5 Diploma in Education and Training (DET)

**Comment by gmoger-jisc** [comment]
Yes, what is your thoughts on historic codes that have been removed from HESA?  Often we see them coming through in the data as they have not re-mapped to our accepted list.  

Do  we ask institutions to conform to the latest spec, even with their historic data?

**Comment by arc12** [comment]
For those cases where the UDD codes are un-mapped, I think we should retain any codes which have been valid within an N-year window (N=5 prior years?).
i.e. historical coding remains as "correct"

**Comment by alanepaull** [comment]
We have 2 codes to be added, plus 1 I'm not sure about:

course.COURSE_AIM
I78	Level 5 Diploma in Education and Training (DET)

student_course_membership.WITHDRAWAL_REASON
From HESA WITHDRAWREASON
47	Learner has transferred to another provider due to merger
From HESA RSNEND
12	Transferred out as part of collaborative supervision arrangements

This last one is the one I'm not sure of. We have it in the COURSE_OUTCOME property, but not in the WITHDRAWAL_REASON. There are other RSNSEND codes in WITHDRAWAL_REASON that conceptually seem as reasonable to include as this one. Shall we add it or not?

In addition, I'm updating the HESA links in v1.4.1, as these are rather out of date. This is all separate from Data Futures.

**Comment by gmoger-jisc** [comment]
Seems fine to add it if we have with the others.

**Comment by alanepaull** [comment]
Those have been added, and HESA links are now up-to-date for 2018-19. They'll need updating again for Data Futures later. All this is in v1.4.1_Development.
