### ISSUE TITLE
Timetable integration

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#302]
We want to bring in timetable data in to the UDD as an easier way to managing and interpret attendance data.  

This will also enhance the functionality in our Check-In app to enable institutions to record attendance to events already defined in their timetabling system.

Currently attendance events are linked to module instances, but not all students on a module instance are required to attend all events; they might be split up into different cohorts.  The existing spec does not allow us to analyse the data based on whether a student was registered on that event and so have an accurate cohort to use.  While in some cases we can look at all students on that specific event, many systems we receive data from do submit records for non-attendance.  Being able to clearly define the events and the students relationship will help us mitigate this.

This is an outline of the entities and fields we would need to capture (requirements have not been signed off as yet):

**Event**
EVENT_ID
EVENT_NAME
EVENT_DESCRIPTION
EVENT_START
EVENT_END
EVENT_LOCATION
EVENT_TYPE
MOD_INSTANCE_ID

**Student on Event Instance**
STUDENT_ON_EVENT_INSTANCE_ID
EVENT_ID
STUDENT_ID

The actual attendance will still be recorded as xAPI through existing means (TSV loads or Check-In app) but drawing on the above for better context.

**Comment by gmoger-jisc** [comment]
I have reviewed this today and want to propose the following for discussion.

**Event**

Field Name | Description | Format
-- | -- | --
EVENT_ID** | Primary key for event table | String (255)
EVENT_NAME | Name of event | String (255)
EVENT_DESCRIPTION | Description of event | String (255)
EVENT_START | Start date/time | ISO 8601 Datetime (eg 2015-05-24T09:00Z)
EVENT_END | End date/time | ISO 8601 Datetime (eg 2015-05-24T09:00Z)
EVENT_LOCATION | Where the event took place | String (255)
EVENT_TYPE | Event categories | String (255) – code list
MOD_INSTANCE_ID* | Module instance id, as foreign key | String (255)

MOD_INSTANCE_ID will not be mandatory and we might think of modules more simply as a ‘chunk of activity’ which may or may not be related to academic outcomes e.g. induction or school/faculty/library events.  This will potentially allow us to capture different kinds of events in future.

We might also consider that events are tied to courses instead of modules and include COURSE_INSTANCE_ID for linkage however that is outside of the current scope of development so will not be included right now.

**Student on Event**

Field Name | Description | Format
-- | -- | --
STUDENT_ON_EVENT_ ID** | Primary key for table | String (255)
EVENT_ID* | Foreign key to event table | String (255)
STUDENT_ID* | Foreign key to student table | String (255)

**EVENT_TYPE code list**

Code | Description
-- | --
10 | Dissertation
11 | Field Trip
12 | Assessment
13 | Lecture
14 | Meeting
15 | Practical
16 | Laboratory
17 | Seminar
18 | Tutorial
19 | Workshop
20 | Study Skills
21 | Other

We might need to review these to see if there is a better way to group or categorise them however these were the top recurring types I can see across different institutions data.

**Comment by alanepaull** [comment]
I've drafted an **event** entity and **student_event** entity reflecting @gmoger-jisc's comments above. The event entity links to the student entity via the student_event entity (see diagram linked below).

See:
https://github.com/jiscdev/analytics-udd/blob/v1.4.1_development/udd/event_DRAFT.md
and https://github.com/jiscdev/analytics-udd/blob/v1.4.1_development/udd/student_event_DRAFT.md and https://github.com/jiscdev/analytics-udd/blob/v1.4.1_development/media/UDDdiagram_DRAFT.png.

These entities concern future events that students are registered on, or expected to attend. So, typically these might be lectures, seminars, practicals, assessments, and so on. They capture timetable data, which can be linked to actual attendance xAPI data to give a clearer picture around attendance. In addition, they have the capacity to support Intelligent Campus requirements, though this is secondary.

Some pointers for discussion:

1. **Formal exams**. Should this data include formal end-of-year exams? We have an EVENT_TYPE for 'assessment'. I suspect that exams should be included (pretty important); if data is available.
2. Cardinality. Which properties should be optional and which mandatory? I've been relaxed in relation to the event entity (only EVENT_ID and EVENT_NAME are mandatory), because it looks best to be liberal until we have a clear idea what's available and what's useful. I've been strict with student_event, because this is a linking entity.
3. **COURSE_INSTANCE_ID**. Gareth suggested that we don't (yet) need this. However, institutions can use the courseArea xAPI extension to include a COURSE_INSTANCE_ID, so it doesn't feel wrong to include this option in the UDD at this stage; it would save adding it later, and in the meantime enable some play.
4. **EVENT_TYPE**. We need to discuss the content of the code list for this (see above for Gareth's tentative list, which is in the current draft MD file). I suspect that we'll wish to EITHER (a) home in on a relatively short list of terms for UDD usage using mappings from local terms, OR (b) enable institutions to use their own controlled lists for ease of local presentation, OR (c) have both. My preference is (c) on the grounds of flexibility.
5. **Intelligent Campus booking entity**. Our current draft Intelligent Campus spec has a similar entity to this event entity, called booking. A booking is an abstraction of a timetabling entry related to a module instance. The booking specification is derived from the APIs of the CELCAT and Syllabus Plus solutions typically used for timetabling by UK providers. There may be merit in using an entity as similar as possible to this, because the purpose of the booking entity is similar to event, namely to link into the UDD. See: https://github.com/Cetis/intelligent-campus/blob/master/udd/booking.md.
Differences include event == booking, EVENT_NAME == NAME. There are more details specific to Intelligent Campus on the booking entity, such as layout, room_id and capacity. It would be possible (and credible) to amend the naming in Intelligent Campus in line with the proposed additions to the UDD (for example, 'booking' could become 'event').
6. **Location**. In Intelligent Campus we define location more closely than in the UDD. There may be merit in considering this approach for the UDD, despite the overhead of extra data, because the drafted EVENT_LOCATION property in event (arbitrary string) may not be of further use - it seems to be a dead end, rather than a potential link to other data about the location. The booking entity (and by extension the event entity) could use a ROOM_ID property to link the event's room to the module or course. Further details of location can then be determined via the site and location entities in the Intelligent Campus model. The site and location entities from Intelligent Campus could be added to the model later, if not desired now.

**Comment by alanepaull** [comment]
From monthly call 10 May 2019: event and student_event entities to be implemented on Wednesday 15 May as part of v1.4.1 UDD release. Add EVENT_TYPE_RAW to event, as a means of storing the original event type in institution's own vocabulary. Add ROOM_ID to event for compatibility with booking entity in Intelligent Campus. In E-R diagram, remove explicit links from event to module_instance and course_instance (these are optional).

**Comment by ryansmith94** [comment]
Changes to UDD code have been made, I will merge and release those changes once v1.4.1 is released and the code has been reviewed at HT2. Deployment is scheduled with James for Friday morning.

**Comment by ryansmith94** [comment]
@gmoger-jisc are there any database indexes you need on these two entities?

Right now I've got the following indexes for the event entity.
```ts
table.primary(['organisation', 'EVENT_ID']);
table.index(['organisation', 'PROVIDED_AT']);
table.index(['organisation', 'MOD_INSTANCE_ID']);
table.index(['organisation', 'COURSE_INSTANCE_ID']);
```

And I've got the following indexes for the student event entity.
```ts
table.primary(['organisation', 'STUDENT_EVENT_ID']);
table.index(['organisation', 'EVENT_ID']);
table.index(['organisation', 'STUDENT_ID']);
table.index(['organisation', 'PROVIDED_AT']);
```

**Comment by gmoger-jisc** [comment]
No, this looks sufficient.

**Comment by alanepaull** [comment]
v1.4.1 is now live. Please let me know if there are any problems with event and event_student!

**Comment by gmoger-jisc** [comment]
In the naming conventions we have student_event.tsv.  Can this please be changed to 'studentevent.tsv'?

**Comment by alanepaull** [comment]
student_event corrected to studentevent in 3 places in the filename_conventions.md file in master and in v1.4.2_development.

**Comment by ryansmith94** [comment]
Hey both, changes have just been deployed.

**Comment by gmoger-jisc** [comment]
Can we be more explicit on the START/END time fields of the event entity to show the full ISO format e.g:

2019-04-05T16:15:00:000Z

They are stored in the database with the millisecond component so this should be reflected in the documentation.

**Comment by arc12** [comment]
What, not nanoseconds :-)

IMO the spec should indicate that start/end MUST give minute precision and MAY give additional precision.
i.e. do not tie the spec to a particular database storage/retrieval/formatting idiosyncrasy of milliseconds

Data consumers should tolerate both the presence and absence of seconds, including decimal seconds.

Also AFAIK, the ISO8601 uses decimal seconds, rather than an additional colon.

Cheers, Adam

**Comment by gmoger-jisc** [comment]
Yep, the database will accept additional precision (optional only) but where it is not given, in the HT2 implementation at least, it will be stored as zero's.

For example 2019-04-05T16:15:00Z becomes 2019-04-05T16:15:00:000Z.

Perhaps the example should be:
YYYY-MM-DDThh:mm:ss[.mmm]Z (eg 2012-03-29T10:05Z)

I can't see anyone submitting milliseconds frankly, I'm just trying to manage variations when processing.

**Comment by alanepaull** [comment]
Yes, there has been some divergence in the particular ISO 8601 version to use. I'm happy to home in on optional second and milliseconds, like this:

YYYY-MM-DDThh:mm[:ss.mmm]Z
[:ss.mmm] are optional and will be zero filled where not given.
Examples: 2012-03-29T10:05Z  2012-03-29T10:05:00Z  2012-03-29T10:05:00.000Z

This is not a substantive change, so I propose to include it in 1.4.2 release.
