### ISSUE TITLE
Student FTE

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#303]
Can we please look to capture the student FTE.  This would correspond with HESA's STULOAD:
https://www.hesa.ac.uk/collection/c17051/a/stuload

This would be recorded against their course membership.

We already capture MODE but this does not give us the detail needed to compare student activities across different FTE's.

**Comment by alanepaull** [comment]
MODE is recorded against student_course_instance (a specific year of study) rather than student_course_membership (a whole course). I believe that both MODE and STULOAD can change in different years of the same course. So, it might be better to record our equivalent of STULOAD against student_course_instance.

There are a lot of HESA rules about calculating FTE: see https://www.hesa.ac.uk/collection/c18051/fte. In the light of this complexity, one method would be simply to ask providers to supply STULOAD if they supply it to HESA. Then, we would name our property STULOAD and clearly adhere to the HESA guidance. Alternatively, if our requirement is different, then we could have a simplified calculation.

I think I would recommend the HESA STULOAD version for simplicity.

**Comment by arc12** [comment]
+1 for SoCI

I think consistency is key, so by default UK HE providers should use STULOAD as per HESA. For FE or mixed FE/HE provision, there might be a case for doing differently. Realistically, we might end up with different rules in use in one dataset, but that should be avoided if possible

**Comment by gmoger-jisc** [comment]
That seems fine, with both on student course instance as you suggest.

**Comment by alanepaull** [comment]
Monthly call 29 March 2019: Agreed to introduce a new property **FTE** on student_on_course_instance that providers should use to record HESA STULOAD if possible. If not possible, then providers should use their best calculation, so that the LDH has a reasonable approximation of full time equivalence for the student.
