### ISSUE TITLE
Module mapping - domain specific

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#306]
Can we discuss updating the 'module vle mapping' entity to specify a domain, much like with the 'student id map'?  This would allow us to manage module mappings across systems and not just VLE.

As an example, with reading list systems like Talis, institutions are grouping content around modules but the identifiers are not always consistent with how this is stored in their student record system (or VLE module ID's).

**Comment by alanepaull** [comment]
This requirement suggests linked properties of DOMAIN and IDENTIFIER, where the latter identifies the local ID of the module.

## DOMAIN
### Description
Identifies the system within which IDENTIFIER exists.

### Purpose
Efficient processing of IDs, and lookup of data in xAPI statements.

### Valid values
A URL that identifies the system within which IDENTIFIER exists, for example a VLE or reading list system

### Format
String (255)

## IDENTIFIER
### Description
Local ID for the module, as used in DOMAIN.

### Purpose
Enables identification of module in DOMAIN.

### Valid values
Any

### Format
String (255)

A question I have is whether this requirement refers to module or module_instance?

**Comment by gmoger-jisc** [comment]
Module instance.  Let's discuss this one on the call shortly.

**Comment by alanepaull** [comment]
Monthly call 29 May 2019: Agreed to implement this change for v1.5. This new entity tentatively called module_mapping, replaces module_vle_map. However, in order to give time for smooth implementation, module_vle_map may have to be included, but deprecated, in v1.5 alongside the new entity. A decision on whether to include and deprecate module_vle_map will be taken before the release of v1.5.

module_mapping would consist of the following properties:

MODULE_MAPPING_ID **
MOD_INSTANCE_ID [1] *
DOMAIN [1] *
IDENTIFIER [1] *
PROVIDED_AT [0..1]

How this relates to the MODULE_VLE_MAP_MODE property in institution has yet to be determined.

**Comment by alanepaull** [comment]
Draft module_map entity is here: https://github.com/jiscdev/analytics-udd/blob/v1.5_development/udd/module_map.md

For discussion at next monthly call.

**Comment by alanepaull** [comment]
@arc12 has no need for MODULE_VLE_MAP_MODE, so I propose to remove that functionality.

In addition, I agree with @arc12 that we shouldn't use 'module' or 'module_instance' in relation to the non-UDD VLE entities, because these may not actually be modules, but may relate to a different concept. This means we should perhaps rename DOMAIN_MOD_INSTANCE_ID, so that it doesn't suggest this. New name: DOMAIN_MAPPED_ID?

@arc12 also suggests that we are not prescriptive about the meaning of the relationship. While in some cases there may be an identical-thing case, we shouldn't prescribe it. So, it's an association, rather than a 1-1 relationship between the identifiers.

I've amended Draft module_map entity accordingly: https://github.com/jiscdev/analytics-udd/blob/v1.5_development/udd/module_map.md.

**Comment by alanepaull** [comment]
22 July 2019 monthly call: current draft agreed.
