### ISSUE TITLE
Capture formative summative details in assessment instance

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#318]
Can we please look to add a new property in assessment instance to capture whether an assessment is formative or summative.

**Comment by robwynj** [comment]
For inclusion in UDD 1.5 please of course :)

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, CSM & CSPO Scrum, ISEB Certified
APMG PRINCE2 & AgilePM Certified Practitioner
Director of Data Analytics, Jisc
email: rob.jones@jisc.ac.uk skype: robwynj twitter: @robwynjonesmobile: 07468 727040
web: www.jisc.ac.ukNot<http://www.jisc.ac.ukNot> on iOS? Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alanepaull** [comment]
Our current description of assessment_instance includes: "The assumption is that grades and/or marks in assessment_instances are summative." The assessment_instance design is, to an extent at least, built on this summative approach. Therefore its main content deals with types from the SRS, weight towards module mark, and the marks themselves.

A simple solution would be to add a Boolean Y/N for summative, with a Y default. However, are there additional requirements for formative assessments over and above this simple or simplistic solution? For example, formative assessment might be linked explicitly to feedback. In addition, there would be some essential business rules within assessment_instance - for example, if 'summative = N', then assess_weight must be blank.

Would it be possible to provide a couple of scenarios for use of formative assessments, so that we can identify any potential additional requirements?

**Comment by gmoger-jisc** [comment]
I think a simply flag of summative y/n is sufficient.  If they have populated weightings then these will simply be ignored when it comes to the analytics.

I will look into the examples with @JemmaGreener

**Comment by alanepaull** [comment]
I propose to implement this in a similar way to MOD_OPTIONAL. This is a string value rather than a Boolean, but it is the style previously adopted, presumably for a significant reason.

If there is a preferred alternative style for Boolean, please indicate.

## ASSESS_SUMMATIVE
### Description
Indicates whether the assessment_instance is summative or formative.

### Purpose
To provide information about the assessment.

### Derivation
Jisc

### Valid Values
<table>
<tr><td>ASSESS_SUMMATIVE</td><td>DESCRIPTION(ENGLISH)</td><td>DESCRIPTION(WELSH)</td></tr>
<tr><td>1</td><td>Yes; summative</td><td>Ie</td></tr>
<tr><td>2</td><td>No; formative, not summative</td><td>Na</td></tr>
</table> 

### Format
String (255)

### Notes

**Comment by arc12** [comment]
I'd be inclined to make the semantics more open, with formative and summative being concepts from a potentially larger set. For example, some people may wish to discriminate a diagnostic assessment from the other two. There may be further cases.
So: something like ASSESSMENT_PURPOSE with a code list with F=formative, S=summative, D=diagnostic

**Comment by Josh-Ring-jisc** [comment]
I like the proposal from @alanepaull, It is simpler and easier to get right, which means the data will be more useful.

Related to this issue, I have reopened: https://github.com/jiscdev/analytics-udd/issues/326

**Comment by alanepaull** [comment]
22 July 2019 monthly call: Boolean solution favoured, but checking for alternative requirements prior to implementation.

**Comment by alanepaull** [comment]
I've amended the concept so that it is purely 1=summative, 2=not summative. There is no inference that not summative = formative.

**Comment by alanepaull** [comment]
There is one further question about ASSESS_SUMMATIVE. Previously, it could be inferred that assessment_instances contained summative grades or marks, as this has been prescribed in the description of the entity. If a supplier omits ASSESS_SUMMATIVE, we can no longer properly infer that the grade or mark is summative.

This suggests to me that ASSESS_SUMMATIVE should be mandatory with a default value of 1 (summative).

Is this the logic that we want here?

**Comment by gmoger-jisc** [comment]
I would rather not make it mandatory.  Maybe we change the description of the entity to say that records are deemed summative unless specified by the field.

**Comment by alanepaull** [comment]
I have reverted that. Final position is now in place in v1.5: https://github.com/jiscdev/analytics-udd/blob/v1.5_development/udd/assessment_instance.md#assess_summative
