### ISSUE TITLE
ASSESS_TYPE_ID needs to be made categorical, take two.

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#326]
## I think this issue needs to be reopened.
Previous issue: https://github.com/jiscdev/analytics-udd/issues/221

#### The `ASSESS_TYPE_ID` column is in complete disarray
A survey across the UDD's of many sites (in no particular order) has this `ASSESS_TYPE_ID` in complete disarray (one row per site), with some universities having ~9900 unique `ASSESS_TYPE_ID` values.

![image](https://user-images.githubusercontent.com/29859996/60900840-cd853800-a264-11e9-9336-fded8ff39fd3.png)

### I propose the following to solve this issue:

Column | Description
------------ | -------------
| RAW_ASSESS_TYPE_ID | University's internal ASSESS_TYPE_ID name |
| ASSESS_TYPE_ID | Categorical ASSESS_TYPE_ID see below

### Coding:
I have adopted Tribal's set of ASSESS_TYPE_ID categories and added a category for group work, to indicate the final mark is a reflection of several people.

| ASSESS_TYPE_ID valid values | Description
------------------------------------------|----------------------
| "assignment or coursework" | Individually submitted work. |
| "exam" | Individual work under exam conditions. |
| "practical or observation" | Lab work, performance, demonstrated competence. |
| "group work or discussion" | The mark is a reflection of a group's efforts. |
| "oral exam or viva" | Competence demonstrated orally, under exam conditions. |
| "other" | Misc entry, which cannot fit into the above categories. |

**Comment by alanepaull** [comment]
While not disagreeing with the sentiment here that there may be an issue to resolve, I'm not quite certain of the meaning of the example data above. It seems to suggest that 2 providers have a major issue (the top 2) with what they're supposed to supply in this field? Though, I confess I'm not certain what the first column means.

**Comment by alanepaull** [comment]
Reading through #221, is there merit in addressing the issues identified there?

The last piece of the conversation in #221 was:
"...agreed to handle this issue via application layer extension properties and test out any revised code lists.
We will continue to use the UDD defined material "as is" for ASSESS_TYPE_ID, as we do now. Note: this is String Any value, so can be used already for code lists at institution or vendor instigation.
To test any new generic code lists, we can use the ASSESS_TYPE_ID for raw values, coupled with an extension that defines and uses a generic code list to which the raw values are mapped.
We agreed to re-visit this issue in 6 months time. In the meantime, we should start discussions with Pathfinders, as suggested above by @arc12."

@arc12 raised these issues:

- getting agreement on a mapping from local codes is a source of delay, so using post-UDD for more agility/flexibility
- consulting academic leads is important on this one. In consulting, we should be clear about the uses we expect to put this information to, otherwise they will be answering their own questions to a large extent.
We use this information (condensed down to our core set) to:
a) summarise the assessment style of a module
b) categorise assessment resultsm with a thought that different types might be differently predictive of module outcome
c) to guess at assessment sequencing when due dates are missing

**Comment by alanepaull** [comment]
We could address this issue by adding and modifying the following properties in assessment_instance:

**ASSESS_RAW_TYPE_ID**
**Description**: A provider's unique identifier for the type of assessment as defined in their student record system (for example, CW for Coursework). It is mapped to common UDD values held in ASSESS_TYPE_ID.
[This is the current definition of ASSESS_TYPE_ID.]

**ASSESS_RAW_TYPE_NAME**
**Description**: A provider's description for the type of assessment as defined in their student record system (for example, Coursework).
[This is the current definition of ASSESS_TYPE_NAME.]

**ASSESS_TYPE_ID**
**Description**: Standardised UDD identifier for the type of assessment.
**Values**: A table of suitable identifier values with labels and definitions, as for other UDD coded properties.

Then, we might have an ASSESS_TYPE_ID table that looks a bit like this:

<table>
<tr><td>ASSESS_TYPE_ID</td><td>DESCRIPTION (ENGLISH)</td><td>DESCRIPTION (WELSH)</td><td>DEFINITION</td></tr>
<tr><td>1</td><td>assignment or coursework</td><td></td><td>Individually submitted work</td></tr>
<tr><td>2</td><td>exam</td><td></td><td>Individual written work under exam conditions</td></tr>
<tr><td>3</td><td>practical or observation</td><td></td><td>Lab work, performance, demonstrated practical skill or competence</td></tr>
<tr><td>4</td><td>group work or group discussion</td><td></td><td>Assessment of a group or participation in a group activity</td></tr>
<tr><td>5</td><td>oral exam or viva voce</td><td></td><td>oral assessment</td></tr>
<tr><td>98</td><td>Other</td><td></td><td>Type that does not fit into the above categories</td></tr>
<tr><td>99</td><td>Not known</td><td></td><td></td></tr></table>

I think we will need further discussion and perhaps consultation with academics on the above.

**Comment by Josh-Ring-jisc** [comment]
> I think we will need further discussion and perhaps consultation with academics on the above.

- An initial crude analysis I did on some universities had upwards of 70% as written assignments. 
- I think adding any more (small) categories, (at the suggestion of academics or otherwise) would not have enough population to justify their existence.

I think we should proceed with the above as it has all of us (Jisc, Tribal, Cetis) in broad agreement, with a Win-Win scenario.

**Comment by arc12** [comment]
sorry folks for not replying earlier - been off work.

Referring back to Josh's summary, my view is that looks about like I would expect.
2 sites have clearly not understood what the field is, probably being deceived by "_ID" in the field name and not taking the time to read the spec.
The 62 unique values looks like an outlier; I'd want to ask them questions to understand whether there was some kind or policy/procedure change which caused this.

I retain my previous position that requiring people to map codes which are in their SRS to a nice tidy list before setting up ETL is problematical. I wont repeat points here.

The proposal for a "raw" version does give us a workaround, in that we can initially work with the as-is. and can always cross-check it against the massaged version. The massaged version can be left as an empty column in the initial ETLs to get things started. One remaining fly in the ointment is that any tweaks to the mapping during onboarding a client's data would now mean mass updates in the LDH, and still the inertial of an ETL change. My preference remains to do the mapping on "our" side of the customer-provider systems fence.

This would be a BREAKING change - the conceptual attribute changes its name and a NEW concept takes its former place - but we could live with it if Jisc are keen.

Re the actual proposal, some reactions/thoughts:
1. no code for "not known" please. Just missing data, NA, or NULL according to your vocabulary.
2. omit assess-raw-type-name. I think this kind of thing is best handled by an out-of-udd transfer of code lookup tables from the client. Arguably, UDD could define an entity to transfer the lookup table from the SRS. Denorming into a "real" entity like assessment-instance feels like a bad move.
3. since this is breaking change, maybe consider renaming to avoid the lazy "_ID means its an id" assumption. ASSESS_TYPE and ASSESS_RAW_TYPE. This would also avoid problems with legacy data in which "ASSESS_TYPE_ID" means one thing and other date in which it means another, with only inspection of code values to resolve... yuk

Cheers, Adam

**Comment by alanepaull** [comment]
Thanks, Adam. All this looks good. Re ASSESS_RAW_TYPE_NAME - I meant to take that out before posting! D'oh!

You're right, this is a breaking change. We're looking at this to go live in the first of the v1.5 versions, which would be for new academic year (in other words, for this autumn).

Revised proposal, if we can agree Adam's point about mapping before setting up ETL above; noting that these properties are optional, so providers could do this in either way until things settle down (?):

**ASSESS_RAW_TYPE**
**Description**: A provider's unique identifier for the type of assessment as defined in their student record system (for example, CW for Coursework). It is mapped to common UDD values held in ASSESS_TYPE.
[This is the current definition of ASSESS_TYPE_ID.]

**ASSESS_TYPE**
**Description**: Standardised UDD identifier for the type of assessment.
**Values**: 

<table>
<tr><td>ASSESS_TYPE</td><td>DESCRIPTION (ENGLISH)</td><td>DESCRIPTION (WELSH)</td><td>DEFINITION</td></tr>
<tr><td>1</td><td>assignment or coursework</td><td></td><td>Individually submitted work</td></tr>
<tr><td>2</td><td>exam</td><td></td><td>Individual written work under exam conditions</td></tr>
<tr><td>3</td><td>practical or observation</td><td></td><td>Lab work, performance, demonstrated practical skill or competence</td></tr>
<tr><td>4</td><td>group work or group discussion</td><td></td><td>Assessment of a group or participation in a group activity</td></tr>
<tr><td>5</td><td>oral exam or viva voce</td><td></td><td>oral assessment</td></tr>
<tr><td>98</td><td>Other</td><td></td><td>Type that does not fit into the above categories</td></tr></table>

**Comment by Josh-Ring-jisc** [comment]
The above looks good, agreed.
 >You're right, this is a breaking change. We're looking at this to go live in the first of the v1.5 versions, which would be for new academic year (in other words, for this autumn).

Yes sounds reasonable.


> This would be a BREAKING change - the conceptual attribute changes its name and a NEW concept takes its former place - but we could live with it if Jisc are keen.

Very keen.

> Revised proposal, if we can agree Adam's point about mapping before setting up ETL above; noting that these properties are optional, so providers could do this in either way until things settle down (?):

They are optional (in the short term), but will be important when you want to understand the nature of assessments at your university, so as a more longer term ambition.

**Comment by gmoger-jisc** [comment]
These are some of the top ASSESS_TYPE_NAME entries across our institutions.  It might help in establishing our own code set:

![image](https://user-images.githubusercontent.com/36480934/61643944-c1a16900-ac9b-11e9-90fe-15a737aad7e5.png)

**Comment by Josh-Ring-jisc** [comment]
> ### ASSESS_RAW_TYPE
> Description: A provider's unique identifier for the type of assessment as defined in their student record system (for example, CW for Coursework). It is mapped to common UDD values held in ASSESS_TYPE.
[This is the current definition of ASSESS_TYPE_ID.]


might become:


### ASSESS_RAW_TYPE
Description: A provider's unique identifier for the type of assessment as defined in their student record system (for example, CW for Coursework). It is mapped to common UDD values held in ASSESS_TYPE.
[This was previously stored in the ASSESS_TYPE_NAME, which has now been removed.]

**Comment by alanepaull** [comment]
Our current categories are:
- assignment or coursework
- exam
- group work or group discussion
- oral exam or viva voce
- other
- practical or observation

Having mapped Gareth's longer list above against our short list of 6 categories, they mostly go, with some exceptions we might want to consider.

![assessment_methods](https://user-images.githubusercontent.com/17160871/61717996-fffd5d80-ad59-11e9-9147-6a29fe0088c4.JPG)

We can eliminate some of these from consideration, because there's not enough detail to classify them, or they are simply not assessments:
- (NULL)
- Formative Assessment
- Semester Assessment
- ATTENDANCE ONLY
- Supplementary Assessment
- NOT KNOWN
- turnitintooltwo (though this may be 'assignment or coursework'?

This leaves us with a couple of candidate additions:
- Project
- Presentation

Both of these *could* be mapped to 'assignment or coursework', but both stand up pretty well in terms of numbers against our other terms. Are these 2 candidates sufficiently distinguishable from other categories to gain us better quality data, and are the numbers sufficient to justify it?

There are pros and cons. Main pro is that we'll get more detail and the numbers in Gareth's sample suggest that these might be useful. I think providers could readily use these categories, if they record something similar themselves. However, the con may be, if a provider doesn't record a Project as anything different in their own SRS, but just puts them as 'coursework', we're probably trying to differentiate something that cannot be handled.

My recommendation would be to add in Project and Presentation to our short list, but I'm open to counter-views. That would make our list (in alphabetical order):

- assignment or coursework
- exam
- group work or group discussion
- oral exam or viva voce
- other
- practical or observation
- presentation
- project

Any comments?

**Comment by gmoger-jisc** [comment]
Does an assignment always equate to coursework?

I think it is fine to add these extra values, even if there is some overlap between them and the others.

**Comment by gmoger-jisc** [comment]
For the sake of expediency (as we could probably debate the categories for a long time) I suggest we stick with what Alan has proposed.  If we need to add or make amendments then these can be added as non-breaking changes.

**Comment by Josh-Ring-jisc** [comment]
Agreed.
