### ISSUE TITLE
Additional fields for LA UDD? (for HEI and Jisc ingress/ storage purposes)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#335]
Dear All,

We've had various discussions about additional fields which may be of benefit to the LA service moving forwards - be they additional fields for which we could obtain useful data from HEIs eg. like HESA's "CARELEAVER", to fields which we may potentially require ourselves in Jisc, to store useful markers/ information about students (output of our own LA processes/ software, related to a student, where it needs a defined location for storage). These are defined fields in the UDD, bypassing the extensions facility, where they need explicit area of storage as standard.

I'd like to open this up, for consideration of CARELEAVER in the first instance (from Student.Entry_Profile entity):

https://www.hesa.ac.uk/collection/c19051/a/careleaver

I also came across this new (not seen this before!) Student entity field, which may also be useful for consideration:

https://www.hesa.ac.uk/collection/c19051/a/carer

Kind Regards, 

Rob

**Comment by arc12** [comment]
Rob - 
I can see value in care-leaver, and similar.

Could we consider adding these to a 1.4.x as well as to 1.5, please. I think that is in keeping with the compatibility rules for patch releases and it gives a lower barrier to adoption.

I think we should, for care-leaver and any others similar we consider, take care to decide whether the attribute is an "intrinsic", an "on entry" or a "this year/stage" attribute. Care-leaver is clearly about the student prior as they applied, so is "on entry" (i.e. SCM). Whether or not the student is a carer may apply, or stop applying, during the course so we would need to capture this against SoCI. IF SRSs dont store CARER in such a way to allow for this level of description - e.g. over-writing a student-level attribute - then we should (IMO) not include the attribute in UDD as it would be misleading in historical data.

**Comment by alanepaull** [comment]
CARELEAVER: For student_course_membership. I propose to follow the HESA field exactly and refer to their details, because this is a new HESA field with much complexity, and I don't think it would help our users to attempt any clarification.

## CARELEAVER
### Description
Whether the student is a care leaver.

### Purpose
For analytics

### Derivation
https://www.hesa.ac.uk/collection/c19051/a/careleaver


### Valid Values & Mappings
<table>
<tr><td>CARELEAVER</td><td>DESCRIPTION (ENGLISH)</td><td>DESCRIPTION (WELSH)</td><td>HESA (CARELEAVER)</td></tr>
<tr><td>01</td><td>Care leaver (16+)</td><td></td><td>01</td></tr>
<tr><td>02</td><td>Looked after in Scotland</td><td></td><td>02</td></tr>
<tr><td>03</td><td>In care in the rest of UK</td><td></td><td>03</td></tr>
<tr><td>04</td><td>UCAS defined care leaver</td><td></td><td>04</td></tr>
<tr><td>05</td><td>Not a care leaver</td><td></td><td>05</td></tr>
<tr><td>98</td><td>Information refused</td><td></td><td>98</td></tr>
<tr><td>99</td><td>Not known</td><td></td><td>99</td></tr>
</table>  

### Format
String (255)

### Notes

This property is identical to the HESA CARELEAVER field. Please refer to the link https://www.hesa.ac.uk/collection/c19051/a/careleaver for definitions, details of coverage and other information about this data.

**Comment by alanepaull** [comment]
In HESA, CARER is for Scotland and Wales, not England. This suggests that English providers may not have it. See https://www.hesa.ac.uk/collection/c19051/a/carer.

**Comment by arc12** [comment]
I dont yet have the data to back up an assertion that it is used extensively but our SRS (SITS) does support this kind of information in relation to applications, and I see UCAS has a page explaining what applicants who are carers should do...

**Comment by alanepaull** [comment]
CARELEAVER property added to student_course_membership. Diagrams and changes documentation updated.

**Comment by arc12** [comment]
Hey folks - 
I think we put CARELEAVER on the wrong entity.
My initial comment was more about where CARER should go, and I didnt give proper thought to asserting that CARELEAVER should go on SCM.

The definition of care leaver indicates it should better go on STUDENT. You cant change whether or not you have been in care!
The only counter-argument I can see is that it is possible for young people to enter care after 16, so for FE use, CARELEAVER might change during studies. I see this as a bit of an edge case and the conclusion it drives us to - put it on SoCI - would, I think muddy the waters rather than clear them... and the counter-counter arguement is that from a LA point of view, CARELEAVER is telling us something about the background (which we expect is indirectly linked to outcome patterns) rather than the immediate student circumstances (e.g. for CARER, we expect it is the immediate circumstances which matter, when considering outcomes, rather than whether someone has been a carer).

**Comment by robwynj** [comment]
Yes, it comes from UCAS – so it’s a PERSON table field in the HESA SR.

RWJ

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, ISEB, Scrum CSM & CSPO Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
We could add CARELEAVER to student and remove it from student_on_course_instance as a non-breaking change, I think.

**Comment by arc12** [comment]
if no-one is yet working against 1.5 then nothing breaks :-)

**Comment by robwynj** [comment]
Agreed. I want to keep it – even if we only use it for display purposes (optional, per HEI) in Data Explorer. I am keen to utilise any other beneficial field, optional, if they are only used even for display purposes in our software, in one common location for users.

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, ISEB, Scrum CSM & CSPO Certified; APMG Prince2 & Agile Certified Practitioner

Director of Data Analytics – Jisc
Cyfarwyddwr Data Dadansoddiadau - Jisc

email & skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Monday 14 Oct 2019: Agreed to check with @arc12 re usage, then delete from student_course_membership and add to student for v1.5.1 release by end of October.

**Comment by arc12** [comment]
@alanepaull we've already coded-up against STUDENT in anticipation!

**Comment by alanepaull** [comment]
Now implemented in v1.5.1_development: CARELEAVER has been removed from student_course_membership and added to student.
