### ISSUE TITLE
Extend list of domains for student id map

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#354]
The current accepted values are HUSID and ULN, as here:
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_id_map.md#domain

Can this be extended to include:
- VLE
- SHIB (or suitable domain to describe authentication services).

We will want to extend this further in future to support platform integrations where identifiers have diverged.

**Comment by alanepaull** [comment]
Current value also include:
"a URL that identifies the system within which IDENTIFIER exists, for example a VLE"

This potential value was included in case the provider had more than 1 VLE, I believe. We steered away from using "VLE" as a value for that reason. This suggests that we might need 2 things in relation to VLE at least.

It might be tricky to introduce DOMAIN_URL, which seems the obvious solution, because that would require a URL for HUSID and ULN, and any other DOMAIN type added in future - if that's possible it may be worth investigating. We would then have DOMAIN for the type of system, and DOMAIN_URL (part of primary key) for the URL.

However, if that's tricky, perhaps 'VLE' could simply mean the provider's main VLE (if that's a thing), and a URL could be any other system of unspecified type.

Any else have views on this issue?

**Comment by alanepaull** [comment]
4 Feb 20 call: Agreed to amend DOMAIN content so it uses the approach of MODULE_MAP_DOMAIN. This is to make it a STRING using local terminology, but with some reserved codes.

**Comment by Josh-Ring-jisc** [comment]
To quote the other issue:
> So proposing an additional field to student_id_map and module_map which names the provider PROVIDER_NAME. So we can differentiate between data sources and providers within the same data source.

**Comment by gmoger-jisc** [comment]
Not sure additional fields are needed for what appears to be an edge case.  I haven't seen multiple VLE's in institutions unless they are transitioning between them.  If needed we can look at how we utilise DOMAIN in our implementation so see how this might be handled if/when it arises.
Thoughts?

**Comment by alanepaull** [comment]
PROVIDER_NAME: I'm not sure I understand this issue. As far as I was aware, provider identifiers are included on each table within the implementation, so it shouldn't be necessary to include PROVIDER_NAME in an individual table. Each provider's data set is separate from other providers'.

Can you explain the issue in a bit more detail, please?

**Comment by gmoger-jisc** [comment]
What Josh is talking about is more specific to the mapping entities so that we can identify not just the domain but also the provider/platform within that domain.  So it might look like this:

DOMAIN: VLE
PROVIDER: MOODLE

DOMAIN: VLE
PROVIDER: BLACKBOARD

This would allow us to track mappings for specific platforms within the same DOMAIN, but again I think this is an edge case.  We may just need to be more specific about how we use DOMAIN.

**Comment by alanepaull** [comment]
Thanks, I now understand.

In the example above, I think it would be better to have:

DOMAIN: MOODLE
or
DOMAIN: BLACKBOARD

rather than a new property. That way, the control of the terminology lies at the local level. If we have DOMAIN and LOCAL_PLATFORM (or similar), we would be changing the meaning of DOMAIN. In this case, we would have to limit DOMAIN to a type of system (for example, VLE, HUSID, LIBRARY, and so on), and have LOCAL_PLATFORM as the specific local label. The possibility of bad data would increase, I fear, and we may run into problems with compatibility with existing data.

However, DOMAIN and LOCAL_PLATFORM is certainly a valid use case.

I'm happy to go ahead with the DOMAIN change, as follows, subject to further discussion:

## DOMAIN
### Description
Identifies the system within which IDENTIFIER exists.

### Purpose
Efficient processing of IDs, and lookup of data in xAPI statements.

### Valid values
Values should be one of the following:
- 'VLE' - this is a reserved label for the institution's primary VLE.
- a local name that identifies the system within which IDENTIFIER exists, for example 'Scientia'.

### Format
String (255)

### Notes
Local name values are not maintained in the UDD.

Any further comments? Particularly confirmation of the above, rather than the 2 properties solution, would be helpful. It would be possible to add LOCAL_PLATFORM in the future as a non-breaking change if that use case proved important.

**Comment by alanepaull** [comment]
For another branch of the discussion, see #356.

**Comment by gmoger-jisc** [comment]
Yes I think this is fine for DOMAIN and then we can decide how to best use it in our implementation.

**Comment by Josh-Ring-jisc** [comment]
> What Josh is talking about is more specific to the mapping entities so that we can identify not just the domain but also the provider/platform within that domain. So it might look like this:
> 
> DOMAIN: VLE
> PROVIDER: MOODLE
> 
> DOMAIN: VLE
> PROVIDER: BLACKBOARD
> 
> This would allow us to track mappings for specific platforms within the same DOMAIN, but again I think this is an edge case. We may just need to be more specific about how we use DOMAIN.
> 

Yes this is important to be able to support complicated arrangements in the uni, and to be able to generalise the implementation.



> In the example above, I think it would be better to have:
> 
> DOMAIN: MOODLE
> or
> DOMAIN: BLACKBOARD

No this does not work, it would be far better to reach for a general solution, rather than naming individual providers. We need the ability to distinguish the type of the data source. Naming providers without giving a type of mapping does not achieve this

**Comment by arc12** [comment]
IMO the ESSENTIAL requirement is "domain" (or call it what you want) applies to the identifiers. That is to say we can tell "these identifiers were issued by the same authority". We can have reserved words for well-known external sources such as HUSID or URIs for software systems (but not supposing these are platform host URLs as practical systems are not guaranteed to operate with a single host or even single domain).

The matter of which specific systems (named software platforms) and their type (e.g. VLE, timetabling,..) is different and should absolutely be a separate concern. It MIGHT be the case that there is a 1:1 mapping in which case, for a given institution, we might adopt shortform labels of convenience for the identifier-domain (e.g. VLE or Scientia), but these are just aliases.

The association between identifier-domains and software platforms (or platform type) should be handled separately. This does not need to be done in UDD; this is arguably something which should be handled as data platform configuration.

**Comment by Josh-Ring-jisc** [comment]
> IMO the ESSENTIAL requirement is "domain" (or call it what you want) applies to the identifiers. That is to say we can tell "these identifiers were issued by the same authority". We can have reserved words for well-known external sources such as HUSID or URIs for software systems (but not supposing these are platform host URLs as practical systems are not guaranteed to operate with a single host or even single domain).
I think we can store the name of the provider via a `PROVIDER_NAME` field and the type of source eg `ATTENDANCE_SYSTEM` or `VLE` etc, having both pieces of information is essential. 


> The matter of which specific systems (named software platforms) and their type (e.g. VLE, timetabling,..) is different and should absolutely be a separate concern. 
We need both pieces of information.


>It MIGHT be the case that there is a 1:1 mapping in which case, for a given institution, we might adopt shortform labels of convenience for the identifier-domain (e.g. VLE or Scientia), but these are just aliases.
I think we're at cross purposes here, I think we need a type of platform, and the provider of that platform. This type of platform needs a standardised naming.


>The association between identifier-domains and software platforms (or platform type) should be handled separately. This does not need to be done in UDD; this is arguably something which should be handled as data platform configuration.
I fundamentally disagree here. We are removing the mapping tables in the UDD allowing us to link platforms to the UDD, so we will rely on these tables "student_id_map" "module_map" "staff_link" to be able to link parts within the UDD itself and to other systems.

We must allow this use case to be viable. So we need to know the type of platform we're linking to, and the name of it.

**Comment by alanepaull** [comment]
Before I merge v1.5.2 into master, I think we need to resolve this issue - largely a discussion between @gmoger-jisc, @Josh-Ring-jisc and @arc12, I believe, though others may wish to take a view as well.

First, please could we be careful about naming in this discussion, or I for one will get confused. PROVIDER_NAME is the property we use for the higher education provider (university, and so on); it's not a systems supplier for timetabling, and such like. For the name of a specific system, could we use local system platform; that's clearly what we mean when we're talking about a specific timetabling system or a specific submission system like Turnitin. Then, we can refer to 'system type', when we mean a VLE or Timetabling system in general.

As @arc12 has pointed out, we may have 2 issues here:

1. Identifiers that are used within the context of a stated AUTHORITY, such as HUSID or ULN. These are not systems platforms. The source can be readily seen from the name HUSID or ULN; a platform name or type is not needed for these, the name of the identifier suffices. Do we even need these in student_id_map? They're on the student entity in any case. I note that my agreed suggestion for DOMAIN did not specifically include these authority-based IDs (just VLE plus anything local), and nobody has complained about the removal of HUSID or ULN. Is this correct? See v1.5.2 and master for comparison.

2. Identifiers that are used within the context of a local system platform, such as MOODLE or BLACKBOARD or TURNITIN, each of which could have a system type, such as VLE or SUBMISSION (or whatever a system type for Turnitin might be). For this issue, the open question is: do we need to identify both the system type and the local system platform **in the UDD**? So, there are 3 potential cases (a to c below) and a naming issue (d below), taking it for granted that we need **something** in the UDD for this:

a. In the UDD, identify system type only. Identify the local system platform in the configuration outside UDD.

b. In the UDD, identify local system platform only. Thus, we disregard the system type, because the provider/Jisc knows what it is from the local system platform name, and that could be in configuration.

c. In the UDD, identify system type and local system platform. For both of these, the key recommendation is that we don't control the names in the UDD, just store them, with the exception of 'VLE', which would be a reserved name for system type.

d. Naming issue in the UDD. We've been resistant till now to having specific names for system types and local system platforms under UDD control. I've put this issue here, so we can confirm what we want, which is, I believe, just 'VLE' as a system type under UDD control, and no other names.

I would welcome views on each of the issues here.

**Comment by Josh-Ring-jisc** [comment]
Before I merge v1.5.2 into master, I think we need to resolve this issue - largely a discussion between @gmoger-jisc, @Josh-Ring-jisc and @arc12, I believe, though others may wish to take a view as well.

First, please could we be careful about naming in this discussion, or I for one will get confused. PROVIDER_NAME is the property we use for the higher education provider (university, and so on); it's not a systems supplier for timetabling, and such like. For the name of a specific system, could we use **LOCAL_SYSTEM_PLATFORM**; that's clearly what we mean when we're talking about a specific timetabling system or a specific submission system like Turnitin. Then, we can refer to '**SYSTEM_TYPE**', when we mean a VLE or Timetabling system in general.

As @arc12 has pointed out, we may have 2 issues here:

>Identifiers that are used within the context of a stated AUTHORITY, such as HUSID or ULN. These are not systems platforms. The source can be readily seen from the name HUSID or ULN; a platform name or type is not needed for these, the name of the identifier suffices. Do we even need these in student_id_map? 

These IDs can be used to map between systems, so therefore belong in a mapping table. In combination with the '**SYSTEM_TYPE**' it will be able to document how this ID is being used in the UDD and what kind of mapping it being used for. Eg it may be that there is an externally made attendance system, (**SYSTEM_TYPE = ATTENDANCE**)   using one of these IDs to map to their internal STUDENT_ID for whatever reason.
This is really really useful to help to diagnose problems with the data, plus it makes sense to have IDs we **can** map with, in the mapping tables.


>Identifiers that are used within the context of a local system platform, such as MOODLE or BLACKBOARD or TURNITIN, each of which could have a system type, such as VLE or SUBMISSION (or whatever a system type for Turnitin might be). For this issue, the open question is: do we need to identify both the system type and the local system platform in the UDD? 

In order to validate the data and ensure it's quality, and make the data self documenting, without needing an external data source yes, we need this.




>So, there are 3 potential cases (a to c below) and a naming issue (d below), taking it for granted that we need something in the UDD for this:

>a. In the UDD, identify system type only. Identify the local system platform in the configuration outside UDD.

The data is not self documenting in this case, and is not as robust to errors, also relying on having an external source of truth defeats the purpose of the UDD.

>b. In the UDD, identify local system platform only. Thus, we disregard the system type, because the provider/Jisc knows what it is from the local system platform name, and that could be in configuration.

This is idealistic, and assumes we have perfect data, we will wish to validate this data, having **SYSTEM_TYPE** makes this process significantly easier, as we would know what system they would have to be validated against, from the data itself, otherwise it will be simple to accumulate data with errors and not know what it pertains to. Which from a data governance perspective is a disaster.


>c. In the UDD, identify system type and local system platform. For both of these, the key recommendation is that we don't control the names in the UDD, just store them, with the exception of 'VLE', which would be a reserved name for system type.

I disagree here, the vital part of this suggestion **is precisely to standardise the valid values of** **SYSTEM_TYPE**, we can append to this list freely in the future, in a point release, but I see no problem in having more standardised and enforceable data structure.


>d. Naming issue in the UDD. We've been resistant till now to having specific names for system types and local system platforms under UDD control. I've put this issue here, so we can confirm what we want, which is, I believe, just 'VLE' as a system type under UDD control, and no other names.

I think we need to revisit this resistance, in order to help us ensure better data quality, more self documenting data and more standardised data formats.




# SYSTEM_TYPE
## Description
Identifies the type of system being mapped to, for instance a VLE system.


## Purpose
Documentation of the type of system being mapped to by a STUDENT_ID_MAP_ID, helpful to validate the data against the source data system, and to manually diagnose data problems.



## Valid values
Values should be one of the following:

SYSTEM_TYPE | DESCRIPTION (ENGLISH) | 
------------|-----------------------|
VLE | Mapping to a VLE system |
ATTENDANCE | Mapping to an attendance system |
LIBRARY | Mapping to a library system |
LECTURE_CAPTURE | Mapping to a lecture capture system |
... add your's here ... | ... add your's here ... |






# LOCAL_SYSTEM_PLATFORM
## Description
Identifies the name of the platform at the institution, for the system being mapped to, for instance MOODLE or BLACKBOARD.


## Purpose
Documentation of the type of the name of the platform being mapped to by a STUDENT_ID_MAP_ID, helpful to validate the data against the source data system, and to manually diagnose data problems.


## Derivation
Jisc

## Format
String (255)

**Comment by arc12** [comment]
Previously, I said:
"The association between identifier-domains and software platforms (or platform type) should be handled separately. This does not need to be done in UDD; this is arguably something which should be handled as data platform configuration."
They key point is the first sentence.

Josh said:
"I fundamentally disagree here. We are removing the mapping tables in the UDD allowing us to link platforms to the UDD, so we will rely on these tables "student_id_map" "module_map" "staff_link" to be able to link parts within the UDD itself and to other systems."

This is the heart of the matter.
IMO we MUST NOT conflate the authority/domain for an identifier with the identification of software platforms/systems or with the naming of the function of such platforms/systems. This is because there is not a 1:1 relationship.
This is not to say that we do not need to know how to associate the data from a given platform with an id map; it is to say that they are logically (and practically) distinct. Our prior practice has been a bit sloppy in this respect but we should not dig a deeper hole.
Hence: 
A. the STUDENT_ID_MAP should map {non udd student id + the identity of the id provider} to the UDD student id. The rules/documentation for the identity of the provider should be tightened/clarified. The same rationale should apply to MODULE_MAP.
B. if we do wish to include mapping between platforms/systems and identity domains in the UDD, this should be a separate entity. Even if we do not wish to do this in UDD, I think it would be helpful to jot down what the entity would be. This should articulate with xAPI "platform". When we get to this point, we can explore "system type".

**Comment by Josh-Ring-jisc** [comment]
>Previously, I said:
"The association between identifier-domains and software platforms (or platform type) should be handled separately. This does not need to be done in UDD; this is arguably something which should be handled as data platform configuration."
They key point is the first sentence.

No I don't believe so, the UDD is the data platform, that's it's purpose.


>Josh said:
"I fundamentally disagree here. We are removing the mapping tables in the UDD allowing us to link platforms to the UDD, so we will rely on these tables "student_id_map" "module_map" "staff_link" to be able to link parts within the UDD itself and to other systems."

>This is the heart of the matter.
IMO we MUST NOT conflate the authority/domain for an identifier with the identification of software platforms/systems or with the naming of the function of such platforms/systems. This is because there is not a 1:1 relationship.

DOMAIN is separate to my post above, notice I didn't mention DOMAIN there. So this point is invalid.


> This is not to say that we do not need to know how to associate the data from a given platform with an id map; 

That is the only purpose of this entity, so of course we need to be able to do this.



>it is to say that they are logically (and practically) distinct. Our prior practice has been a bit sloppy in this respect but we should not dig a deeper hole.

You mean tying it to VLE_ID specifically, sure, but that's not what we're suggesting.


>Hence:
A. the STUDENT_ID_MAP should map {non udd student id + the identity of the id provider} to the UDD student id. 

Again yes, but I don't see how you're disagreeing here?


>The rules/documentation for the identity of the provider should be tightened/clarified. The same rationale should apply to MODULE_MAP.

What is your point?


>B. if we do wish to include mapping between platforms/systems and identity domains in the UDD, this should be a separate entity. 

You seem to be disagreeing with yourself, I really don't understand your post at all.


>Even if we do not wish to do this in UDD, I think it would be helpful to jot down what the entity would be. This should articulate with xAPI "platform". When we get to this point, we can explore "system type".

Again this doesn't make much sense

**Comment by arc12** [comment]
The UDD is **not** a data platform.
The UDD is the specification of a data model. It was instigated to be platform neutral.

**Comment by gmoger-jisc** [comment]
Only action here is:
`4 Feb 20 call: Agreed to amend DOMAIN content so it uses the approach of MODULE_MAP_DOMAIN. This is to make it a STRING using local terminology, but with some reserved codes.`

Can we please include that for 1.5.2 and close this?

We don't have use cases outside of this currently and this can be revisited as and when we do.

**Comment by gmoger-jisc** [comment]
Added for 1.6:
https://github.com/jiscdev/analytics-udd/blob/v1.6_development/udd/student_id_map.md#domain
