### ISSUE TITLE
Reintroducing GRADE_DATE

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#38]
Before the recent refactoring of the UDD, there was a 'grade' entity with a GRADE_DATE attribute. It disappeared in the refactoring, and a new DUE_DATE on the new 'student on assignment' entity remained.

See commit #28 for the change, and issue #24 for the rationale.

To complicate matters, there's also been a discussion on basecamp on [how to handle assessment data](https://basecamp.com/2737506/projects/10136653/messages/55761277), where it was noted that various data points are either not available or not uniformly from the same source in different institutions.

However, because the data is important, [both assignment due date and assignment submitted are now part of an xAPI recipe proposal](https://github.com/jiscdev/xapi-vle/issues/31) that already has implementations in both Moodle and Blackboard.

Still, Aberystwyth holds this data in their SRS (and maybe not their VLE?) and has included the assignment date data in their UDD dataset. Hence the proposal to reintroduce the GRADE_DATE on 'student on assessment instance' in order to be able to store it.

**Comment by robwynj** [comment]
Thanks for putting this up for me Wilbert. I've emailed Sandeep too, to confirm his view on this. I think this should be kept, and made optional - and the case should be moreso for historical data collection (predictive modelling creation)? I'll leave this to the data scientists to discuss!

Rob

**Comment by arc12** [comment]
happy to see this in there (I suspect it didn;t make it into the Tribal proposals because Exeter don't have date info for assessments in SITS) but suggest the semantics should be clear.

I can envisage:
- date an assignment was due
- date on which an assessment took place (e.g. an exam)
- date when a submission of coursework occurred
- date on which an initial mark/grade was entered
- date on which a "final" (maybe subject to appeal?) mark/grade was agreed
- date on which the agreed mark was recorded in the SRS

I suggest we fudge the last two as being what is being proposed in this issue, with wording along the lines of "this is the effective date of an mark agreed by the appropriate Board, or the date of recording if not available in a given SRS"... or something like...
I'm quite happy with somewhat inclusive UDD definitions, with a presumption that, for any given site, a consistent approach is taken and documented.

Cheers, Adam

**Comment by robwynj** [comment]
I don't think we have a due date, without an actual date anyway - some HEIs will have this or both :)

Cheers

Rob

**Comment by wilmTap** [comment]
I've reverted to the original definition but with an additional note to see that it is the confirmed and entered grade before exam board, and that it is typically the same date as the point at which the grade is entered into a SRS.

**Comment by robwynj** [comment]
Confirmed with Sandeep @ UNICON, should be in there.

Kind Regards

Rob

**Comment by sandeepmjay** [comment]
The GRADE_DATE we referred to would be the date added when the instructor entered/updated the grades for a student_assessment_instance. Ideally this would be a Grade history dataset which captures all the changes like initial grades, agreed grade etc and the dates associated with it. 
This dataset is particular useful to chronologically divide the datasets by timeline while creating early alert predictive models.

I agree with Adam here on the semantics. We do need to strengthen the semantics to differentiate on what information the data point intends to capture.

**Comment by wilmTap** [comment]
Wil open a new issue for high res marks in a later version
