### ISSUE TITLE
v1.2 Nits

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#43]
Starting an issue for some nit-picking for v1.2. Nothing structural...
Multiple nits in 1 issue for sanity (or so I hope), and if they  turn out not to be nits we can raise a new issue.

1  ASSESSMENT_INSTANCE would benefit from some explanation of what the entity is.
2. ASSESS_INSTANCE_ID appears to be have error in "purpose" (refers to a module instance)

**Comment by wilmTap** [comment]
Thanks for catching these nits – for that is what they are, I think –; I've aimed for speed rather than accuracy so far, so these kind of fixes are most welcome. As ever, feel free to hit the edit button, stick the change in your own branch and send a pull request.

I'm not sure Nit 2 was an error; linking instances is arguably the main purpose of IDs, but I've clarified it.
