### ISSUE TITLE
Sensible way to generate documentation

### ISSUE THREAD

**Issue by ds10** [jiscdev/analytics-udd#48]
After a day of going back and forward generating gh-pages from the master branch and getting in knots I think the key is to do something that is quick and repeatable with each new version. Perhaps a 'run this to generate documentation script in the gh-pages branch?)

Generating the documentation with pandoc might be a suggestion - it can still be hosted in gh-pages for web access and will also give other outputs such as PDF:

example pandoc to convert gh markdown to html:
for file in $(ls *.md); do pandoc -f markdown_github -t html "${file}" -o "${file}.html"; done

**Comment by arc12** [comment]
David -
I couldn't resist having a fiddle

I managed to get something approximately servicable with the following, which I executed in the udd directory. The output is vanilla but no harm in that I think. There is a Toc and page numbers but it could really do with an opening page and header and footer with version no, title, copyright and licence, acks etc. This can all be done with pandoc variables and options...

Some things I worked around
1. I found I needed xelatex option because at least one md file contains inequalities which come out as unicode chars which plain latex barfs on.
2. Tables were a problem because they use HTML not MD in the .md. There may be a way to make pandoc tolerate these but it have me lots of <td> etc in the output when attempting to go direct to pdf. Hence I go for a 2-stage conversion.

There are still some issues. The default latex template has very wide page margins and double-spacing. Among other things, this means the tables get over-squashed. (I think there is also a bug in some of the tables in the MD too). The URLs might still run off the page even with a narrower margin...

Cheers, Adam

# strip the page-level ToC
find . -type f -exec sed -i 's/\*\s*\[.*\](.*\#.*)//g' {} \;

#two stage
pandoc *.md -o udd.html
pandoc udd.html --latex-engine=xelatex --toc --toc-depth=2 -o udd.pdf

**Comment by wilmTap** [comment]
While the PDF looks very useful, I think a simple, friendly web front end to all three repos (UDD, Jisc xAPI recipes, a generic root site) is also important.

Having said that, we do need to move on the acknowledgement, version, copyright and license issues. With regard to the latter, we have already proposed using a combination of CC BY (international 4.0) for content and Apache 2.0 for code. Looking through the detail, my sense is to apply the CC BY to the UDD, and the Apache 2.0 to the recipes. It may be possible to use CC BY with the recipes as well, but that opens questions with somewhat ambiguous answers such as the distinction between code samples, code and documentation, and also the degree of derivation of ADL's xAPI spec. Applying Apache 2.0 doesn't have those issues, and the effect will be much the same.

**Comment by alanepaull** [comment]
User friendly docs version of documentation is now available from: https://docs.analytics.alpha.jisc.ac.uk/docs.

Although this is a lead-in to the github files, rather than a direct friendly version of the MD files, is this sufficient?  Noting that progress has been made since April 16 on the acknowledgement, version, copyright and license issues.

Alan
