### ISSUE TITLE
Update UDD 1.2 field definitions

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#57]
Hi @Wilbert,

Might be a good idea to provide enhanced documentation for some of the fields in UDD 1.2, eg:

COURSE_ID in Student on Course Membership
COURSE_MEMBERSHIP_ID / SEQ across the board

Might be useful to have a review, just to cover any gaps :)

Many Thanks

Rob

**Comment by wilmTap** [comment]
COURSE_ID is defined in only one place: in the course entity page. Every other mention is linked to that place. The same goes for other properties that occur in more than one entity. 

The idea was to make sure that these properties are defined in one place only, and stuff didn't get out of sync. The cost is that optional/mandatory constraints are not enforced on these properties on each entity, but, since we're pretty loose on such constraints, it seemed a price worth paying. Happy to revisit the issue, and design a different solution, though.

I hope the COURSE_MEMBERSHIP_ID / SEQ clarification hits the spot.

**Comment by robwynj** [comment]
Thanks Wilbert. COURSE_ID is fine, the others were really key :)

Cheers

Rob

**Comment by arc12** [comment]
+1 for definitions in 1 place.
It might improve clarity to put a one-liner in e.g. the course membership page which asserts that COURSE_ID in that context is a mandatory FK to COURSE.COURSE_ID, and make the link to th definition at that point, rather than in the course membership field list.

Adam
