### ISSUE TITLE
Moving MAX_POINTS from student on assessment instance to assessment instance

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#58]
MAX_POINTS is unlikely to change from student to student, so it might be best pulled from the instance. (suggested by Sandeep)

**Comment by robwynj** [comment]
Can we put this into UDD 1.3 please, as will still function ok in 1.2?

**Comment by wilmTap** [comment]
Completely agree; that's why I stuck the patch in a 1.3 branch :-)

**Comment by wilmTap** [comment]
Delete in v2.0.

**Comment by alanepaull** [comment]
Current situation is as follows:

- MAX_POINTS in SoAI in v1.3 takes alphanumeric values (string 255).  Delete MAX_POINTS in SoAI in v2.0.

- MAX_MARKS in assessment_instance is in the current master and in v1.3.  It takes decimal values.  It will stay in v1.3 and v2.0.

Keep issue open, so that we delete MAX_POINTS from SoAI in v2.0.

Alan

**Comment by alanepaull** [comment]
We've recommended that maximum marks for an assessment is picked up from assessment_instance and that the roughly equivalent MAX_POINTS property is removed from student_on_assessment_instance for v1.4.

I suggest that MAX_POINTS on student_on_assessment_instance is deprecated on v1.3.3, and deleted from v1.4 now.

Any objections?

**Comment by alanepaull** [comment]
Monday 19 March 2018: agreed to remove MAX_POINTS from student_on_assessment_instance from v1.4, and to deprecate it on v1.3.3.
