### ISSUE TITLE
StudentCourseInstance/StudentCourseMembership

### ISSUE THREAD

**Issue by ht2** [jiscdev/analytics-udd#59]
In the process of trying to map out these relations into the actual API, I've stumbled upon some issues that are already somewhat documented in #56 and #55.

However, it seems that there are a couple more, so I thought it would be good to at least illustrate on the current diagram (as of a418491eac4bcc211f8f62dc618b7f461d241a94) where I see issues and hopefully get some consensus as to a resolution.

[View my amended diagram here.](http://i.imgur.com/28eGg0U.jpg)

Issues:

- [x] Fixed in 1.2.3 - There should be no direct relation between Student Course Memberships (SCM) and Courses, unless an SCM contains a `COURSE_ID` (which it currently does not)
- [x] Fixed in 1.2.3 - A Course Instance should have a one-to-many relation to SCMs represented in the digram through `COURSE_INSTANCE_ID`
- [x] Fixed in 1.2.3 - A Course Instance has a one-to-many relation to Student Course Instances (SCI) represented in the diagram, but SCI holds no foreign key. SCIs should have a `COURSE_INSTANCE_ID`
- [x] Fixed in 1.2.3 - SCMs should have a one-to-many relation to SCIs represented in the diagram through `STUDENT_COURSE_MEMBERSHIP_ID`
- [x] Fixed in 1.2.3 - Students should have a one-to-many relationship to SCIs represented in the diagram though `STUDENT_ID`

Depending on how normalised the model is trying to be, some of these may not apply (for example could an SCI relate back to a Course Instance purely through its SCM relation?)

I'm unsure if this is the extent of issues across all the models, this is as far as I got before thinking I should probably flag them and pretty much revolves around Students at the moment.

**Comment by wilmTap** [comment]
Many thanks for the feedback- I'll respond to each issue in turn:

1. There is no COURSE_ID in the 1.2.2 diagram, but it [is in the documentation](https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md). That's amended in [the current version of the diagram](https://github.com/jiscdev/analytics-udd/blob/v1.2.3/media/UDD1_2.png)
2. Agreed; added to 1.2.3 diagram
3. That is fixed in 1.2.3 in both the docs and the diagram
4. Agreed; added to 1.2.3 diagram
5. Agreed; added to 1.2.3 diagram

**Comment by ht2** [comment]
Great stuff - I've edited the list.

In theory there's two more Student relations, but its only going to get messy (as is always the case with fully normalised db diagrams)!

Student ---< Student Module Instances
Student ---< Student Assessment Instances

And then to really start making the spaghetti fly...

Student Course Membership ---< Student Module Instances
Student Course Membership ---< Student Assessment Instances

There are even more with the MOD_IDs, but I'm not sure that connecting all the dots is helpful at that point. I'll leave it to you guys to make a call on that. Having the COURSE_INSTANCE_ID in SCIs was really the key thing for me (and 1.2.3 addresses that)

**Comment by robwynj** [comment]
I agree, found a few anomalies with COURSE_INSTANCE_ID, but should not be fairly solid!

Ta, Rob

**Comment by wilmTap** [comment]
@ht2 Yeah, I read the original diagram as indicating the main logical relations rather than the actual references. You're not the first to find that confusing, but the flip side is that showing all the reference links gets very hairy indeed.

Happy to go either way; whichever way people find easiest to read.
