### ISSUE TITLE
UDD 1.2.x - Proposed Changes (COURSE_INSTANCE_ID: SoMI, Module Instance)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#60]
Dear All,

I previously discussed this with @wilmTap earlier, and want to clarify the following potential changes to UDD 1.2.x with you all:

a) Student_on_Module_Instance - **remove** COURSE_INSTANCE_ID (not required, as per ER model) as linkage done to Module_Instance, via MOD_INSTANCE_ID;

which also then relates to....

b) Module_Instance -  which **requires** COURSE_INSTANCE_ID (missing at the moment) here for linkage, as per ER model, to Course_Instance;

Spoke to @wilmTap earlier, and he is going to review & refine the ER model (and therefore the UDD1.1 - 1.2 transition map also I assume) so we can confirm all pieces line up correctly :)

Kind Regards

Rob

**Comment by arc12** [comment]
Rob. all -
yes, I think there are a number of things like this which are really errata rather than change.

**Comment by robwynj** [comment]
Thanks @arc12. Some in the name of referential integrity!

Kind Regards, Rob

**Comment by wilmTap** [comment]
I've updated the source documents and diagrams in [the v1.2.3 branch](https://github.com/jiscdev/analytics-udd/tree/v1.2.3) after following them all through. 

I've kept COURSE_INSTANCE_ID on Student on Module Instance rather than on Module Instance for now, because I'm worried that Module Instance to Course Instance relations could get very verbose, very messy and may be mostly theoretical in the absence of a student. That is: any given module instance could typically relate to loads of course instances – both concurrently and sequentially –, only some of which have actually been taken by any student. Going to Course Instance from Module Instance via Student on Module Instance seems to solve that problem.

I could well have misunderstood the relations, though, and I'll be happy to make the change if I have.

**Comment by robwynj** [comment]
Hia,

I just want us to be clear on this - it makes sense to me that COURSE_INSTANCE_ID flows through in this way, but let me know what you think. Here's the feedback below I had from Aberystwyth on this.

Kind Regards

Rob

"On the model diagram Course instance is shown linked to Module instance, but neither contains a reference to the other in the documentation or on the model.  

This leads on to the fact that Student on Module Instance has a course_instance_id in the documentation (but not on the model) and populating it is problematic as there’s no way to obtain it through the model that I can see. Can’t go through student course membership as that now links to course instead of course instance…

Hop that makes sense, my printout of the model now has so many crossings-out and extra lines on it, it’s easy to get lost… I might just be mis-reading things as the documentation and model are out of step it’s hard to know which one is meant to be correct. I’ve only got student module instance/  student assessment instance and assessment instance to sort now, so am nearly there."

**Comment by arc12** [comment]
I think the diagram should not be interpreted as definitive, but the documentation more so, including resort to previous versions when we can't see documented rationale for change.

Craig is better positioned to comment on feasibility in relation to SITS, but the following logic works for me:
- there is no direct link of module instance to course instance; a module instance refers to a module ocurring in a period of time. I'm pretty sure direct association would be an error in some circumstances.
- course instance refers to something which students can be registered against as they progress through a course/programme. Hence, in practical terms, it is the student-on-course-instance that  provides the primary association.
- appearance of course-instance-id in student-on-module-instance isnt the primary way of associating student with course instance but provides supplementary context which may be useful in some circumstances.

i.e. I don't think it is meaningful to navigate from module instance to course instance unless you are also considering a given student whose study context is at the intersection of these 2 instances.

Adam

**Comment by robwynj** [comment]
Hi Adam,

Don't want to go so far as to suggest or recommend a "hybrid" or set of different UDD approaches here around data submission/ linkage, but it sounds like the ER model flows correctly. 

I agree with all of your points above. Should COURSE_INSTANCE_ID link a module instance with a course instance, but not a student on module instance linking with a course instance itself (see HESA model below, where the primary record aka student on course instance, links to the student on module instance). Our model is segragated in comparison, so a bit different....

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15051&href=datamodel.html

**Comment by craig-petch** [comment]
Hi All,

In SITS terms Course Instance shouldn't be included in module instance for the reasons Adam refers to.  Module instances can apply to multiple courses and for those institutions that offer highly flexible courses in both a student's module/subject choice and flexible enrolment periods this could get really unweildy in terms of generation. I think the rationale for the  inclusion of the the course instance ID in student on module instance for ease of use rather than an required relationship. In SITS terms to join course instance and module instance you should go vi course membership using the STUDENT_COURSE_MEMBERSHIP_ID and
STUDENT_COURSE_MEMBERSHIP_SEQ, but that's possibly even more confusing and I suspect is more due to how SITS works rather than a practical relationship for the UDD. Hence the inclusion of Course Instance ID on Student on a Module instance. I appreciate that's SITS related logic but maybe that'll help explain the initial thought process.

Craig

**Comment by robwynj** [comment]
Thanks Craig - see where you are coming from here! COURSE_MEMBERSHIP_ID/ SEQ need more guidance around them anyway I think, for non SITS customers obviously. Will speak to Aber and go through it with them. Many Thanks.

**Comment by craig-petch** [comment]
Ok Rob, happy to talk it through and look at helping with some further guidance around COURSE_MEMBERSHIP_ID/ SEQ. It maybe that the SEQ part isn't required for other non-SITS sites but it's fairly core to SITS. Like I said we've obviously come at it with a SITS bias so we may need to review certain things as we progress to be more SRS agnostic.

**Comment by robwynj** [comment]
Thanks Craig - so are we saying the COURSE_INSTANCE_ID in SoMI is optional.

Many Thanks, Rob

**Comment by craig-petch** [comment]
Sorry Rob. Yes if it makes life easier at the moment it's optional. For SITS sites I would include it but I guess at this stage we need to learn a bit more about how it best functions with other systems and also those that consume it and we can make a more informed decision later?

**Comment by wilmTap** [comment]
@robwynj; we've not defined optional versus mandatory very tightly yet, because sites seem to differ quite a bit in what they can support. But, yes, COURSE_INSTANCE_ID in SoMI is now optional in v1.2.3.
