### ISSUE TITLE
Review MODE with a view to collapsing most categories

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#66]
The code list for MODE is a nightmare!
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#mode

I suggest a remap (which could reference HESA codes) to a much simpler list. FT vs PT would do, but maybe there would be good sense in being a bit more sophisticated, e.g. FT, PT, Distance, Online, and a category to cover cases such as post-registration assessment which might have a different character to regular-pattern part-time.

Adam

**Comment by wilmTap** [comment]
I've made a drastically reduced set:
 
- Full time
- Part-time
- FE students in England
- On hiatus
- Not Known/ Not in Early Statistics/HEIFES population
- NULL

I've assumed that the only source data we can rely on is HESA MODE data, and that HESA MODE vocab makes it difficult/impossible to pick out things like post registration assessment or online and distance education (code 36 only applies to FE students in Wales). I've picked out 'FE students in England' because it seems a pretty significant population, of which we don't actually know what mode they study in...

More widely, I wonder whether such a simplified mode vocabulary might be best used as analysis level super classes rather than something that should go in the plain UDD data records. Some of the HESA MODE distinctions look like they maybe worthwhile in some cases. Maybe we should use my revised code list in an X property?

**Comment by robwynj** [comment]
Hi Wilbert (and all),

Yes agree which should "modernise" the mode to include what you mention above for online/ distance learning etc.

In terms of granularity - the only question i'd raise is do we need that granularity as originally specified, and if we do - then we can map from these to our simplified mode-list under X_MODE for example. 

What do we find useful, for mode, for LA or use with LA services/ tools? UNICON - any thoughts?

Kind Regards

Rob

**Comment by arc12** [comment]
Wilbert -
I'm afraid your revised list doesn't "do it" for me. I think reliance on HESA MODE is rain on our parade!
From my analysis pov, it seems to me conceptually muddy.
- FE is a matter of level, not mode of study
- hiatus is a matter of progression

I've used "mode of study" deliberately to emphasise what I think is useful about MODE: full-time, part-time, distance, and online are all very indicative of differences in the student experience and outcomes.

Suggestion: we lock the concept to "mode of study" (defined in terms of patterns of participation and attendance*) come at this from the question
"what information about mode of study is available in the SRSs used in HE and FE?"
rather than whittling at the HESA MODE.

* - accepting that there are rather grey areas between the stereotypes in reality, and that there are inter-sector differences (I don't think these differences will harm the LA; we'd apply treatments which differentiated e.g. HE and FE anyway)

**Comment by robwynj** [comment]
...... more importantly, what will we find useful, in terms of granularity for Learning Analytics - what do we really need from "MODE" here for US. They can provide granularity, we map to what we may need to see (and if simplified, so be it) in X_MODE, but ultimately what granularity do we need.

**Comment by arc12** [comment]
@robwynj - agreed about what works for us.
So far, we've just worked on FT/PT and not included distance/online at all - i.e. those students excluded from dataset. UCS does have quite a few cpd and post-registration assessment but we're not looking at those, and I think UCS pre-filters them out in the views we use.
I can imagine we'd want more detail in the future, plausibly with institutions with larger ODL or health provision, but we don't have experience to bring ...

My hunch is that detail within e.g. PT will be useless, but if we can find consistent sub-cases in student records then we should probably use them in UDD and map down to PT ourselves.

Adam

**Comment by arc12** [comment]
Could we review this for 1.3 please.
I think it is a case of either do something in that timeframe or declare "no change".

**Comment by alanepaull** [comment]
Review for 1.3 looks possible. However, I'm a little worried about the possible impact on time scale for 1.3 release.

There is considerable potential entanglement in relation to the meaning of Mode for learning analytics, I suspect.  Mode can refer to 'student load' or to 'how the course is run', epitomised by 'full time study' versus 'full time attendance'. Some of the discussion may be coloured by differences in perception over this meaning (for example, students on a distance learning course may be studying full time), even if there is formal clarity in various specs. However, it may be a lot clearer with an appreciation of the meaning of the data that's available (sorry, that may be a 'me' problem, not others).

If it's clear what's available from the data and there is clarity for the requirement within analytics, then we ought to be able to review speedily within the 1.3 time scale.  However, if this is more of a can of worms, then we would be risking pushing 1.3 release into the future or fudging, neither of which might be desirable.

Is there a strong collective appetite for review for 1.3?  If there is, then I'm happy to prioritise the work on potential solutions.

**Comment by arc12** [comment]
@alanepaull - my use of "review" was quite lightweight. It may be we agree that a deeper review is deemed not worthwhile or too much for timelines. TBH, although I raised the issue, I'm more inclined to think its not worth getting bogged down in. There is much else on 1.3 list which I'd like done soon!

**Comment by alanepaull** [comment]
Monday 16 Jan 2017: agreed to leave open and discuss after higher priority issues.

**Comment by arc12** [comment]
I move to exclude from v1.3.0, defer to later "dot" release
What we have now may be sub-optimal but it is manageable.
Work to resolve is more than I think can be achieved in the asap timeframe.

**Comment by alanepaull** [comment]
I suggest that we haven't got time to review Mode fully before we're due to launch v1.3.1, so this should move to a later release - could be a later dot release of 1.3 or move into 1.4.
Any views on this?

**Comment by alanepaull** [comment]
Issues with student_course_instance.MODE that have been identified in the current discussion:
1. too many categories
2. categories too complex for use in analytics
3. HESA mode may not be suitable
4. doesn't cover things like post registration assessment or online and distance education
5. what do we find useful for LA or use with LA services/ tools?
6. should be "defined in terms of patterns of participation and attendance"?
7. what information about mode of study is available in the SRSs used in HE and FE?

I've looked in detail at HESA, HEFCE and ILR data collections for mode. There are some critical differences.
HESA: attendance versus student load is not explicit. However, FT is "according to funding council definitions". The basic definition from the funding councils is "minimum 24 weeks study", but there are additional esoteric bits and bobs across the non-English definitions. 
HEFCE (HESES return): Only 3 categories - FT, PT, SW year out (NOT the same as HESA SW). Esoteric rules for students active for part of a year. Strict criteria for FT and SW year out. All the rest count as PT.
ILR: 7 categories - Missing (or N/A), FT full-year, FT part-year, PT other including e-learning, PT - open, PT - distance, PT - evening. These categories may be OK for FE, but probably wouldn't work well for HE.

There's no difficulty using some form of mode, if we simply adopt a mode from somebody else's data collection (typically HESA or HEFCE); because we just accept their definitions and the data as supplied to that collector. If we adopted that approach, then the HEFCE HESES one would be simplest, and probably easiest for institutions to fulfill. It would cover the points at the top of this comment, except for 4.

In the light of the above detail and the current discussion, my own review of the issues pointed up is:
1. and 2. Agreed - we probably need something shorter and more tuned to LA requirements; therefore, what are the MODE categories that are significant for LA?
3. HESA classification has the advantage of being available. Mapping from the "many and complex" HESA codes to our own "simple and effective for LA" ones may be a way forward.
4. If we want "simple and effective for LA", then we need to be careful about adding in additional categories. For example, if we need to differentiate between FT attendance, PT attendance, online and distance education, then we should try to ensure that the data supplied by institutions will support it, and be very clear that FT and PT refer to attendance not student load (always).
5. What is the current state of LA experience in respect of MODE? How is this being used at the coal face of LA?
6. Is it more useful to define MODE in terms of attendance or load? Or alternatively, if we have MODE as "attendance mode", do we need something for work load? In some other systems, I've seen MODE OF STUDY, ATTENDANCE MODE, and ATTENDANCE PATTERN used as a way to triangulate "patterns of participation and attendance". However, we need to be driven by what's available from institutions.
7. To repeat: we need to be driven by what's available from institutions. Is there clarity here? Possibly more research on this is needed?

There is an issue around the interpretation of the meaning of mode. It can variously be interpreted as "student load", "attendance mode", "attendance pattern" or a combination. This can cause difficulties; for example what does "distance learning" or "online" mean in relation to MODE? If we're categorising these separately from FT or PT, then we have a difficulty in relation to HESA and HEFCE, who don't separate these categories in relation to MODE. There are specific differences in how some institutions use mode - for example, the OU categorises most of its courses as offered in "part time" mode; they compete in the part time market, but in fact all are distance learning with tutor support. On the other hand, the OU has around 30,000 students who study with a full time load. Birkbeck University of London has both FT and PT students, but attendance is almost invariably evening only.

Whatever our definitions of MODE and its categories, we should probably take account of these issues before we go firm.

**Comment by alanepaull** [comment]
Monday 19 March 2018: Agreed to close this issue. It is currently viewed as too complex and dangerous to change the current implementation.
