### ISSUE TITLE
MAX_POINTS is free text making calculations problematic

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#73]
From Amanda:

"The MAX_POINTS value is a String and currently has "one" for most assessments in the demo data in LRW. We can convert this into the actual number "1" for the Grade Average Risk Indicator calculation, but we also see this: "The value can be any alphanumeric used by any type of marking scale. E.g. 80%, B11 or 'excellent'." in the link: https://github.com/jiscdev/analytics-udd/blob/v1.2.3/udd/student_on_assessment_instance.md#max_points

So, the question I have is: how are we supposed to calculate the Grade Average of (earnedPoints / (maxPoints * weight)) with the word "excellent"? The most favourable solution would be to make this a decimal like the other Grade Average calculation values or if it must be words, then set an implied range e.g. the value must be the english words zero through one hundred."

This fits my current definition of a breaking change (ie it's adding a constraint) so we need to work out how to handle it.

Options that I can see:

1) Revise my definition of a breaking change (more in line with Adam's 'if everyone agrees'). I still strongly believe that we must stick to not making changes that require uni's to change data they have already given as a core principle.

2) Leave it to the application to only use this value if it converts to a number.

3) Add a new value that is numeric.  MAX_POINTS_VALUE (or something)

**Comment by arc12** [comment]
I think the notes section in the spec is wrong, and a hangover from some text that was used before marks and grade were differentiated.
I think this should always be a numeric, otherwise "max" is meaningless.
And... this means the value in exchanged data should parse as a string of decimal numbers. I find it a bit hard to believe that, provided the correct SRS data is used, we'd find valid data which does not parse like this.

Other strings are invalid and IMO should be treated as NAs in the data.

Incidentally, a name "MAX_MARKS" would be more consistent with other field names. Is it not the actual/agreed marks which this value relates to?

So: option 2 and modify the UDD spec to constrain the field to be a numeric.

Adam

**Comment by robwynj** [comment]
Hi Adam,

I thought so - doesn't seem to make sense (description) - plus when I saw UNICON's comment denoting max marks as 1, so string input been chopped from 100 MAX_MARKS for their data from Aber I assume (not just UoJ).

Kind Regards

Rob

**Comment by wilmTap** [comment]
Apologies for getting the wrong end of the stick. The note isn't a left-over; from various on and offline conversations, my understanding of the property was that it was meant to indicate the maximum value of either a grade or a mark in whatever form it came. 

Agreed that a new optional MAX_MARKS property with an integer value on 'assessment instance' (which would neatly solve modelling issue #58 at the same time) is the best solution. 

Given that moving MAX_POINTS was the sole reason for a more-or-less breaking version 1.3 (i.e. it changes the datamodel, but we could sort backward compatibility in the LRW), I think we can forego that option entirely, and just do a v1.2.5.

**Comment by wilmTap** [comment]
Agreed: a new optional MAX_MARKS property with an integer value on 'assessment instance' is the best solution.
