### ISSUE TITLE
Code lists - conformity, extensibility, and machine-readable versions

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#75]
A bunch of related aspects here, being aired for discussion...

Proposal 1: UDD code lists should be published in a machine-readable format as an aid to consistent checking of conformity across the architecture.

Proposal 2: Code lists have a recommended rather than mandatory status (and are subjected to soft "validation" = reporting on conformity as a data-quality check). i.e. source data SHOULD be mapped to UDD codes but if there is a business reason for not doing so, off-list codes MAY be used.

Proposal 3: A consistent way of signalling an off-list code would be helpful to distinguish intentional extension codes from poor quality data. A 2 or 3 character reserved prefix is a bit crude but simple for people and machines to grok.

Cheers, Adam

**Comment by wilmTap** [comment]
Re Proposal 1, we have talked in the past about realising the vocab following the ADL xAPI companion spec. That uses [JSON LD for a machine readable serialisation.](https://adl.gitbooks.io/experience-xapi-vocabulary-primer/content/guidelines_for_property_use/example_xapi_vocabulary_dataset_json-ld_version.html) Would that do for people?

Re: proposal 2: if codelists are no longer mandatory, wouldn't it be easier to just make the property optional? Otherwise, what's the meaning of a mandatory property with custom values? 

Re: proposal 3: as in issue #74, we might have to assign extensions to data providers...

**Comment by wilmTap** [comment]
To be coordinated with HESA data futures

**Comment by arc12** [comment]
see also #84 re code list extraction to machine-readable format

**Comment by wilmTap** [comment]
For @ht2 feedback re implementation

**Comment by arc12** [comment]
I move to exclude from v1.3.0, defer to later "dot" release EXCEPT for agreement on continued use of the JSON format code lists as currently generated from the markdown.

Extensibility should be part of a discussion on the LRW replatforming for UDD data. i.e. a non-spec issue at the moment.
Alongside this is modular use of different code lists for FE/HE.

**Comment by alanepaull** [comment]
Summary of where we are with this issue:
_Proposal 1: UDD code lists should be published in a machine-readable format as an aid to consistent checking of conformity across the architecture._
Tool created by @arc12 to produce machine-readable code lists in JSON. In the case of JACS3, which is a very long code list, it's been included in the \media folder as a csv file. I suggest that this is sufficient as a practical solution, at least for now.

_Proposal 2: Code lists have a recommended rather than mandatory status (and are subjected to soft "validation" = reporting on conformity as a data-quality check). i.e. source data SHOULD be mapped to UDD codes but if there is a business reason for not doing so, off-list codes MAY be used._
Properties with code list values are generally optional in the UDD. However, if present, they ARE validated against the UDD specified values. More than one set of original code values (for example, from HESA or from FE ILR) are sometimes mapped to the UDD specified values. We now have an extension mechanism (https://github.com/jiscdev/analytics-udd/blob/v1.3.0/extension.md), so I suggest that this proposal is also now resolved.

_Proposal 3: A consistent way of signalling an off-list code would be helpful to distinguish intentional extension codes from poor quality data. A 2 or 3 character reserved prefix is a bit crude but simple for people and machines to grok._
This is covered by the extension mechanism (https://github.com/jiscdev/analytics-udd/blob/v1.3.0/extension.md), so this proposal is also now resolved.

Subject to agreement at next weekly meeting, this issue should be closed.
