### ISSUE TITLE
COURSE_END_DATE [1] - multiplicity should be optional

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#78]
Folks -
I think this should be an optional field since it relates to the student concerned so will not be known for students in-progress.

Adam

**Comment by arc12** [comment]
Same applies to COURSE_MARK - necessarily NULL for in-progress students

**Comment by robwynj** [comment]
Hi All,

I thought this had been done already for UDD 1.2.4?

Kind Regards

Rob

Sent from my iPhone

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant - Special Projects - JISC
Email/ Skype: Robert.Jones@jisc.ac.uk<mailto:Robert.Jones@jisc.ac.uk>
Web: www.jisc.ac.uk<http://www.jisc.ac.uk>
Mobile: 07976 508860<tel:07976%20508860>

On 15 Meh 2016, at 14:35, Adam Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:


Folks -
I think this should be an optional field since it relates to the student concerned so will not be known for students in-progress.

Adam

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/jiscdev/analytics-udd/issues/78>, or mute the thread<https://github.com/notifications/unsubscribe/AP6Ubq-jZvfqO--764nzs1GA4ug3wSOlks5qL_-wgaJpZM4I2XN1>.

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800.

**Comment by wilmTap** [comment]
My impression was that we'd handle cases with a necessarily unknown outcome with an explicit NULL rather than a missing property? Happy to change it, though.

**Comment by arc12** [comment]
I had interpreted [0..1] to mean that the attribute value is optional for an entity instance. i.e. that the attribute would not so much be "missing" as unspecified.

It occurs to me that we may also want to accommodate the case where valid datasets can omit an attribute entirely. I think this is a different class of optionality tho'.

Adam

**Comment by robwynj** [comment]
This should be optional – so yes, please accept NULL!
--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by wilmTap** [comment]
Question: do we use NULL or "N/A"?
Will tag a milestone once there is consensus.

**Comment by arc12** [comment]
There is also COURSE_GRADE, which is currently mandatory but should be optional.

I think we should also take care to separate out:
- the concept of mandatory/missing
- the representation in exchanged data

IMO the documentation should describe only the first against a given attribute. The representation may be described separately, and refer to both the data type and the binding-type. (e.g. string, and JSON exposed by LRW).

**Comment by robwynj** [comment]
Hia,

I assume something as null, being not in existence ie blank - and not a piece of test denoting "null". I stand to be corrected, but that was my original interpretation :@

Definitely COURSE_END_DATE should be optional. Can this be put in for UDD 1.2.5?

Rob

**Comment by wilmTap** [comment]
I think we have consensus: rather than use any sort of value for date or numeric data points that aren't known or aren't known yet, we simply declare the properties optional.

The "date or numeric" is important because we do have a fair few properties that have explicit codes for "unknown".

Bearing in mind Adam's point about datamodel versus binding, I'd propose that we make it explicit that the cardinality constraints are _implemented_ as the presence or absence of either the property or its value at validation.

It should also be borne in mind that this means that some important properties can't be relied on to be there. Having said that, making data providers stick in an explicit "N/A" for these properties may not solve that problem anyway.

Properties to be made optional:
student_course_membership.COURSE_MARK
student_course_membership.COURSE_END_DATE
student_on_a_module_instance.MOD_GRADE (deprecated in any case)
student_on_a_module_instance.MOD_AGREED_GRADE
student_on_a_module_instance.MOD_CREDITS_ACHIEVED
student_on_a_module_instance.MOD_COMPLETED_ATTEMPT
student_on_assessment_instance.ASSESS_AGREED_GRADE
student_on_assessment_instance.ASSESS_ACTUAL_GRADE
student_on_course_instance.X_COURSE_AVERAGE_MARK
student_on_course_instance.X_YEAR_AVERAGE_GRADE

**Comment by wilmTap** [comment]
Agreed in meeting
