### ISSUE TITLE
Denormalisation idea - MOD_ACADEMIC_YEAR

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#87]
Academic year is a key element in partitioning the data.

Problem statement:
student assessment instance in particular may contain quite a lot of data and it may be sensible to only query the LRW for data for a particular academic year rather than query for all records. This is likely to be particularly relevant as years roll-over. Using actual dates may not be possible - they may not be present, or may be unreliable.

Possible solution: 
denormalise so that the MOD_ACADEMIC_YEAR of the associated module instance appears in student assessment instance. The value must be identical to the value in the record referred to by the MOD_INSTANCE_ID FK.

By extension we could do the same for some other "instance" tables too.

**Comment by wilmTap** [comment]
So you'd want a "X_MOD_ACADEMIC_YEAR"? on student_on_assessment_instance?

**Comment by wilmTap** [comment]
Agreed.

Also add to student_mod_instance, course_instance

**Comment by wilmTap** [comment]
[course_instance already has ACADEMIC_YEAR](https://github.com/jiscdev/analytics-udd/blob/381a99fc294b03859fdc7755c3fecf61d148dd62/udd/course_instance.md#academic_year), so I've just added X_MOD_ACADEMIC_YEAR to student_on_assessment_instance and student_on_a_module_instance

**Comment by arc12** [comment]
Query:
X_ or not X_, that is the question!

I thought the discussion on Monday was to add MOD_ACADEMIC_YEAR without the X_, and without the obligation on the LRW to manufacture it (in which case, is this change to the LRW anticipated by HT2?).

(also, I think denorming the course_instance.academic_year to student_on_course_instance would be good for consistency)

Adam

**Comment by wilmTap** [comment]
Hmm. I was pretty certain it was X_, not least because otherwise it would either a) create a duplicate in the logical model, or b) create a non-backwards compatible datamodel change. Perhaps more widely, I thought X_ was what we used for any denormalised property, regardless of when it is generated and by whom.

I'll hold off merging v1.2.7 for now until we have confirmation. If it proves controversial, I'll lift this commit out of the RP #91.

If we're sticking with X_ for denormalised properties, would adding X_ACADEMIC_YEAR to student_on_course_instance do the trick?

**Comment by arc12** [comment]
My incliination would  be to reserve X_ for derived values and to not signal denormalisation in the same way. My sense is that denormalising views are best created as close to the data source as possible. Derived values might have a dependency on what the downstream applications need so may be best done away from the source because that need might change. Admittedly, denormalisation is in the interest of downstream processing, but I think it still represents source truth.

I'm not religeous about it, but my preference is simply to include denorm fields without prefixing at all.

Interested to get Michael's POV...

Adam

**Comment by arc12** [comment]
A further extension which is suggested by this academic-year denormalisation idea would be to add to Student Course Membership a field to designate the academic year of joining, with value identical to the associated course-instance for which year_stu = 1.

This is not a biggie - the tables won't be particularly large to make the joining expensive - but it will probably aid data handling

Adam

**Comment by michaelwebbjisc** [comment]
At the moment I'd rather stick to X_ for denormalised.  It just makes it clear to institutions that it's a duplicate (ie denormalised) value rather than something different. Also, I want the X_ values to be entered/maintained automatically at some point.

**Comment by robwynj** [comment]
Can these X_ fields be optional on UDD, and thus for API validation

Sent from my iPhone

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant - Special Projects - JISC
Email/ Skype: Robert.Jones@jisc.ac.uk<mailto:Robert.Jones@jisc.ac.uk>
Web: www.jisc.ac.uk<http://www.jisc.ac.uk>
Mobile: 07976 508860<tel:07976%20508860>

On 13 Gorff 2016, at 10:49, Michael Webb <notifications@github.com<mailto:notifications@github.com>> wrote:


At the moment I'd rather stick to X_ for denormalised. It just makes it clear to institutions that it's a duplicate (ie denormalised) value rather than something different. Also, I want the X_ values to be entered/maintained automatically at some point.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/jiscdev/analytics-udd/issues/87#issuecomment-232309232>, or mute the thread<https://github.com/notifications/unsubscribe/AP6Ubm9K5NF1_VhX4yTELv-1xVE1rNeoks5qVLSngaJpZM4I-E9R>.

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800.

**Comment by wilmTap** [comment]
Hi Rob; both of the X_MOD_ACADEMIC_YEAR instances are optional now. 
There's a bit of question to what extent it makes sense to declare them mandatory or optional. It depends on who we want to make responsible for their creation: whoever is doing the ETL at the institutions, or someone who has access to the LRW. The latter is ideal, but we're not there yet.
