### ISSUE TITLE
Query - USERNAME (on student additional) mandatory?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#88]
Problem statement: this data is likely to be not available in all cases where UDD data is extracted from a SRS

I can see why we'd want the LRW to expose this, but I feel we should specify the UDD so that any mandatory obligations can be translated to validation rules for import. bottom liine is that the absence of this attribute doesn't make data about a student invalid, although it may have other consequences to the ability for components in the architecture to operate. We should separate out "validation"/QA for the latter.

Propose: USERNAME [0..1]

(BTW, I note that the student-additional page says "An additional data entity." but I understood there is only a student LRW-UDD endpoint and not a student-additional.)

**Comment by wilmTap** [comment]
From past discussion, I think we decided to get rid of student_additional as a separate entity (it already is in the LRW), and merge the properties into student. Since student_additional is, er, additional, that does raise the question what needs to happen to the mandatory properties on it: make them all optional?

**Comment by wilmTap** [comment]
Agreed:
Merge student and student_additional
And make USERNAME [0 1]
LAST_NAME [0 1]
FIRST_NAME [0 1]
